### ISSUE TITLE
离线静态量化报错 paddleslim2.1.1 paddlepaddle2.1.1

### ISSUE THREAD

**Issue by LLiuzui** [PaddlePaddle/PaddleSlim#1086]
.\..\imagenet_reader.py:119: DeprecationWarning: FLIP_LEFT_RIGHT is deprecated and will be removed in Pillow 10 (2023-07-01). Use Transpose.FLIP_LEFT_RIGHT instead.
  img = img.transpose(Image.FLIP_LEFT_RIGHT)
Traceback (most recent call last):
  File "quant_post.py", line 67, in <module>
    main()
C:\Users\1\anaconda3\envs\PaddleSlim-2.1.1\lib\site-packages\paddle\fluid\reader.py:1294: DeprecationWarning: The 'warn' function is deprecated, use 'warning' instead
  logging.warn('Your reader has raised an exception!')
2022-05-09 12:53:53,398-WARNING: Your reader has raised an exception!
  File "quant_post.py", line 62, in main
    quantize(args)
  File "quant_post.py", line 56, in quantize
    bias_correction=args.bias_correction)
  File "C:\Users\1\anaconda3\envs\PaddleSlim-2.1.1\lib\site-packages\paddleslim-2.1.1-py3.7.egg\paddleslim\quant\quanter.py", line 417, in quant_post_static
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Users\1\anaconda3\envs\PaddleSlim-2.1.1\lib\site-packages\paddle\fluid\data_feeder.py", line 206, in done
    arr = arr.reshape(self.shape)
ValueError: cannot reshape array of size 32 into shape (3,300,300)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\1\anaconda3\envs\PaddleSlim-2.1.1\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\1\anaconda3\envs\PaddleSlim-2.1.1\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\1\anaconda3\envs\PaddleSlim-2.1.1\lib\site-packages\paddle\fluid\reader.py", line 1295, in __thread_main__
    six.reraise(*sys.exc_info())
  File "C:\Users\1\anaconda3\envs\PaddleSlim-2.1.1\lib\site-packages\six.py", line 719, in reraise
    raise value
  File "C:\Users\1\anaconda3\envs\PaddleSlim-2.1.1\lib\site-packages\paddle\fluid\reader.py", line 1275, in __thread_main__
    for tensors in self._tensor_reader():
  File "C:\Users\1\anaconda3\envs\PaddleSlim-2.1.1\lib\site-packages\paddle\fluid\data_feeder.py", line 249, in __call__
    yield self._done()
  File "C:\Users\1\anaconda3\envs\PaddleSlim-2.1.1\lib\site-packages\paddle\fluid\data_feeder.py", line 237, in _done
    return [c.done() for c in self.converters]
  File "C:\Users\1\anaconda3\envs\PaddleSlim-2.1.1\lib\site-packages\paddle\fluid\data_feeder.py", line 237, in <listcomp>
    return [c.done() for c in self.converters]
  File "C:\Users\1\anaconda3\envs\PaddleSlim-2.1.1\lib\site-packages\paddle\fluid\data_feeder.py", line 210, in done
    .format(self.shape, arr.shape))
ValueError: Reshape error. What is defined in data layer is (-1, 3, 300, 300), but receive (32,)

  File "C:\Users\1\anaconda3\envs\PaddleSlim-2.1.1\lib\site-packages\paddle\fluid\contrib\slim\quantization\post_training_quantization.py", line 365, in quantize
    for data in self._data_loader():
  File "C:\Users\1\anaconda3\envs\PaddleSlim-2.1.1\lib\site-packages\paddle\fluid\reader.py", line 1251, in __next__
    return self._reader.read_next()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at C:\home\workspace\Paddle_release2\paddle/fluid/operators/reader/blocking_queue.h:166)

**Comment by LLiuzui** [comment]
我用的是ImageNet val数据集 ，这是val_list.txt
[train_list.txt](https://github.com/PaddlePaddle/PaddleSlim/files/8648870/train_list.txt)

**Comment by yghstill** [comment]
@LLiuzui 根据报错，ValueError: Reshape error. What is defined in data layer is (-1, 3, 300, 300), but receive (32,)
应该是数据输入的shape没有对上，请更新PaddleSlim到最新release 2.3再试下：https://github.com/PaddlePaddle/PaddleSlim/tree/release/2.3
