### ISSUE TITLE
已安装paddleslim ，运行 python tools/train.py -c configs/ssd/ssd_mobilenet_v1_300_120e_voc.yml --slim_config configs/ssd/ssd_mobilenet_v1_qat.yml  报错

### ISSUE THREAD

**Issue by LLiuzui** [PaddlePaddle/PaddleSlim#1095]
C:\Users\1\anaconda3\envs\paddle_env\lib\site-packages\paddle\tensor\creation.py:125: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warni
ng, use `object` by itself. Doing this will not modify any behavior and is safe.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
W0511 12:37:27.197337  5304 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.6, Runtime API Version: 10.2
W0511 12:37:27.214337  5304 device_context.cc:422] device: 0, cuDNN Version: 7.6.
[05/11 12:37:29] ppdet.utils.checkpoint INFO: Finish loading model weights: C:\Users\1/.cache/paddle/weights\ssd_mobilenet_v1_300_120e_voc.pdparams
Traceback (most recent call last):
  File "C:\Users\1\anaconda3\envs\paddle_env\lib\site-packages\paddle\utils\lazy_import.py", line 32, in try_import
    mod = importlib.import_module(module_name)
  File "C:\Users\1\anaconda3\envs\paddle_env\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\1\anaconda3\envs\paddle_env\lib\site-packages\paddleslim\__init__.py", line 22, in <module>
    from paddleslim import dygraph
  File "C:\Users\1\anaconda3\envs\paddle_env\lib\site-packages\paddleslim\dygraph\__init__.py", line 2, in <module>
    from .quant import *
  File "C:\Users\1\anaconda3\envs\paddle_env\lib\site-packages\paddleslim\dygraph\quant\__init__.py", line 16, in <module>
    from . import ptq
  File "C:\Users\1\anaconda3\envs\paddle_env\lib\site-packages\paddleslim\dygraph\quant\ptq.py", line 21, in <module>
    from paddle.fluid.contrib.slim.quantization import AbsmaxQuantizer
ImportError: cannot import name 'AbsmaxQuantizer' from 'paddle.fluid.contrib.slim.quantization' (C:\Users\1\anaconda3\envs\paddle_env\lib\site-packages\paddle\fluid\contrib\slim\quantizat
ion\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 139, in <module>
    main()
  File "tools/train.py", line 129, in main
    cfg = build_slim_model(cfg, FLAGS.slim_config)
  File "C:\Users\1\anaconda3\envs\paddle_env\lib\site-packages\paddledet-2.1.0-py3.8.egg\ppdet\slim\__init__.py", line 57, in build_slim_model
    cfg['model'] = slim(model)
  File "C:\Users\1\anaconda3\envs\paddle_env\lib\site-packages\paddledet-2.1.0-py3.8.egg\ppdet\slim\quant.py", line 35, in __call__
    paddleslim = try_import('paddleslim')
  File "C:\Users\1\anaconda3\envs\paddle_env\lib\site-packages\paddle\utils\lazy_import.py", line 40, in try_import
    raise ImportError(err_msg)

**ImportError: Failed importing paddleslim. This likely means that some paddle modules require additional dependencies that have to be manually installed (usually with `pip install paddleslim`).

**Comment by yghstill** [comment]
@LLiuzui 看报错还是没有安装paddleslim成功，确认下import paddleslim是否成功

**Comment by 1190202328** [comment]
您好，我也遇到这个问题了，我已经安装好了paddleslim，但是还是说没有安装上，import也没有问题，但是PaddleDetection运行报错如下：
```
W0712 16:27:00.790410 28115 gpu_context.cc:278] Please NOTE: device: 0, GPU Compute Capability: 8.0, Driver API Version: 11.4, Runtime API Version: 11.2
W0712 16:27:00.796125 28115 gpu_context.cc:306] device: 0, cuDNN Version: 8.1.
/share/apps/anaconda3/lib/python3.7/site-packages/socks.py:58: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Callable
Traceback (most recent call last):
  File "/share/home/vilab/vilab_jiangjing/.local/lib/python3.7/site-packages/paddle/utils/lazy_import.py", line 32, in try_import
    mod = importlib.import_module(module_name)
  File "/share/apps/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'paddleslim'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 177, in <module>
    main()
  File "tools/train.py", line 164, in main
    cfg = build_slim_model(cfg, FLAGS.slim_config)
  File "/share/home/vilab/vilab_jiangjing/jiang/PaddleDetection/ppdet/slim/__init__.py", line 87, in build_slim_model
    cfg['model'] = slim(model)
  File "/share/home/vilab/vilab_jiangjing/jiang/PaddleDetection/ppdet/slim/quant.py", line 35, in __call__
    paddleslim = try_import('paddleslim')
  File "/share/home/vilab/vilab_jiangjing/.local/lib/python3.7/site-packages/paddle/utils/lazy_import.py", line 40, in try_import
    raise ImportError(err_msg)
ImportError: Failed importing paddleslim. This likely means that some paddle modules require additional dependencies that have to be manually installed (usually with `pip install paddleslim`).
~                                                                                                                                                                                         
~       
```
各个包版本如下：
<img width="362" alt="image" src="https://user-images.githubusercontent.com/81356892/178449210-f9615f0d-3b14-48ef-b078-61fa8c9896ed.png">

**Comment by 1190202328** [comment]
已经解决，安装好之后需要重启电脑才可以。

> 您好，我也遇到这个问题了，我已经安装好了paddleslim，但是还是说没有安装上，import也没有问题，但是PaddleDetection运行报错如下：
> 
> ```
> W0712 16:27:00.790410 28115 gpu_context.cc:278] Please NOTE: device: 0, GPU Compute Capability: 8.0, Driver API Version: 11.4, Runtime API Version: 11.2
> W0712 16:27:00.796125 28115 gpu_context.cc:306] device: 0, cuDNN Version: 8.1.
> /share/apps/anaconda3/lib/python3.7/site-packages/socks.py:58: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
>   from collections import Callable
> Traceback (most recent call last):
>   File "/share/home/vilab/vilab_jiangjing/.local/lib/python3.7/site-packages/paddle/utils/lazy_import.py", line 32, in try_import
>     mod = importlib.import_module(module_name)
>   File "/share/apps/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
> ModuleNotFoundError: No module named 'paddleslim'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "tools/train.py", line 177, in <module>
>     main()
>   File "tools/train.py", line 164, in main
>     cfg = build_slim_model(cfg, FLAGS.slim_config)
>   File "/share/home/vilab/vilab_jiangjing/jiang/PaddleDetection/ppdet/slim/__init__.py", line 87, in build_slim_model
>     cfg['model'] = slim(model)
>   File "/share/home/vilab/vilab_jiangjing/jiang/PaddleDetection/ppdet/slim/quant.py", line 35, in __call__
>     paddleslim = try_import('paddleslim')
>   File "/share/home/vilab/vilab_jiangjing/.local/lib/python3.7/site-packages/paddle/utils/lazy_import.py", line 40, in try_import
>     raise ImportError(err_msg)
> ImportError: Failed importing paddleslim. This likely means that some paddle modules require additional dependencies that have to be manually installed (usually with `pip install paddleslim`).
> ~                                                                                                                                                                                         
> ~       
> ```
> 
> 各个包版本如下： <img alt="image" width="362" src="https://user-images.githubusercontent.com/81356892/178449210-f9615f0d-3b14-48ef-b078-61fa8c9896ed.png">
