### ISSUE TITLE
剪枝后评估报错 InvalidArgumentError PaddleDetection2.1 PaddleSlim2.1.0

### ISSUE THREAD

**Issue by Jiashuhao518** [PaddlePaddle/PaddleSlim#1100]
(paddle) jiash21@asic-u1:~/Desktop/PaddleDetection-release-2.1/static$ python slim/prune/eval.py -c configs/ssd/ssd_mobilenet_v1_voc.yml --pruned_params "conv7_4_extra2_weights,conv7_1_extra2_weights,conv1_weights,conv5_5_sep_weights,conv2_1_sep_weights,conv7_2_extra1_weights,conv6_sep_weights,conv7_4_extra1_weights,conv7_3_extra1_weights,conv7_1_extra1_weights,conv7_2_extra2_weights,conv7_3_extra2_weights" --pruned_ratios="0.3,0.9,0.2,0.7,0.1,0.4,0.6,0.6,0.2,0.2,0.9,0.2" -o weights=output/ssd_mobilenet_v1_voc/model_final.pdparams
/home/jiash21/.conda/envs/paddle/lib/python3.7/site-packages/paddleslim/core/graph_wrapper.py:20: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  from collections import Iterable
W0512 00:48:01.676729 48192 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 11.2, Runtime API Version: 10.2
W0512 00:48:01.680086 48192 device_context.cc:465] device: 0, cuDNN Version: 8.0.
2022-05-12 00:48:17,315-INFO: pruned params: ['conv7_4_extra2_weights', 'conv7_1_extra2_weights', 'conv1_weights', 'conv5_5_sep_weights', 'conv2_1_sep_weights', 'conv7_2_extra1_weights', 'conv6_sep_weights', 'conv7_4_extra1_weights', 'conv7_3_extra1_weights', 'conv7_1_extra1_weights', 'conv7_2_extra2_weights', 'conv7_3_extra2_weights']
2022-05-12 00:48:17,315-INFO: pruned ratios: [0.3, 0.9, 0.2, 0.7, 0.1, 0.4, 0.6, 0.6, 0.2, 0.2, 0.9, 0.2]
2022-05-12 00:48:18,513-WARNING: Leaves ['batch_norm_21.tmp_0', 'batch_norm_6.tmp_0', 'batch_norm_24.tmp_2', 'batch_norm_5.tmp_2', 'batch_norm_7.tmp_1', 'batch_norm_11.tmp_0', 'batch_norm_20.tmp_0', 'batch_norm_29.tmp_2', 'batch_norm_12.tmp_2', 'batch_norm_3.tmp_2', 'transpose_6.tmp_1', 'batch_norm_10.tmp_1', 'batch_norm_32.tmp_0', 'batch_norm_28.tmp_1', 'batch_norm_15.tmp_2', 'batch_norm_17.tmp_1', 'transpose_4.tmp_1', 'batch_norm_19.tmp_1', 'flatten_16.tmp_1', 'transpose_1.tmp_1', 'transpose_5.tmp_1', 'batch_norm_16.tmp_1', 'flatten_15.tmp_1', 'flatten_4.tmp_1', 'reshape2_1.tmp_1', 'batch_norm_13.tmp_1', 'batch_norm_24.tmp_0', 'batch_norm_15.tmp_0', 'transpose_8.tmp_1', 'batch_norm_14.tmp_1', 'batch_norm_32.tmp_2', 'batch_norm_20.tmp_1', 'batch_norm_2.tmp_1', 'flatten_19.tmp_1', 'batch_norm_8.tmp_1', 'im_id', 'batch_norm_11.tmp_2', 'batch_norm_6.tmp_1', 'batch_norm_13.tmp_2', 'batch_norm_2.tmp_0', 'batch_norm_18.tmp_0', 'batch_norm_9.tmp_0', 'batch_norm_18.tmp_2', 'batch_norm_8.tmp_2', 'batch_norm_25.tmp_1', 'batch_norm_10.tmp_2', 'batch_norm_16.tmp_0', 'batch_norm_31.tmp_2', 'batch_norm_33.tmp_2', 'batch_norm_3.tmp_0', 'batch_norm_21.tmp_2', 'batch_norm_29.tmp_0', 'transpose_10.tmp_1', 'detection_output_0.tmp_0', 'flatten_7.tmp_1', 'batch_norm_19.tmp_0', 'batch_norm_22.tmp_2', 'flatten_17.tmp_1', 'batch_norm_7.tmp_2', 'batch_norm_33.tmp_0', 'batch_norm_23.tmp_1', 'batch_norm_22.tmp_0', 'flatten_5.tmp_1', 'flatten_21.tmp_1', 'batch_norm_25.tmp_2', 'batch_norm_10.tmp_0', 'batch_norm_27.tmp_1', 'flatten_10.tmp_1', 'batch_norm_19.tmp_2', 'batch_norm_4.tmp_0', 'batch_norm_25.tmp_0', 'flatten_2.tmp_1', 'batch_norm_24.tmp_1', 'batch_norm_31.tmp_1', 'batch_norm_6.tmp_2', 'flatten_12.tmp_1', 'im_shape', 'batch_norm_14.tmp_0', 'transpose_11.tmp_1', 'batch_norm_5.tmp_0', 'batch_norm_4.tmp_1', 'flatten_23.tmp_1', 'batch_norm_1.tmp_1', 'batch_norm_1.tmp_2', 'transpose_12.tmp_1', 'batch_norm_18.tmp_1', 'transpose_3.tmp_1', 'batch_norm_17.tmp_2', 'batch_norm_9.tmp_2', 'batch_norm_23.tmp_2', 'batch_norm_30.tmp_1', 'batch_norm_30.tmp_0', 'batch_norm_8.tmp_0', 'batch_norm_31.tmp_0', 'transpose_0.tmp_1', 'flatten_6.tmp_1', 'flatten_8.tmp_1', 'batch_norm_16.tmp_2', 'batch_norm_9.tmp_1', 'batch_norm_12.tmp_0', 'reshape2_0.tmp_1', 'batch_norm_4.tmp_2', 'flatten_9.tmp_1', 'batch_norm_27.tmp_2', 'transpose_7.tmp_1', 'batch_norm_21.tmp_1', 'flatten_13.tmp_1', 'batch_norm_34.tmp_1', 'flatten_11.tmp_1', 'batch_norm_13.tmp_0', 'transpose_9.tmp_1', 'batch_norm_7.tmp_0', 'flatten_18.tmp_1', 'batch_norm_33.tmp_1', 'flatten_3.tmp_1', 'batch_norm_26.tmp_1', 'flatten_0.tmp_1', 'batch_norm_30.tmp_2', 'batch_norm_26.tmp_0', 'batch_norm_34.tmp_0', 'batch_norm_26.tmp_2', 'batch_norm_28.tmp_2', 'batch_norm_0.tmp_1', 'batch_norm_27.tmp_0', 'batch_norm_29.tmp_1', 'batch_norm_23.tmp_0', 'batch_norm_32.tmp_1', 'batch_norm_3.tmp_1', 'batch_norm_28.tmp_0', 'batch_norm_22.tmp_1', 'batch_norm_20.tmp_2', 'batch_norm_0.tmp_0', 'batch_norm_34.tmp_2', 'transpose_2.tmp_1', 'batch_norm_11.tmp_1', 'batch_norm_17.tmp_0', 'batch_norm_12.tmp_1', 'flatten_14.tmp_1', 'batch_norm_1.tmp_0', 'flatten_22.tmp_1', 'gt_class', 'flatten_20.tmp_1', 'is_difficult', 'batch_norm_2.tmp_2', 'batch_norm_15.tmp_1', 'batch_norm_5.tmp_1', 'batch_norm_14.tmp_2', 'batch_norm_0.tmp_2', 'flatten_1.tmp_1', 'gt_bbox'] will be skipped when parsing graph. You can set skipped variables by option 'skip_vars'.
2022-05-12 00:48:18,954-WARNING: ('Unsupported operator named prior_box',)
2022-05-12 00:48:18,974-INFO: change groups of depthwise_conv2d(conv2_1_dw_weights) from 32 to 26;
2022-05-12 00:48:18,981-INFO: change groups of depthwise_conv2d(conv2_2_dw_weights) from 64 to 58;
2022-05-12 00:48:19,042-INFO: pruned FLOPS: 0.03032174633227653
/home/jiash21/Desktop/PaddleDetection-release-2.1/static/ppdet/data/reader.py:90: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  if isinstance(item, collections.Sequence) and len(item) == 0:
Traceback (most recent call last):
  File "slim/prune/eval.py", line 244, in <module>
    main()
  File "slim/prune/eval.py", line 200, in main
    resolution=resolution)
  File "/home/jiash21/Desktop/PaddleDetection-release-2.1/static/ppdet/utils/eval_utils.py", line 148, in eval_run
    return_numpy=False)
  File "/home/jiash21/.conda/envs/paddle/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1262, in run
    six.reraise(*sys.exc_info())
  File "/home/jiash21/.conda/envs/paddle/lib/python3.7/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/jiash21/.conda/envs/paddle/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1260, in run
    return_merged=return_merged)
  File "/home/jiash21/.conda/envs/paddle/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1415, in _run_impl
    return_merged=return_merged)
  File "/home/jiash21/.conda/envs/paddle/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1065, in _run_parallel
    tensors = exe.run(fetch_var_names, return_merged)._move_to_list()
ValueError: In user code:

    File "slim/prune/eval.py", line 244, in <module>
      main()
    File "slim/prune/eval.py", line 88, in main
      fetches = model.eval(feed_vars)
    File "/home/jiash21/Desktop/PaddleDetection-release-2.1/static/ppdet/modeling/architectures/ssd.py", line 135, in eval
      return self.build(feed_vars, 'eval')
    File "/home/jiash21/Desktop/PaddleDetection-release-2.1/static/ppdet/modeling/architectures/ssd.py", line 73, in build
      body_feats = self.backbone(im)
    File "/home/jiash21/Desktop/PaddleDetection-release-2.1/static/ppdet/modeling/backbones/mobilenet.py", line 168, in __call__
      out, 32, 64, 32, 1, scale, name=self.prefix_name + "conv2_1")
    File "/home/jiash21/Desktop/PaddleDetection-release-2.1/static/ppdet/modeling/backbones/mobilenet.py", line 121, in depthwise_separable
      name=name + "_dw")
    File "/home/jiash21/Desktop/PaddleDetection-release-2.1/static/ppdet/modeling/backbones/mobilenet.py", line 88, in _conv_norm
      bias_attr=False)
    File "/home/jiash21/.conda/envs/paddle/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 1651, in conv2d
      "data_format": data_format,
    File "/home/jiash21/.conda/envs/paddle/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/home/jiash21/.conda/envs/paddle/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3184, in append_op
      attrs=kwargs.get("attrs", None))
    File "/home/jiash21/.conda/envs/paddle/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2224, in __init__
      for frame in traceback.extract_stack():

    InvalidArgumentError: The number of input's channels should be equal to filter's channels * groups for Op(Conv). But received: the input's channels is 32, the input's shape is [32, 32, 150, 150]; the filter's channels is 1, the filter's shape is [32, 1, 3, 3]; the groups is 26, the data_format is NCHW. The error may come from wrong data_format setting.
      [Hint: Expected input_channels == filter_dims[1] * groups, but received input_channels:32 != filter_dims[1] * groups:26.] (at /paddle/paddle/fluid/operators/conv_op.cc:119)
      [operator < depthwise_conv2d > error]

**Comment by wanghaoshuang** [comment]
请问，您使用的PaddleSlim版本是？

**Comment by Jiashuhao518** [comment]
> 请问，您使用的PaddleSlim版本是？
PaddleSlim2.1.0
