### ISSUE TITLE
加载通道裁剪后的模型，再进行蒸馏报错

### ISSUE THREAD

**Issue by zhizunbao-y** [PaddlePaddle/PaddleSlim#117]
```python
    student_program = fluid.Program()
    s_startup = fluid.Program()
    with fluid.program_guard(student_program, s_startup):
        with fluid.unique_name.guard():
            # model definition
           ...
    place = fluid.CUDAPlace(0) if args.use_gpu else fluid.CPUPlace()
    exe = fluid.Executor(place)
    load_model(exe, student_program, args.pretrained_model)  #prune.io
    val_program = student_program.clone(for_test=True)

    teacher_model = models.__dict__[args.teacher_model]()
    teacher_program = fluid.Program()
    t_startup = fluid.Program()
    with fluid.program_guard(teacher_program, t_startup):
        with fluid.unique_name.guard():
            # teacher model definition
           ...

    exe.run(t_startup)
    if args.teacher_pretrained_model:
        def if_exist(var):
            return os.path.exists(
                os.path.join(args.teacher_pretrained_model, var.name))
        fluid.io.load_vars(
            exe,
            args.teacher_pretrained_model,
            main_program=teacher_program,
            predicate=if_exist)

    data_name_map = {'images': 'images'}
    merge(teacher_program, student_program, data_name_map, place)
    with fluid.program_guard(student_program, s_startup):
        dist_loss = soft_label_loss("teacher_fc_0.tmp_0", "fc_0.tmp_0", student_program)
        loss = avg_cost + dist_loss
        lr, opt = create_optimizer(args)
        opt.minimize(loss)
    exe.run(s_startup)
```
会报以下错误：
```
Error: Param and Velocity of MomentumOp should have the same dimension.
  [Hint: Expected param_dim == ctx->GetInputDim("Velocity"), but received param_dim:256 != ctx->GetInputDim("Velocity"):128.] at (/paddle/paddle/fluid/operators/optimizers/momentum_op.h:79)
  [operator < momentum > error]
```
怀疑是exe.run(s_startup)这句代码覆盖了load_model ，但是optimizer又需要初始化，请问如何解决？

**Comment by wanghaoshuang** [comment]
>怀疑是exe.run(s_startup)这句代码覆盖了load_model ，但是optimizer又需要初始化，请问如何解决？

是的，你说的对。
我让负责正六点同事看一下。您稍等。

**Comment by zhizunbao-y** [comment]
好！谢谢！辛苦了！

**Comment by baiyfbupt** [comment]
hi @zhizunbao-y , load_model加载模型需要放在`exe.run(s_startup)`初始化之后做，这样不会覆盖掉训练好的参数

**Comment by zhizunbao-y** [comment]
@baiyfbupt  按您所说的调整后仍会报错：
```
Traceback (most recent call last):
  File "/home/yuan/pycharm-2019.2.3/helpers/pydev/pydevd.py", line 2073, in <module>
    main()
  File "/home/yuan/pycharm-2019.2.3/helpers/pydev/pydevd.py", line 2067, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/yuan/pycharm-2019.2.3/helpers/pydev/pydevd.py", line 1418, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "/home/yuan/pycharm-2019.2.3/helpers/pydev/pydevd.py", line 1425, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/yuan/pycharm-2019.2.3/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/yuan/PADDLESLIM/PaddleSlim/demo/prune_dist/distill.py", line 301, in <module>
    main()
  File "/home/yuan/PADDLESLIM/PaddleSlim/demo/prune_dist/distill.py", line 297, in main
    compress(args)
  File "/home/yuan/PADDLESLIM/PaddleSlim/demo/prune_dist/distill.py", line 200, in compress
    load_model(exe, student_program, args.pretrained_model)
  File "/home/yuan/anaconda3/envs/zuanzhuslim/lib/python3.6/site-packages/paddleslim-1.0.0-py3.6.egg/paddleslim/prune/prune_io.py", line 70, in load_model
  File "/home/yuan/anaconda3/envs/zuanzhuslim/lib/python3.6/site-packages/paddleslim-1.0.0-py3.6.egg/paddleslim/core/graph_wrapper.py", line 363, in infer_shape
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::operators::MomentumOp::InferShape(paddle::framework::InferShapeContext*) const
3   paddle::framework::OpDesc::InferShape(paddle::framework::BlockDesc const&) const

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/home/yuan/anaconda3/envs/zuanzhuslim/lib/python3.6/site-packages/paddle/fluid/framework.py", line 2528, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/yuan/anaconda3/envs/zuanzhuslim/lib/python3.6/site-packages/paddle/fluid/optimizer.py", line 1006, in _append_optimize_op
    stop_gradient=True)
  File "/home/yuan/anaconda3/envs/zuanzhuslim/lib/python3.6/site-packages/paddle/fluid/optimizer.py", line 523, in _create_optimization_pass
    self._append_optimize_op(target_block, param_and_grad)
  File "/home/yuan/anaconda3/envs/zuanzhuslim/lib/python3.6/site-packages/paddle/fluid/optimizer.py", line 674, in apply_gradients
    optimize_ops = self._create_optimization_pass(params_grads)
  File "/home/yuan/anaconda3/envs/zuanzhuslim/lib/python3.6/site-packages/paddle/fluid/optimizer.py", line 704, in apply_optimize
    optimize_ops = self.apply_gradients(params_grads)
  File "/home/yuan/anaconda3/envs/zuanzhuslim/lib/python3.6/site-packages/paddle/fluid/optimizer.py", line 793, in minimize
    loss, startup_program=startup_program, params_grads=params_grads)
  File "/home/yuan/anaconda3/envs/zuanzhuslim/lib/python3.6/site-packages/paddle/fluid/dygraph/base.py", line 100, in __impl__
    return func(*args, **kwargs)
  File "/home/yuan/anaconda3/envs/zuanzhuslim/lib/python3.6/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "</home/yuan/anaconda3/envs/zuanzhuslim/lib/python3.6/site-packages/decorator.py:decorator-gen-49>", line 2, in minimize
  File "/home/yuan/PADDLESLIM/PaddleSlim/demo/prune_dist/distill.py", line 198, in compress
    opt.minimize(loss)
  File "/home/yuan/PADDLESLIM/PaddleSlim/demo/prune_dist/distill.py", line 297, in main
    compress(args)
  File "/home/yuan/PADDLESLIM/PaddleSlim/demo/prune_dist/distill.py", line 301, in <module>
    main()
  File "/home/yuan/pycharm-2019.2.3/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/yuan/pycharm-2019.2.3/helpers/pydev/pydevd.py", line 1425, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/yuan/pycharm-2019.2.3/helpers/pydev/pydevd.py", line 1418, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "/home/yuan/pycharm-2019.2.3/helpers/pydev/pydevd.py", line 2067, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/yuan/pycharm-2019.2.3/helpers/pydev/pydevd.py", line 2073, in <module>
    main()

----------------------
Error Message Summary:
----------------------
Error: Param and Velocity of MomentumOp should have the same dimension.
  [Hint: Expected param_dim == ctx->GetInputDim("Velocity"), but received param_dim:16 != ctx->GetInputDim("Velocity"):32.] at (/paddle/paddle/fluid/operators/optimizers/momentum_op.h:79)
  [operator < momentum > error]
```
上出错误好像在说参数维度是16，但是梯度的维度是32，错误定位在下列load_model方法中的*标出的位置
```
def load_model(exe, graph, dirname):
    """
    Load weights of model and information of shapes from filesystem.

    Args:
      - graph(Program|Graph): The graph to be saved.
      - dirname(str): The directory that the model saved into.
    """
    assert graph is not None and dirname is not None
    graph = GraphWrapper(graph) if isinstance(graph, Program) else graph

    SHAPES_FILE = os.path.join(dirname, _SHAPES_FILE)
    _logger.info("Load shapes of weights from {}".format(SHAPES_FILE))
    with open(SHAPES_FILE, "r") as f:
        shapes = json.load(f)
        for param, shape in shapes.items():
            graph.var(param).set_shape(shape)

    _logger.info("Load shapes of weights from {}".format(SHAPES_FILE))

    fluid.io.load_params(
        executor=exe,
        dirname=dirname,
        main_program=graph.program,
        filename=_PARAMS_FILE)
    graph.update_groups_of_conv()
    *************************
    graph.infer_shape()
    *************************
    _logger.info("Load weights from {}".format(
        os.path.join(dirname, _PARAMS_FILE)))
```

**Comment by baiyfbupt** [comment]
>上出错误好像在说参数维度是16，但是梯度的维度是32，错误定位在下列load_model方法中的*标出的位置

可以试试把蒸馏相关代码注释掉，下图红框处，是否可以正常运行呢？
![image](https://user-images.githubusercontent.com/28884066/74831902-22d40c80-5351-11ea-95f2-c69a557df5b6.png)

**Comment by zhizunbao-y** [comment]
仍会报错 ，以下是报错内容：
```
traceback (most recent call last):
  File "/home/yuan/PADDLESLIM/PaddleSlim/demo/prune_dist/distill.py", line 301, in <module>
    main()
  File "/home/yuan/PADDLESLIM/PaddleSlim/demo/prune_dist/distill.py", line 297, in main
    compress(args)
  File "/home/yuan/PADDLESLIM/PaddleSlim/demo/prune_dist/distill.py", line 200, in compress
    load_model(exe, student_program, args.pretrained_model)
  File "/home/yuan/anaconda3/envs/zuanzhuslim/lib/python3.6/site-packages/paddleslim-1.0.0-py3.6.egg/paddleslim/prune/prune_io.py", line 70, in load_model
  File "/home/yuan/anaconda3/envs/zuanzhuslim/lib/python3.6/site-packages/paddleslim-1.0.0-py3.6.egg/paddleslim/core/graph_wrapper.py", line 363, in infer_shape
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::operators::MomentumOp::InferShape(paddle::framework::InferShapeContext*) const
3   paddle::framework::OpDesc::InferShape(paddle::framework::BlockDesc const&) const

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/home/yuan/anaconda3/envs/zuanzhuslim/lib/python3.6/site-packages/paddle/fluid/framework.py", line 2528, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/yuan/anaconda3/envs/zuanzhuslim/lib/python3.6/site-packages/paddle/fluid/optimizer.py", line 1006, in _append_optimize_op
    stop_gradient=True)
  File "/home/yuan/anaconda3/envs/zuanzhuslim/lib/python3.6/site-packages/paddle/fluid/optimizer.py", line 523, in _create_optimization_pass
    self._append_optimize_op(target_block, param_and_grad)
  File "/home/yuan/anaconda3/envs/zuanzhuslim/lib/python3.6/site-packages/paddle/fluid/optimizer.py", line 674, in apply_gradients
    optimize_ops = self._create_optimization_pass(params_grads)
  File "/home/yuan/anaconda3/envs/zuanzhuslim/lib/python3.6/site-packages/paddle/fluid/optimizer.py", line 704, in apply_optimize
    optimize_ops = self.apply_gradients(params_grads)
  File "/home/yuan/anaconda3/envs/zuanzhuslim/lib/python3.6/site-packages/paddle/fluid/optimizer.py", line 793, in minimize
    loss, startup_program=startup_program, params_grads=params_grads)
  File "/home/yuan/anaconda3/envs/zuanzhuslim/lib/python3.6/site-packages/paddle/fluid/dygraph/base.py", line 100, in __impl__
    return func(*args, **kwargs)
  File "/home/yuan/anaconda3/envs/zuanzhuslim/lib/python3.6/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "</home/yuan/anaconda3/envs/zuanzhuslim/lib/python3.6/site-packages/decorator.py:decorator-gen-49>", line 2, in minimize
  File "/home/yuan/PADDLESLIM/PaddleSlim/demo/prune_dist/distill.py", line 198, in compress
    opt.minimize(loss)
  File "/home/yuan/PADDLESLIM/PaddleSlim/demo/prune_dist/distill.py", line 297, in main
    compress(args)
  File "/home/yuan/PADDLESLIM/PaddleSlim/demo/prune_dist/distill.py", line 301, in <module>
    main()

----------------------
Error Message Summary:
----------------------
Error: Param and Velocity of MomentumOp should have the same dimension.
  [Hint: Expected param_dim == ctx->GetInputDim("Velocity"), but received param_dim:16 != ctx->GetInputDim("Velocity"):32.] at (/paddle/paddle/fluid/operators/optimizers/momentum_op.h:79)
  [operator < momentum > error]

```

**Comment by zhizunbao-y** [comment]
在注释掉红框内内容的基础上，再去掉optimizer的有关代码，只运行forward的部分，代码可以运行了。那么问题是不是出在optimizer无法识别裁剪后的模型结构，还是按照代码中的模型定义进行了初始化

**Comment by wanghaoshuang** [comment]
按以下修改试试？ 
``` python
    student_program = fluid.Program()
    s_startup = fluid.Program()
    with fluid.program_guard(student_program, s_startup):
        with fluid.unique_name.guard():
            # model definition
           ...
    place = fluid.CUDAPlace(0) if args.use_gpu else fluid.CPUPlace()
    exe = fluid.Executor(place)
    exe.run(s_startup) ##################### modify
    load_model(exe, student_program, args.pretrained_model)  #prune.io
    val_program = student_program.clone(for_test=True)

    teacher_model = models.__dict__[args.teacher_model]()
    teacher_program = fluid.Program()
    t_startup = fluid.Program()
    with fluid.program_guard(teacher_program, t_startup):
        with fluid.unique_name.guard():
            # teacher model definition
           ...

    exe.run(t_startup)
    if args.teacher_pretrained_model:
        def if_exist(var):
            return os.path.exists(
                os.path.join(args.teacher_pretrained_model, var.name))
        fluid.io.load_vars(
            exe,
            args.teacher_pretrained_model,
            main_program=teacher_program,
            predicate=if_exist)

    data_name_map = {'images': 'images'}
    merge(teacher_program, student_program, data_name_map, place)
    dist_startup = fluid.Program() ##################### modify
    with fluid.program_guard(student_program, dist_startup): ##################### modify
        dist_loss = soft_label_loss("teacher_fc_0.tmp_0", "fc_0.tmp_0", student_program)
        loss = avg_cost + dist_loss
        lr, opt = create_optimizer(args)
        opt.minimize(loss)
    exe.run(dist_startup)      ##################### modify
```

**Comment by zhizunbao-y** [comment]
仍会报错，
```
Traceback (most recent call last):
  File "/home/yuan/PADDLESLIM/PaddleSlim/demo/prune_dist/distill.py", line 301, in <module>
    main()
  File "/home/yuan/PADDLESLIM/PaddleSlim/demo/prune_dist/distill.py", line 297, in main
    compress(args)
  File "/home/yuan/PADDLESLIM/PaddleSlim/demo/prune_dist/distill.py", line 282, in compress
    tb_writer)
  File "/home/yuan/PADDLESLIM/PaddleSlim/demo/prune_dist/distill.py", line 251, in train
    fetch_list=[lr.name, loss.name, avg_cost.name, dist_loss.name,  acc_top1.name])
  File "/home/yuan/anaconda3/envs/zuanzhuslim/lib/python3.6/site-packages/paddle/fluid/executor.py", line 783, in run
    six.reraise(*sys.exc_info())
  File "/home/yuan/anaconda3/envs/zuanzhuslim/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/yuan/anaconda3/envs/zuanzhuslim/lib/python3.6/site-packages/paddle/fluid/executor.py", line 778, in run
    use_program_cache=use_program_cache)
  File "/home/yuan/anaconda3/envs/zuanzhuslim/lib/python3.6/site-packages/paddle/fluid/executor.py", line 843, in _run_impl
    return_numpy=return_numpy)
  File "/home/yuan/anaconda3/envs/zuanzhuslim/lib/python3.6/site-packages/paddle/fluid/executor.py", line 677, in _run_parallel
    tensors = exe.run(fetch_var_names)._move_to_list()
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   paddle::operators::GetBroadcastDimsArrays(paddle::framework::DDim const&, paddle::framework::DDim const&, int*, int*, int*, int, int)
3   paddle::operators::ElementwiseOp::InferShape(paddle::framework::InferShapeContext*) const
4   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
5   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
6   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
7   paddle::framework::details::ComputationOpHandle::RunImpl()
8   paddle::framework::details::FastThreadedSSAGraphExecutor::RunOpSync(paddle::framework::details::OpHandleBase*)
9   paddle::framework::details::FastThreadedSSAGraphExecutor::RunOp(paddle::framework::details::OpHandleBase*, std::shared_ptr<paddle::framework::BlockingQueue<unsigned long> > const&, unsigned long*)
10  std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, void> >::_M_invoke(std::_Any_data const&)
11  std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
12  ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/home/yuan/anaconda3/envs/zuanzhuslim/lib/python3.6/site-packages/paddle/fluid/framework.py", line 2528, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/yuan/anaconda3/envs/zuanzhuslim/lib/python3.6/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/yuan/anaconda3/envs/zuanzhuslim/lib/python3.6/site-packages/paddle/fluid/layer_helper.py", line 135, in append_bias_op
    attrs={'axis': dim_start})
  File "/home/yuan/anaconda3/envs/zuanzhuslim/lib/python3.6/site-packages/paddle/fluid/layers/nn.py", line 1407, in conv2d
    pre_act = helper.append_bias_op(pre_bias, dim_start=1, dim_end=2)
  File "../models/audionet.py", line 108, in conv_layer
    bias_attr=ParamAttr(initializer=Constant(0), name=name + "_bias"))
  File "../models/audionet.py", line 14, in net
    name='conv1')
  File "/home/yuan/PADDLESLIM/PaddleSlim/demo/prune_dist/distill.py", line 130, in compress
    logits = model.net(input=sig_features, class_dim=class_dim)
  File "/home/yuan/PADDLESLIM/PaddleSlim/demo/prune_dist/distill.py", line 297, in main
    compress(args)
  File "/home/yuan/PADDLESLIM/PaddleSlim/demo/prune_dist/distill.py", line 301, in <module>
    main()

----------------------
Error Message Summary:
----------------------
Error: ShapeError: broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [128, 64, 20, 63] and the shape of Y = [16]. Received [64] in X is not equal to [16] in Y at (/paddle/paddle/fluid/operators/elementwise/elementwise_op_function.h:145)
  [operator < elementwise_add > error]
```
错误定位在了student model的第一层卷积:
```
 input = self.conv_layer(input,  
                                32, 3, 1, padding='SAME',
                                name='conv1')
```
报错中128是我的batch_size，16应该是通道数（我是用50%的prune_ratio,所以裁剪后的模型第一个卷积层输出通道为32*0.5=16），不知道为什么会有64这个数

**Comment by baiyfbupt** [comment]
>在注释掉红框内内容的基础上，再去掉optimizer的有关代码，只运行forward的部分，代码可以运行了。那么问题是不是出在optimizer无法识别裁剪后的模型结构，还是按照代码中的模型定义进行了初始化

感觉是optimizer部分存在同名不同shape变量引起的，`# teacher model definition`是怎么写的呢？这里是否也定义了一个optimizer？

**Comment by zhizunbao-y** [comment]
程序主体如下：
```python
    with fluid.program_guard(student_program, s_startup):
        with fluid.unique_name.guard():
            sig_features = fluid.layers.data(name='sig_features', shape=[None] + image_shape, dtype='float32', lod_level=0)
            label = fluid.layers.data(name='label', shape=[None, 1], dtype='int64', lod_level=0)
            # data_loader
            capacity = 64
            train_data_loader = fluid.io.DataLoader.from_generator(
                feed_list=[sig_features, label],
                capacity=capacity,
                use_double_buffer=True,
                iterable=True)
            test_data_loader = fluid.io.DataLoader.from_generator(
                feed_list=[sig_features, label],
                capacity=capacity,
                use_double_buffer=True,
                iterable=True)
            # model definition
            model = models.__dict__[args.model]()
            logits = model.net(input=sig_features, class_dim=class_dim)
            out = fluid.layers.softmax(logits)
            cost = fluid.layers.cross_entropy(input=out, label=label)
            avg_cost = fluid.layers.mean(x=cost)
            acc_top1 = fluid.layers.accuracy(input=out, label=label, k=1)

    place = fluid.CUDAPlace(0) if args.use_gpu else fluid.CPUPlace()
    exe = fluid.Executor(place)
    exe.run(s_startup)
    load_model(exe, student_program, args.pretrained_model)
    val_program = student_program.clone(for_test=True)

    places = fluid.cuda_places() if args.use_gpu else fluid.cpu_places()
    train_data_loader.set_sample_list_generator(train_reader, places)
    test_data_loader.set_sample_list_generator(test_reader, places)

    teacher_model = models.__dict__[args.teacher_model]()
    # define teacher program
    teacher_program = fluid.Program()
    t_startup = fluid.Program()
    with fluid.program_guard(teacher_program, t_startup):
        with fluid.unique_name.guard():
            sig_features = fluid.layers.data(name='sig_features', shape=[None] + image_shape, dtype='float32')
            logits = teacher_model.net(sig_features, class_dim=class_dim)
            predict = fluid.layers.softmax(logits)
    exe.run(t_startup)
    if args.teacher_pretrained_model:
        def if_exist(var):
            return os.path.exists(
                os.path.join(args.teacher_pretrained_model, var.name))

        fluid.io.load_vars(
            exe,
            args.teacher_pretrained_model,
            main_program=teacher_program,
            predicate=if_exist)

    data_name_map = {'sig_features': 'sig_features'}
    merge(teacher_program, student_program, data_name_map, place)

    dist_s_program = fluid.Program()
    with fluid.program_guard(student_program, dist_s_program):
        dist_loss = soft_label_loss("teacher_fc_0.tmp_0", "fc_0.tmp_0", student_program)
        loss = avg_cost+dist_loss
        lr, opt = create_optimizer(args)
        opt.minimize(loss)
    exe.run(dist_s_program)
    build_strategy = fluid.BuildStrategy()
    build_strategy.fuse_all_reduce_ops = False
    parallel_main = fluid.CompiledProgram(student_program).with_data_parallel(
        loss_name=loss.name, build_strategy=build_strategy)
```

**Comment by baiyfbupt** [comment]
看代码没有发现什么异常，需要再做下实验判断
1.在下面的基础上把teacher_program的定义注释掉，看是否可以正常运行

> > 上出错误好像在说参数维度是16，但是梯度的维度是32，错误定位在下列load_model方法中的*标出的位置
> 
> 可以试试把蒸馏相关代码注释掉，下图红框处，是否可以正常运行呢？
> ![image](https://user-images.githubusercontent.com/28884066/74831902-22d40c80-5351-11ea-95f2-c69a557df5b6.png)

![image](https://user-images.githubusercontent.com/28884066/74899164-0f6b8480-53d7-11ea-923f-38a70cc18c80.png)

如果可以运行可以判断是student和teacher program冲突，如果不能则是student的问题，需要继续排查

2.如果方便可不可以上传一份可运行的代码，我这里也跑一下看看

**Comment by zhizunbao-y** [comment]
去掉teacher_model的定义，并删去distillation的一系列操作，相当于直接加载裁剪后的模型继续训练，代码可以运行。https://send.firefox.com/download/1bdbe7bc73db4a43/#EcoHwc_DlV8BuX8N2tEfiQ
这是代码，请帮忙测试一下

**Comment by zhizunbao-y** [comment]
@baiyfbupt 请问有没有进展？

**Comment by baiyfbupt** [comment]
@zhizunbao-y 还在调试中，麻烦再等等，下周一之前给您个答复吧~

**Comment by zhizunbao-y** [comment]
@baiyfbupt  辛苦了！感谢！

**Comment by baiyfbupt** [comment]
@zhizunbao-y 经过排查应该是`load_model`加载剪枝模型引起的错误，附件抽离出了这个bug的最小可复现环境，可以尝试一下
1. 当注释掉`load_model`代码时，可以正常跑通训练逻辑：
    <img width="1207" alt="not_load_params" src="https://user-images.githubusercontent.com/28884066/75112718-61cfce00-5681-11ea-9ed7-4100d82a74e1.png">

2. 当不注释掉`load_model`行时，无论是否使用蒸馏策略都会出现issue中的错误

      可以用以下命令去掉蒸馏策略，去掉之后相当于单独训练剪枝模型：
      `python distill.py --use_distill=False`

    报错信息最后显示16:32不匹配的问题
    <img width="1189" alt="load_params" src="https://user-images.githubusercontent.com/28884066/75112762-d7d43500-5681-11ea-817f-d4b7791a1edf.png">

所以需要您再看一下在使用剪枝的save和load过程中是否存在其他问题，保存下来的剪枝模型能否load后继续训练，谢谢~

[prune_dist_test.zip](https://github.com/PaddlePaddle/PaddleSlim/files/4241270/prune_dist_test.zip)

**Comment by zhizunbao-y** [comment]
@baiyfbupt  save和load过程中没有其他问题
保存下来的剪枝模型可以load后继续训练，程序如下：
```
    student_program = fluid.Program()
    s_startup = fluid.Program()
    with fluid.program_guard(student_program, s_startup):
        with fluid.unique_name.guard():
            sig_features = fluid.layers.data(name='sig_features', shape=[None] + image_shape, dtype='float32', lod_level=0)
            label = fluid.layers.data(name='label', shape=[None, 1], dtype='int64', lod_level=0)
            # data_loader
            capacity = 64
            train_data_loader = fluid.io.DataLoader.from_generator(
                feed_list=[sig_features, label],
                capacity=capacity,
                use_double_buffer=True,
                iterable=True)
            test_data_loader = fluid.io.DataLoader.from_generator(
                feed_list=[sig_features, label],
                capacity=capacity,
                use_double_buffer=True,
                iterable=True)
            # model definition
            model = models.__dict__[args.model]()
            logits = model.net(input=sig_features, class_dim=class_dim)
            out = fluid.layers.softmax(logits)
            cost = fluid.layers.cross_entropy(input=out, label=label)
            avg_cost = fluid.layers.mean(x=cost)
            acc_top1 = fluid.layers.accuracy(input=out, label=label, k=1)

    place = fluid.CUDAPlace(0) if args.use_gpu else fluid.CPUPlace()
    exe = fluid.Executor(place)
    exe.run(s_startup)
    load_model(exe, student_program, args.pretrained_model)
    val_program = student_program.clone(for_test=True)

    places = fluid.cuda_places() if args.use_gpu else fluid.cpu_places()
    train_data_loader.set_sample_list_generator(train_reader, places)
    test_data_loader.set_sample_list_generator(test_reader, places)
    
    s_program = fluid.Program()
    with fluid.program_guard(student_program, s_program):
        lr, opt = create_optimizer(args)
        opt.minimize(avg_cost)
        exe.run(s_program)
```

**Comment by baiyfbupt** [comment]
上面的代码合并在一个program就会出错，这是否符合预期呢
```python    
    student_program = fluid.Program()
    s_startup = fluid.Program()
    with fluid.program_guard(student_program, s_startup):
        with fluid.unique_name.guard():
            sig_features = fluid.layers.data(name='sig_features', shape=[None] + image_shape, dtype='float32', lod_level=0)
            label = fluid.layers.data(name='label', shape=[None, 1], dtype='int64', lod_level=0)
            # data_loader
            capacity = 64
            train_data_loader = fluid.io.DataLoader.from_generator(
                feed_list=[sig_features, label],
                capacity=capacity,
                use_double_buffer=True,
                iterable=True)
            test_data_loader = fluid.io.DataLoader.from_generator(
                feed_list=[sig_features, label],
                capacity=capacity,
                use_double_buffer=True,
                iterable=True)
            # model definition
            model = models.__dict__[args.model]()
            logits = model.net(input=sig_features, class_dim=class_dim)
            out = fluid.layers.softmax(logits)
            cost = fluid.layers.cross_entropy(input=out, label=label)
            avg_cost = fluid.layers.mean(x=cost)
            acc_top1 = fluid.layers.accuracy(input=out, label=label, k=1)
            lr, opt = create_optimizer(args)
            opt.minimize(avg_cost)

    place = fluid.CUDAPlace(0) if args.use_gpu else fluid.CPUPlace()
    exe = fluid.Executor(place)
    exe.run(s_startup)
    load_model(exe, student_program, args.pretrained_model)
    val_program = student_program.clone(for_test=True)

    places = fluid.cuda_places() if args.use_gpu else fluid.cpu_places()
    train_data_loader.set_sample_list_generator(train_reader, places)
    test_data_loader.set_sample_list_generator(test_reader, places)
```
```
Traceback (most recent call last):
  File "distill.py", line 257, in <module>
    main()
  File "distill.py", line 253, in main
    compress(args)
  File "distill.py", line 158, in compress
    load_model(exe, student_program, args.pretrained_model)
  File "/usr/local/lib/python3.6/site-packages/paddleslim-1.0.0-py3.6.egg/paddleslim/prune/prune_io.py", line 71, in load_model
  File "/usr/local/lib/python3.6/site-packages/paddleslim-1.0.0-py3.6.egg/paddleslim/core/graph_wrapper.py", line 374, in infer_shape
paddle.fluid.core_avx.EnforceNotMet:

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > paddle::platform::GetTraceBackString<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*, int)
2   paddle::operators::MomentumOp::InferShape(paddle::framework::InferShapeContext*) const
3   paddle::framework::OpDesc::InferShape(paddle::framework::BlockDesc const&) const

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/usr/local/lib/python3.6/site-packages/paddle/fluid/framework.py", line 2528, in append_op
    attrs=kwargs.get("attrs", None))
  File "/usr/local/lib/python3.6/site-packages/paddle/fluid/optimizer.py", line 1006, in _append_optimize_op
    stop_gradient=True)
  File "/usr/local/lib/python3.6/site-packages/paddle/fluid/optimizer.py", line 523, in _create_optimization_pass
    self._append_optimize_op(target_block, param_and_grad)
  File "/usr/local/lib/python3.6/site-packages/paddle/fluid/optimizer.py", line 674, in apply_gradients
    optimize_ops = self._create_optimization_pass(params_grads)
  File "/usr/local/lib/python3.6/site-packages/paddle/fluid/optimizer.py", line 704, in apply_optimize
    optimize_ops = self.apply_gradients(params_grads)
  File "/usr/local/lib/python3.6/site-packages/paddle/fluid/optimizer.py", line 793, in minimize
    loss, startup_program=startup_program, params_grads=params_grads)
  File "/usr/local/lib/python3.6/site-packages/paddle/fluid/dygraph/base.py", line 100, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "</usr/local/lib/python3.6/site-packages/decorator.py:decorator-gen-50>", line 2, in minimize
  File "distill.py", line 153, in compress
    opt.minimize(avg_cost)
  File "distill.py", line 253, in main
    compress(args)
  File "distill.py", line 257, in <module>
    main()

----------------------
Error Message Summary:
----------------------
Error: Param and Velocity of MomentumOp should have the same dimension.
  [Hint: Expected param_dim == ctx->GetInputDim("Velocity"), but received param_dim:16 != ctx->GetInputDim("Velocity"):32.] at (/Paddle/paddle/fluid/operators/optimizers/momentum_op.h:79)
  [operator < momentum > error]
```

**Comment by zhizunbao-y** [comment]
@baiyfbupt 我不知道为什么合一块就会报错，剪枝的模型的save是按照demo/prune/train.py里的例子做的，用到的是paddleslim.prune.prune_io里的save_model方法，同样load_model也是配套的方法，这里应该是没有问题的，因为可以load裁剪后的模型保存成inference model。值得注意的是，demo/prune/train.py里save的是val_program，这个program在裁剪时用到了Pruner.prune()，其中有个参数时only_graph=True，意为仅裁剪结构，不裁剪参数。实在不知道该怎么办了，裁剪后的模型进行蒸馏是行不通的吗

**Comment by zhizunbao-y** [comment]
直接将裁剪系数在模型定义时乘到卷积核的个数上，再加载裁剪后的模型就没问题了
