### ISSUE TITLE
win11 报错“NameError: name 'platform' is not defined”

### ISSUE THREAD

**Issue by livingbody** [PaddlePaddle/PaddleSlim#1467]
## win11 报错“NameError: name 'platform' is not defined”

如题，跑 PaddleSlim-develop\example\auto_compression\semantic_segmentation 的 例子，报错
```bash
加载个人及系统配置文件用了 939 毫秒。
(p2) PS C:\Users\Administrator> cd C:\Users\Administrator\Desktop\PaddleSlim-develop\example\auto_compression\semantic_segmentation
(p2) PS C:\Users\Administrator\Desktop\PaddleSlim-develop\example\auto_compression\semantic_segmentation> python run.py --config_path='./configs/pp_humanseg/pp_humanseg_auto.yaml' --save_dir='./save_compressed_model'
C:\miniconda3\envs\p2\lib\site-packages\paddleseg\models\losses\decoupledsegnet_relax_boundary_loss.py:19: DeprecationWarning: Please use `shift` from the `scipy.ndimage` namespace, the `scipy.ndimage.interpolation` namespace is deprecated.  from scipy.ndimage.interpolation import shift
C:\miniconda3\envs\p2\lib\site-packages\paddleseg\transforms\functional.py:18: DeprecationWarning: Please use `distance_transform_edt` from the `scipy.ndimage` namespace, the `scipy.ndimage.morphology` namespace is deprecated.
  from scipy.ndimage.morphology import distance_transform_edt
C:\miniconda3\envs\p2\lib\site-packages\_distutils_hack\__init__.py:30: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
2022-10-16 20:06:17,416-WARNING: post-quant-hpo is not support in system other than linux
-----------  Running Arguments -----------
 Global:
         deploy_hardware: SD710
         model_dir: ./ppseg_lite_portrait_398x224_with_softmax
         model_filename: model.pdmodel
         params_filename: model.pdiparams
         reader_config: configs/dataset/humanseg_dataset.yaml
 TrainConfig:
         epochs: 14
         eval_iter: 400
         learning_rate: 0.005
         optimizer_builder:
                 optimizer:
                         type: SGD
                 weight_decay: 0.0005
------------------------------------------
W1016 20:06:17.537575  3000 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.5, Runtime API Version: 11.2
W1016 20:06:17.587304  3000 gpu_resources.cc:91] device: 0, cuDNN Version: 8.1.
[<paddle.fluid.core_avx.Tensor object at 0x0000024DC775BFB0>, <paddle.fluid.core_avx.Tensor object at 0x0000024DC73A1930>]
2022-10-16 20:06:26,207-INFO: devices: gpu
2022-10-16 20:06:27,841-INFO: Detect model type: None
Traceback (most recent call last):
  File "C:\miniconda3\envs\p2\lib\site-packages\paddleslim\auto_compression\utils\predict.py", line 66, in predict_compressed_model
    predictor = TableLatencyPredictor(hardware)
  File "C:\miniconda3\envs\p2\lib\site-packages\paddleslim\analysis\latency_predictor.py", line 80, in __init__
    self._check_opt_model()
  File "C:\miniconda3\envs\p2\lib\site-packages\paddleslim\analysis\latency_predictor.py", line 95, in _check_opt_model
    raise NotImplementedError(
NotImplementedError: latency predictor does NOT support running on Windows.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\PaddleSlim-develop\example\auto_compression\semantic_segmentation\run.py", line 168, in <module>
    main(args)
  File "C:\Users\Administrator\Desktop\PaddleSlim-develop\example\auto_compression\semantic_segmentation\run.py", line 150, in main
    ac = AutoCompression(
  File "C:\miniconda3\envs\p2\lib\site-packages\paddleslim\auto_compression\compressor.py", line 178, in __init__
    strategy_config = prepare_strategy(
  File "C:\miniconda3\envs\p2\lib\site-packages\paddleslim\auto_compression\auto_strategy.py", line 169, in prepare_strategy
    compressed_time_dict = predict_compressed_model(
  File "C:\miniconda3\envs\p2\lib\site-packages\paddleslim\auto_compression\utils\predict.py", line 70, in predict_compressed_model
    format(platform.system()))
NameError: name 'platform' is not defined
```

**Comment by zzjjay** [comment]
> NotImplementedError: latency predictor does NOT support running on Windows.

该分割模型的自动压缩示例（configs/pp_humanseg/pp_humanseg_auto.yaml）使用了延时预估器功能，延时预估器暂不支持在Windows系统使用，请尝试在Linux系统上测试该示例~

或使用非结构化稀疏、量化示例（configs/pp_humanseg/pp_humanseg_qat.yaml）进行自动压缩，这些示例不受系统环境影响~
