### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by weijingsu** [PaddlePaddle/PaddleSlim#1505]
/home/aistudio/work/PaddleSlim-release-2.4/example/auto_compression/detection
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/setuptools/depends.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
[11-07 22:19:51 MainThread @logger.py:242] Argv: run.py --config_path=./configs/ppyoloe_s_qat_dis.yaml --save_dir=./output/ --devices=cpu
[11-07 22:19:51 MainThread @utils.py:79] WRN paddlepaddle version: 2.4.0-rc0. The dynamic graph version of PARL is under development, not fully tested and supported
WARNING:root:cannot import name 'layers' from 'parl' (/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/parl/__init__.py)
2022-11-07 22:19:52,278-WARNING: Some functions fail to import, please update PaddlePaddle version to 2.4+
-----------  Running Arguments -----------
 Distillation:
	 alpha: 1.0
	 loss: soft_label
 Global:
	 Evaluation: True
	 arch: PPYOLOE
	 model_dir: /home/aistudio/work/PaddleDetection/output_inference/ppyoloe_plus_crn_s_80e_coco
	 model_filename: model.pdmodel
	 params_filename: model.pdiparams
	 reader_config: configs/yolo_reader.yml
 Quantization:
	 activation_quantize_type: moving_average_abs_max
	 onnx_format: True
	 quantize_op_types: ['conv2d', 'depthwise_conv2d']
	 use_pact: True
 TrainConfig:
	 eval_iter: 10
	 learning_rate:
		 T_max: 20
		 learning_rate: 3e-05
		 type: CosineAnnealingDecay
	 optimizer_builder:
		 optimizer:
			 type: SGD
		 weight_decay: 4e-05
	 train_iter: 10
------------------------------------------
loading annotations into memory...
Done (t=0.04s)
creating index...
index created!
loading annotations into memory...
Done (t=0.09s)
creating index...
index created!
2022-11-07 22:19:54,727-INFO: devices: cpu
2022-11-07 22:21:07,319-INFO: Detect model type: None
2022-11-07 22:21:08,289-INFO: Selected strategies: ['qat_dis']
2022-11-07 22:22:26,271-INFO: train config.distill_node_pair: ['teacher_conv2d_173.tmp_1', 'conv2d_173.tmp_1', 'teacher_conv2d_177.tmp_0', 'conv2d_177.tmp_0', 'teacher_conv2d_180.tmp_1', 'conv2d_180.tmp_1', 'teacher_conv2d_184.tmp_0', 'conv2d_184.tmp_0', 'teacher_conv2d_187.tmp_1', 'conv2d_187.tmp_1', 'teacher_conv2d_191.tmp_0', 'conv2d_191.tmp_0']
2022-11-07 22:22:27,218-INFO: quant_aware config {'weight_quantize_type': 'channel_wise_abs_max', 'activation_quantize_type': 'moving_average_abs_max', 'weight_bits': 8, 'activation_bits': 8, 'not_quant_pattern': ['skip_quant'], 'quantize_op_types': ['conv2d', 'depthwise_conv2d'], 'dtype': 'int8', 'window_size': 10000, 'moving_rate': 0.9, 'for_tensorrt': False, 'is_full_quantize': False, 'onnx_format': True, 'quant_post_first': False, 'scale_trainable': True, 'name': 'Distillation', 'loss': 'soft_label', 'node': [], 'alpha': 1.0, 'teacher_model_dir': '/home/aistudio/work/PaddleDetection/output_inference/ppyoloe_plus_crn_s_80e_coco', 'teacher_model_filename': 'model.pdmodel', 'teacher_params_filename': 'model.pdiparams'}
Adding quant op with weight:|██████████████████████████████████████████| 397/397
Adding OutScale op:|███████████████████████████████████████████████████| 382/382
2022-11-07 22:22:37,079-INFO: quant_aware config {'weight_quantize_type': 'channel_wise_abs_max', 'activation_quantize_type': 'moving_average_abs_max', 'weight_bits': 8, 'activation_bits': 8, 'not_quant_pattern': ['skip_quant'], 'quantize_op_types': ['conv2d', 'depthwise_conv2d'], 'dtype': 'int8', 'window_size': 10000, 'moving_rate': 0.9, 'for_tensorrt': False, 'is_full_quantize': False, 'onnx_format': True, 'quant_post_first': False, 'scale_trainable': True, 'name': 'Distillation', 'loss': 'soft_label', 'node': [], 'alpha': 1.0, 'teacher_model_dir': '/home/aistudio/work/PaddleDetection/output_inference/ppyoloe_plus_crn_s_80e_coco', 'teacher_model_filename': 'model.pdmodel', 'teacher_params_filename': 'model.pdiparams'}
Adding quant op with weight:|████████████████████████████████████████| 2005/2005
Adding OutScale op:|█████████████████████████████████████████████████| 1233/1233
2022-11-07 22:30:34,936-INFO: When a preprocess_func is used in quant_aware, Need to save a mapping table to match variable names in the convert phase.
2022-11-07 22:30:34,936-INFO: The mapping table is saved as './mapping_table_for_saving_inference_model'.
!!! The CPU_NUM is not specified, you should set CPU_NUM in the environment variable list.
CPU_NUM indicates that how many CPUPlace are used in the current task.
And if this parameter are set as N (equal to the number of physical CPU core) the program may be faster.

export CPU_NUM=64 # for example, set CPU_NUM as number of physical CPU core which is 64.

!!! The default number of CPU_NUM=1.
2022-11-07 22:30:54,660-INFO: Total iter: 0, epoch: 0, batch: 0, loss: [15.1287]
Traceback (most recent call last):
  File "run.py", line 193, in <module>
    main()
  File "run.py", line 183, in main
    ac.compress()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim-Stopping.at.filesystem.boundary._GIT_DISCOVERY_ACROSS_FILESYSTEM.not.set_.-py3.7.egg/paddleslim/auto_compression/compressor.py", line 569, in compress
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim-Stopping.at.filesystem.boundary._GIT_DISCOVERY_ACROSS_FILESYSTEM.not.set_.-py3.7.egg/paddleslim/auto_compression/compressor.py", line 715, in single_strategy_compress
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim-Stopping.at.filesystem.boundary._GIT_DISCOVERY_ACROSS_FILESYSTEM.not.set_.-py3.7.egg/paddleslim/auto_compression/compressor.py", line 757, in _start_train
  File "run.py", line 106, in eval_function
    res = postprocess(np.array(outs[0]), data_all['scale_factor'])
  File "/home/aistudio/work/PaddleSlim-release-2.4/example/auto_compression/detection/post_process.py", line 156, in __call__
    scale_factor)
  File "/home/aistudio/work/PaddleSlim-release-2.4/example/auto_compression/detection/post_process.py", line 108, in _non_max_suppression
    for class_index in range(0, confidences.shape[1]):
IndexError: tuple index out of range

paddle2.4，paddleslim也是2.4

**Comment by weijingsu** [comment]
请问一下百度的各位大神，这个问题在哪里呢？

**Comment by yghstill** [comment]
你的ppyoloe_plus_crn_s_80e_coco模型带nms吗？

**Comment by yghstill** [comment]
@weijingsu ppyoloe_plus的自动化压缩可直接使用ppdet中的demo运行：https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.5/deploy/auto_compression

**Comment by weijingsu** [comment]
@yghstill ppyoloe_plus_crn_s_80e_coco模型带nms的

**Comment by weijingsu** [comment]
非常感谢，您给的这个方法可行！
