### ISSUE TITLE
RuntimeError: (NotFound) Attribute op_role is not found.

### ISSUE THREAD

**Issue by Hongyuan-Liu** [PaddlePaddle/PaddleSlim#1506]
执行如下命令：
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m paddle.distributed.launch --log_dir=log --gpus 0,1,2,3 run.py \
          --config_path=./configs/yolov7_tiny_qat_dis.yaml --save_dir='./output/'
报下面的错误：
2022-11-08 15:06:05,044-INFO: Total iter: 970, epoch: 0, batch: 970, loss: [9.762854]
2022-11-08 15:06:06,677-INFO: Total iter: 980, epoch: 0, batch: 980, loss: [9.984757]
2022-11-08 15:06:08,339-INFO: Total iter: 990, epoch: 0, batch: 990, loss: [10.013017]

Evaluation stage, Run batch:|                                          | 0/40137
Evaluation stage, Run batch:|                                          | 0/40137
Traceback (most recent call last):
  File "run.py", line 148, in <module>
    main()
  File "run.py", line 136, in main
    ac.compress()
  File "/home/liuhongyuan/miniconda3/envs/paddle/lib/python3.8/site-packages/paddleslim/auto_compression/compressor.py", line 568, in compress
    self.single_strategy_compress(strategy, config, strategy_idx,
  File "/home/liuhongyuan/miniconda3/envs/paddle/lib/python3.8/site-packages/paddleslim/auto_compression/compressor.py", line 708, in single_strategy_compress
    test_program_info = self._start_train(
  File "/home/liuhongyuan/miniconda3/envs/paddle/lib/python3.8/site-packages/paddleslim/auto_compression/compressor.py", line 748, in _start_train
    metric = self.eval_function(
  File "run.py", line 70, in eval_function
    outs = exe.run(compiled_test_program,
  File "/home/liuhongyuan/miniconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/executor.py", line 1299, in run
    six.reraise(*sys.exc_info())
  File "/home/liuhongyuan/miniconda3/envs/paddle/lib/python3.8/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/liuhongyuan/miniconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/executor.py", line 1285, in run
    res = self._run_impl(
  File "/home/liuhongyuan/miniconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/executor.py", line 1520, in _run_impl
    program._compile(scope, self.place)
  File "/home/liuhongyuan/miniconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/compiler.py", line 480, in _compile
    self._executor = self._compile_data_parallel(
  File "/home/liuhongyuan/miniconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/compiler.py", line 427, in _compile_data_parallel
    return core.ParallelExecutor(
RuntimeError: (NotFound) Attribute op_role is not found.
  [Hint: Expected it != attrs_.end(), but received it == attrs_.end().] (at /paddle/paddle/fluid/framework/op_desc.cc:590)

INFO 2022-11-08 15:06:24,893 launch_utils.py:322] terminate process group gid:5867
INFO 2022-11-08 15:06:24,893 launch_utils.py:322] terminate process group gid:5867
INFO 2022-11-08 15:06:24,894 launch_utils.py:322] terminate process group gid:5870
INFO 2022-11-08 15:06:24,894 launch_utils.py:322] terminate process group gid:5870
INFO 2022-11-08 15:06:24,894 launch_utils.py:322] terminate process group gid:5874
INFO 2022-11-08 15:06:24,894 launch_utils.py:322] terminate process group gid:5874
INFO 2022-11-08 15:06:28,899 launch_utils.py:343] terminate all the procs
INFO 2022-11-08 15:06:28,899 launch_utils.py:343] terminate all the procs
ERROR 2022-11-08 15:06:28,899 launch_utils.py:640] ABORT!!! Out of all 4 trainers, the trainer process with rank=[0] was aborted. Please check its log.
ERROR 2022-11-08 15:06:28,899 launch_utils.py:640] ABORT!!! Out of all 4 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2022-11-08 15:06:32,903 launch_utils.py:343] terminate all the procs
INFO 2022-11-08 15:06:32,903 launch_utils.py:343] terminate all the procs
INFO 2022-11-08 15:06:32,904 launch.py:402] Local processes completed.
INFO 2022-11-08 15:06:32,904 launch.py:402] Local processes completed.

**Comment by yghstill** [comment]
@Hongyuan-Liu 你的Paddle版本是多少？更新到paddle 2.4.0rc版本试下呢？可以从这里下载：https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html

**Comment by linxid** [comment]
同样的问题，解决了吗
