### ISSUE TITLE
PaddleSlim 自动压缩压缩paddleX训练的picodet模型失败

### ISSUE THREAD

**Issue by Hyperpepe** [PaddlePaddle/PaddleSlim#1529]
使用的是刚发布的fastdeploy的历程。
需要重训和全量化训练picodet或者其他模型，但是目前只有一种可用
于是使用了paddlex训练了一个基于自己训练集的picodet模型。
下面是参考链接。
[https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/vision/detection/paddledetection/rk1126/picodet_detection](url)

[https://github.com/PaddlePaddle/PaddleDetection/blob/develop/configs/picodet/FULL_QUANTIZATION.md](url)

基本未改动config文件，只是规定了模型位置等关键信息。
不知道发生了什么错误导致一直报错。

报错信息

```
(paddle) lxh@lxh-Y9000P:~/amlspace/PaddleSlim-develop/example/auto_compression/detection$ python run.py --config_path=./configs/picodet_s_qat_dis.yaml --save_dir='./output/'
[11-21 15:52:05 MainThread @logger.py:242] Argv: run.py --config_path=./configs/picodet_s_qat_dis.yaml --save_dir=./output/
[11-21 15:52:05 MainThread @utils.py:73] paddlepaddle version: 2.3.2.
-----------  Running Arguments -----------
 Distillation:
	 alpha: 1.0
	 loss: l2
	 node: ['conv2d_138.tmp_1', 'tmp_2', 'conv2d_146.tmp_1', 'tmp_5', 'conv2d_162.tmp_1', 'tmp_11', 'conv2d_154.tmp_1', 'tmp_8']
 Global:
	 Evaluation: True
	 model_dir: ./model/
	 model_filename: model.pdmodel
	 params_filename: model.pdiparams
	 reader_config: ./configs/picodet_reader.yml
 Quantization:
	 activation_bits: 8
	 activation_quantize_type: moving_average_abs_max
	 quantize_op_types: ['conv2d', 'depthwise_conv2d']
	 use_pact: True
	 weight_bits: 8
 TrainConfig:
	 eval_iter: 1000
	 learning_rate:
		 T_max: 8000
		 learning_rate: 1e-05
		 type: CosineAnnealingDecay
	 optimizer_builder:
		 optimizer:
			 type: SGD
		 weight_decay: 4e-05
	 train_iter: 8000
------------------------------------------
[11/21 15:52:06] ppdet.utils.download WARNING: Config dataset_dir dataset/coco is not exits, dataset config is not valid
[11/21 15:52:06] ppdet.utils.download INFO: Dataset /home/lxh/amlspace/PaddleSlim-develop/example/auto_compression/detection/dataset/coco is not valid for reason above, try searching /home/lxh/.cache/paddle/dataset or downloading dataset...
loading annotations into memory...
Done (t=7.32s)
creating index...
index created!
[11/21 15:52:17] ppdet.data.source.coco WARNING: Found an invalid bbox in annotations: im_id: 200365, area: 0.0 x1: 296.65, y1: 388.33, x2: 297.67999999999995, y2: 388.33.
[11/21 15:52:21] ppdet.data.source.coco WARNING: Found an invalid bbox in annotations: im_id: 550395, area: 0.0 x1: 9.98, y1: 188.56, x2: 15.52, y2: 188.56.
W1121 15:52:23.563212 70729 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.8, Runtime API Version: 11.6
W1121 15:52:23.566123 70729 gpu_resources.cc:91] device: 0, cuDNN Version: 8.5.
[11/21 15:52:24] ppdet.utils.download WARNING: Config dataset_dir dataset/coco is not exits, dataset config is not valid
[11/21 15:52:24] ppdet.utils.download INFO: Dataset /home/lxh/amlspace/PaddleSlim-develop/example/auto_compression/detection/dataset/coco is not valid for reason above, try searching /home/lxh/.cache/paddle/dataset or downloading dataset...
loading annotations into memory...
Done (t=0.23s)
creating index...
index created!
2022-11-21 15:52:24,774-INFO: devices: gpu
Traceback (most recent call last):
  File "run.py", line 193, in <module>
    main()
  File "run.py", line 182, in main
    eval_callback=eval_func)
  File "/home/lxh/.conda/envs/paddle/lib/python3.6/site-packages/paddleslim/auto_compression/compressor.py", line 158, in __init__
    self.model_type = self._get_model_type()
  File "/home/lxh/.conda/envs/paddle/lib/python3.6/site-packages/paddleslim/auto_compression/compressor.py", line 310, in _get_model_type
    _, _, model_type = get_patterns(inference_program)
  File "/home/lxh/.conda/envs/paddle/lib/python3.6/site-packages/paddleslim/common/patterns.py", line 146, in get_patterns
    final_weight_node = find_final_nodes(program)
  File "/home/lxh/.conda/envs/paddle/lib/python3.6/site-packages/paddleslim/common/patterns.py", line 33, in find_final_nodes
    if op.type() in ALL_WEIGHT_OP and is_output_weight_ops(op, graph):
  File "/home/lxh/.conda/envs/paddle/lib/python3.6/site-packages/paddleslim/common/patterns_common.py", line 74, in is_output_weight_ops
    return is_output_weight_ops(next_op, graph)
  File "/home/lxh/.conda/envs/paddle/lib/python3.6/site-packages/paddleslim/common/patterns_common.py", line 74, in is_output_weight_ops
    return is_output_weight_ops(next_op, graph)
  File "/home/lxh/.conda/envs/paddle/lib/python3.6/site-packages/paddleslim/common/patterns_common.py", line 74, in is_output_weight_ops
    return is_output_weight_ops(next_op, graph)
  [Previous line repeated 979 more times]
  File "/home/lxh/.conda/envs/paddle/lib/python3.6/site-packages/paddleslim/common/patterns_common.py", line 70, in is_output_weight_ops
    next_ops = sorted(graph.next_ops(op))
  File "/home/lxh/.conda/envs/paddle/lib/python3.6/site-packages/paddleslim/core/graph_wrapper.py", line 359, in next_ops
    for out_var in op.all_outputs():
  File "/home/lxh/.conda/envs/paddle/lib/python3.6/site-packages/paddleslim/core/graph_wrapper.py", line 136, in all_outputs
    self._graph.var(var_name) for var_name in self._op.output_arg_names
  File "/home/lxh/.conda/envs/paddle/lib/python3.6/site-packages/paddleslim/core/graph_wrapper.py", line 136, in <listcomp>
    self._graph.var(var_name) for var_name in self._op.output_arg_names
  File "/home/lxh/.conda/envs/paddle/lib/python3.6/site-packages/paddleslim/core/graph_wrapper.py", line 309, in var
    return VarWrapper(block.var(name), self)
  File "/home/lxh/.conda/envs/paddle/lib/python3.6/site-packages/paddleslim/core/graph_wrapper.py", line 40, in __init__
    assert isinstance(var, (Variable, Parameter))

```
补充报错
```
RecursionError: maximum recursion depth exceeded in __instancecheck__
```

**Comment by yghstill** [comment]
@pigpigfang 你的./model/存放的是导出的预测模型吗？是否含有model.pdmodel和model.pdiparams

**Comment by Hyperpepe** [comment]
有的，是导出的预测模型。不然会读不到模型的。

**Comment by ceci3** [comment]
可以安装下最新的develop 的paddleslim试下，另外可以把你要压缩的pdmodel文件传上来吗？

**Comment by Hyperpepe** [comment]
ok

[https://github.com/pigpigfang/605-1.git](url)
里面有个model.tar,就是训练完成后生成的所有文件了

**Comment by ceci3** [comment]
导出模型的时候需要去掉后处理，自动压缩暂时不支持对有后处理的模型的压缩

**Comment by Hyperpepe** [comment]
好的我试试

**Comment by lrp123456** [comment]
@pigpigfang 请问您解决该问题了吗，我遇到类似的问题
