### ISSUE TITLE
离线量化后模型转MKLDNN模型推理报错

### ISSUE THREAD

**Issue by LiquorPerfect** [PaddlePaddle/PaddleSlim#1579]
模型为：paddleocr开源的字符方向分类器模型，https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_cls_infer.tar。
经过离线量化，在c++ paddle inference（版本为2.3.2）上进行MKLDNN，GPU上推理没有问题。
将量化好的模型使用脚本save_quant_model.py转换为mkldnn 量化模型（python环境为paddle2.4），进行c++ paddle inference推理报错，使用本工程提供的sample_tester_fake_data.cc可执行文件报错类型一样。麻烦排查一下。

WARNING: Logging before InitGoogleLogging() is written to STDERR
W1207 22:04:49.230881 109754 analysis_predictor.cc:1694] Deprecated. Please use CreatePredictor instead.
I1207 22:04:49.680517 109754 analysis_predictor.cc:937] MKLDNN is enabled
--- Running analysis [ir_graph_build_pass]
--- Running analysis [ir_graph_clean_pass]
--- Running analysis [ir_analysis_pass]
--- Running IR pass [mkldnn_placement_pass]
--- Running IR pass [simplify_with_basic_ops_pass]
--- Running IR pass [layer_norm_fuse_pass]
---    Fused 0 subgraphs into layer_norm op.
--- Running IR pass [attention_lstm_fuse_pass]
--- Running IR pass [seqconv_eltadd_relu_fuse_pass]
--- Running IR pass [seqpool_cvm_concat_fuse_pass]
--- Running IR pass [mul_lstm_fuse_pass]
--- Running IR pass [fc_gru_fuse_pass]
---    fused 0 pairs of fc gru patterns
--- Running IR pass [mul_gru_fuse_pass]
--- Running IR pass [seq_concat_fc_fuse_pass]
--- Running IR pass [gpu_cpu_squeeze2_matmul_fuse_pass]
--- Running IR pass [gpu_cpu_reshape2_matmul_fuse_pass]
--- Running IR pass [gpu_cpu_flatten2_matmul_fuse_pass]
--- Running IR pass [matmul_v2_scale_fuse_pass]
--- Running IR pass [gpu_cpu_map_matmul_v2_to_mul_pass]
--- Running IR pass [gpu_cpu_map_matmul_v2_to_matmul_pass]
--- Running IR pass [matmul_scale_fuse_pass]
--- Running IR pass [gpu_cpu_map_matmul_to_mul_pass]
--- Running IR pass [fc_fuse_pass]
--- Running IR pass [repeated_fc_relu_fuse_pass]
--- Running IR pass [squared_mat_sub_fuse_pass]
--- Running IR pass [conv_bn_fuse_pass]
--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]
--- Running IR pass [conv_transpose_bn_fuse_pass]
--- Running IR pass [conv_transpose_eltwiseadd_bn_fuse_pass]
--- Running IR pass [is_test_pass]
--- Running IR pass [runtime_context_cache_pass]
--- Running IR pass [depthwise_conv_mkldnn_pass]
--- Running IR pass [conv_bn_fuse_pass]
--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]
--- Running IR pass [conv_transpose_bn_fuse_pass]
--- Running IR pass [conv_transpose_eltwiseadd_bn_fuse_pass]
--- Running IR pass [conv_bias_mkldnn_fuse_pass]
--- Running IR pass [conv_transpose_bias_mkldnn_fuse_pass]
--- Running IR pass [conv_elementwise_add_mkldnn_fuse_pass]
---    Fused 0 projection conv (as y) + elementwise_add patterns
---    Fused 0 conv (as x) + elementwise_add patterns
---    Fused 0 conv (as y) + elementwise_add patterns
--- Running IR pass [conv_concat_relu_mkldnn_fuse_pass]
--- Running IR pass [conv_relu_mkldnn_fuse_pass]
--- Running IR pass [conv_leaky_relu_mkldnn_fuse_pass]
--- Running IR pass [conv_relu6_mkldnn_fuse_pass]
--- Running IR pass [conv_swish_mkldnn_fuse_pass]
--- Running IR pass [conv_hard_swish_mkldnn_fuse_pass]
--- Running IR pass [conv_mish_mkldnn_fuse_pass]
--- Running IR pass [conv_hard_sigmoid_mkldnn_fuse_pass]
--- Running IR pass [conv_gelu_mkldnn_fuse_pass]
--- Running IR pass [scale_matmul_fuse_pass]
---    fused 0 scale with matmul
--- Running IR pass [reshape_transpose_matmul_mkldnn_fuse_pass]
---    Fused 0 ReshapeTransposeMatmul patterns for matmul Op
---    Fused 0 ReshapeTransposeMatmul patterns for matmul Op with transpose's xshape
---    Fused 0 ReshapeTransposeMatmul patterns for matmul Op with reshape's xshape
---    Fused 0 ReshapeTransposeMatmul patterns for matmul Op with reshape's xshape with transpose's xshape
--- Running IR pass [reshape_transpose_matmul_v2_mkldnn_fuse_pass]
---    Fused 0 ReshapeTransposeMatmul patterns for matmul_v2 Op
---    Fused 0 ReshapeTransposeMatmul patterns for matmul_v2 Op with transpose's xshape
---    Fused 0 ReshapeTransposeMatmul patterns for matmul_v2 Op with reshape's xshape
---    Fused 0 ReshapeTransposeMatmul patterns for matmul_v2 Op with reshape's xshape with transpose's xshape
--- Running IR pass [matmul_transpose_reshape_fuse_pass]
---    Fused 0 MatmulTransposeReshape patterns for matmul Op
--- Running IR pass [matmul_v2_transpose_reshape_fuse_pass]
---    Fused 0 MatmulTransposeReshape patterns for matmul_v2 Op
--- Running IR pass [batch_norm_act_fuse_pass]
---    fused 0 batch norm with relu activation
--- Running IR pass [softplus_activation_mkldnn_fuse_pass]
---    fused 0 softplus with relu activation
---    fused 0 softplus with tanh activation
---    fused 0 softplus with leaky_relu activation
---    fused 0 softplus with swish activation
---    fused 0 softplus with hardswish activation
---    fused 0 softplus with sqrt activation
---    fused 0 softplus with abs activation
---    fused 0 softplus with clip activation
---    fused 0 softplus with gelu activation
---    fused 0 softplus with relu6 activation
---    fused 0 softplus with sigmoid activation
--- Running IR pass [elt_act_mkldnn_fuse_pass]
---    fused 0 elementwise_add with relu activation
---    fused 0 elementwise_add with tanh activation
---    fused 0 elementwise_add with leaky_relu activation
---    fused 0 elementwise_add with swish activation
---    fused 0 elementwise_add with hardswish activation
---    fused 0 elementwise_add with sqrt activation
---    fused 0 elementwise_add with abs activation
---    fused 0 elementwise_add with clip activation
---    fused 0 elementwise_add with gelu activation
---    fused 0 elementwise_add with relu6 activation
---    fused 0 elementwise_add with sigmoid activation
---    fused 0 elementwise_sub with relu activation
---    fused 0 elementwise_sub with tanh activation
---    fused 0 elementwise_sub with leaky_relu activation
---    fused 0 elementwise_sub with swish activation
---    fused 0 elementwise_sub with hardswish activation
---    fused 0 elementwise_sub with sqrt activation
---    fused 0 elementwise_sub with abs activation
---    fused 0 elementwise_sub with clip activation
---    fused 0 elementwise_sub with gelu activation
---    fused 0 elementwise_sub with relu6 activation
---    fused 0 elementwise_sub with sigmoid activation
---    fused 0 elementwise_mul with relu activation
---    fused 0 elementwise_mul with tanh activation
---    fused 0 elementwise_mul with leaky_relu activation
---    fused 0 elementwise_mul with swish activation
---    fused 0 elementwise_mul with hardswish activation
---    fused 0 elementwise_mul with sqrt activation
---    fused 0 elementwise_mul with abs activation
---    fused 0 elementwise_mul with clip activation
---    fused 0 elementwise_mul with gelu activation
---    fused 0 elementwise_mul with relu6 activation
---    fused 0 elementwise_mul with sigmoid activation
--- Running analysis [ir_params_sync_among_devices_pass]
--- Running analysis [adjust_cudnn_workspace_size_pass]
--- Running analysis [inference_op_replace_pass]
--- Running analysis [ir_graph_to_program_pass]
I1207 22:04:50.040491 109754 analysis_predictor.cc:1007] ======= optimize end =======
I1207 22:04:50.042610 109754 naive_executor.cc:102] ---  skip [feed], feed -> x
I1207 22:04:50.044800 109754 naive_executor.cc:102] ---  skip [save_infer_model/scale_0.tmp_0], fetch -> fetch
Batch size 1
I1207 22:04:50.051362 109754 device_context.cc:737] oneDNN v2.5.4
terminate called after throwing an instance of 'phi::enforce::EnforceNotMet'
  what():  

  Compile Traceback (most recent call last):
    File "/Applications/PyCharm CE 2022.2 EAP.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 2195, in <module>
      main()
    File "/Applications/PyCharm CE 2022.2 EAP.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 2177, in main
      globals = debugger.run(setup['file'], None, None, is_module)
    File "/Applications/PyCharm CE 2022.2 EAP.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 1489, in run
      return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
    File "/Applications/PyCharm CE 2022.2 EAP.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 1496, in _exec
      pydev_imports.execfile(file, globals, locals)  # execute the script
    File "/Applications/PyCharm CE 2022.2 EAP.app/Contents/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
      exec(compile(contents+"\n", file, 'exec'), glob, loc)
    File "/Users/zhoujun20/Desktop/工作相关/table/PaddleOCR/tools/export_model.py", line 255, in <module>
      main()
    File "/Users/zhoujun20/Desktop/工作相关/table/PaddleOCR/tools/export_model.py", line 250, in main
      export_single_model(
    File "/Users/zhoujun20/Desktop/工作相关/table/PaddleOCR/tools/export_model.py", line 171, in export_single_model
      paddle.jit.save(model, save_path)
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/dygraph/jit.py", line 631, in wrapper
      func(layer, path, input_spec, **configs)
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/dygraph/jit.py", line 860, in save
      concrete_program = static_func.concrete_program_specify_input_spec(
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 527, in concrete_program_specify_input_spec
      concrete_program, _ = self.get_concrete_program(
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 436, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 801, in __getitem__
      self._caches[item_id] = self._build_once(item)
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 785, in _build_once
      concrete_program = ConcreteProgram.from_func_spec(
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 733, in from_func_spec
      outputs = static_func(*inputs)
    File "/var/folders/9_/fj3gl_0x7mx4_bp7wx1q6z6h0000gp/T/tmp_owozyrl.py", line 27, in forward
      x = paddle.jit.dy2static.convert_ifelse(self.use_backbone, true_fn_1,
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 211, in convert_ifelse
      out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 257, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/Users/zhoujun20/Desktop/工作相关/table/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 86, in forward
      x = self.backbone(x)
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/Users/zhoujun20/Desktop/工作相关/table/PaddleOCR/ppocr/modeling/backbones/rec_mobilenet_v3.py", line 134, in forward
      x = self.conv1(x)
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/Users/zhoujun20/Desktop/工作相关/table/PaddleOCR/ppocr/modeling/backbones/det_mobilenet_v3.py", line 179, in forward
      x = self.conv(x)
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/nn/layer/conv.py", line 666, in forward
      out = F.conv._conv_nd(
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/nn/functional/conv.py", line 168, in _conv_nd
      helper.append_op(
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/layer_helper.py", line 44, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/framework.py", line 3615, in append_op
      op = Operator(
    File "/Users/zhoujun20/opt/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/framework.py", line 2635, in __init__
      for frame in traceback.extract_stack():

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::AnalysisPredictor::ZeroCopyRun()
1   paddle::framework::NaiveExecutor::Run()
2   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, phi::Place const&)
3   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, phi::Place const&) const
4   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, phi::Place const&, paddle::framework::RuntimeContext*) const
5   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<phi::CPUPlace, false, 0ul, paddle::operators::ConvMKLDNNOpKernel<signed char, float> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
6   paddle::operators::ConvMKLDNNOpKernel<signed char, float>::Compute(paddle::framework::ExecutionContext const&) const

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: The type of data we are trying to retrieve does not match the type of data currently contained in the container.
  [Hint: Expected dtype() == paddle::experimental::CppTypeToDataType<T>::Type(), but received dtype():2 != paddle::experimental::CppTypeToDataType<T>::Type():12.] (at /paddle/paddle/phi/core/dense_tensor.cc:137)
  [operator < conv2d > error]
run.sh: line 43: 109754 Aborted                 GLOG_logtostderr=1 ./build/sample_tester_fake_data --infer_model=${MODEL_DIR} --batch_size=1 --num_threads=${num_threads} --iterations=${ITERATIONS} --with_accuracy_layer=${with_accuracy_layer} --use_analysis=${with_analysis}

**Comment by yghstill** [comment]
@LiquorPerfect 使用量化新格式，在离线量化时设置onnx_format=True，然后使用PaddleSlim 2.4.0和PaddlePaddle 2.4.0+再量化试下，可直接预测，无需再使用save_quant_model.py转换mkldnn 量化模型。

**Comment by LiquorPerfect** [comment]
@yghstill 感谢排查，我这边使用paddleslim2.4，paddlepaddle2.4，使用模型自动化压缩工具对 paddleocr开源的‘字符方向分类模型’和'字符检测模型'分别进行自动化压缩（训练量化+知识蒸馏），然后使用paddle inference进行推理，推理不报错，但是没有加速效果，反而是比MKLDNN FP32推理慢3-4倍，这个是什么原因导致的。

**Comment by LiquorPerfect** [comment]
@yghstill 
![image](https://user-images.githubusercontent.com/36955510/207810989-2e1e563b-4b89-41e8-ba15-df310dc6f11e.png)
这里的INT8性能为FP32性能的1.5倍左右，FP32是使用了MKLDNN还是没有使用的速度比呢？
