### ISSUE TITLE
AutoCompression的Distillation教师模型和学生模型可以是不同模型吗

### ISSUE THREAD

**Issue by cold-eye** [PaddlePaddle/PaddleSlim#1607]
我使用微调好的ernie-3.0-xbase-zh，给微调好的ernie-3.0-medium-zh进行蒸馏，报错block名不一致

**Comment by cold-eye** [comment]
2022-12-26 02:19:05,228-INFO: train config.distill_node_pair: ['teacher_linear_75.tmp_1', 'linear_75.tmp_1']
Traceback (most recent call last):
  File "run.py", line 387, in <module>
    main()
  File "run.py", line 377, in main
    ac.compress()
  File "/usr/local/lib/python3.7/dist-packages/paddleslim/auto_compression/compressor.py", line 572, in compress
    train_config)
  File "/usr/local/lib/python3.7/dist-packages/paddleslim/auto_compression/compressor.py", line 695, in single_strategy_compress
    default_distill_node_pair, strategy, config, train_config)
  File "/usr/local/lib/python3.7/dist-packages/paddleslim/auto_compression/compressor.py", line 496, in _prepare_program
    default_distill_node_pair=default_distill_node_pair)
  File "/usr/local/lib/python3.7/dist-packages/paddleslim/auto_compression/create_compressed_program.py", line 318, in build_distill_program
    config.get('alpha') or 1.0)  ### default alpha is 1.0
  File "/usr/local/lib/python3.7/dist-packages/paddleslim/auto_compression/create_compressed_program.py", line 137, in _parse_distill_loss
    tmp_loss += eval(loss)(node[i * 2], node[i * 2 + 1])
  File "/usr/local/lib/python3.7/dist-packages/paddleslim/dist/single_distiller.py", line 198, in soft_label
    teacher_var = program.global_block().var(teacher_var_name)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 3358, in var
    raise ValueError("var %s not in this block" % name)
ValueError: var teacher_linear_75.tmp_1 not in this block

**Comment by cold-eye** [comment]
Global:
  model_dir: ./medium
  model_filename: infer.pdmodel
  params_filename: infer.pdiparams
  batch_size: 10
  max_seq_length: 128
  metric: acc
  
Distillation:
  teacher_model_dir: ./model_25500_export
  teacher_model_filename: infer.pdmodel
  teacher_params_filename: infer.pdiparams
  alpha: 1.0 # 蒸馏loss所占权重
  loss: soft_label
  
  
TrainConfig:
  epochs: 2
  eval_iter: 150
  learning_rate: 1.0e-5
  optimizer_builder:
    optimizer: 
      type: AdamW
    weight_decay: 0.01
  origin_metric: 0.98103

**Comment by ceci3** [comment]
可以不同，不同的话就需要填node结点，可以看下文档：
<img width="1140" alt="image" src="https://user-images.githubusercontent.com/29245900/209511532-d600e599-c364-4998-b453-8b3a307d0795.png">

https://github.com/PaddlePaddle/PaddleSlim/blob/develop/example/auto_compression/hyperparameter_tutorial.md#114-%E7%9F%A5%E8%AF%86%E8%92%B8%E9%A6%8Fknowledge-distillation

**Comment by cold-eye** [comment]
已解决
