### ISSUE TITLE
yolov5量化时报错

### ISSUE THREAD

**Issue by liumingzhu6060** [PaddlePaddle/PaddleSlim#1614]
Traceback (most recent call last):
  File "run.py", line 148, in <module>
    main()
  File "run.py", line 136, in main
    ac.compress()
  File "D:\Software\anaconda3\envs\paddleslim_new\lib\site-packages\paddleslim\auto_compression\compressor.py", line 594, in compress
    train_config)
  File "D:\Software\anaconda3\envs\paddleslim_new\lib\site-packages\paddleslim\auto_compression\compressor.py", line 776, in single_strategy_compress
    train_program_info, test_program_info, strategy, train_config)
  File "D:\Software\anaconda3\envs\paddleslim_new\lib\site-packages\paddleslim\auto_compression\compressor.py", line 819, in _start_train
    test_program_info.fetch_targets)
  File "run.py", line 79, in eval_function
    map_res = coco_metric(anno_file, bboxes_list, bbox_nums_list, image_id_list)
  File "E:\MyProject\pytorch_yolo_series\post_process.py", line 202, in coco_metric
    coco_dt = coco_gt.loadRes(output)
  File "D:\Software\anaconda3\envs\paddleslim_new\lib\site-packages\pycocotools\coco.py", line 328, in loadRes
    if 'caption' in anns[0]:
IndexError: list index out of range
请问这个原因是为什么，我按照coco的格式整理了我的数据集

**Comment by yghstill** [comment]
@liumingzhu6060 这个是由于精度损失过大导致没有检测框输出，所以评估报错。具体需要排查下原因是什么。
- 首先可以确认环境是否正确，直接跑官方demo看能否复现readme结果。
- 其次排查下你的模型、验证集是否有问题。直接用eval.py测试下量化前的模型精度。
- 还可以[只设置image_path进行量化](https://github.com/PaddlePaddle/PaddleSlim/blob/develop/example/auto_compression/pytorch_yolo_series/configs/yolov5s_qat_dis.yaml#L3)，不评估。 然后产出的模型直接预测图片看看符合预期吗？
