### ISSUE TITLE
uie自动压缩示例执行报错

### ISSUE THREAD

**Issue by noobexplore** [PaddlePaddle/PaddleSlim#1620]
版本环境如下：
paddlenlp          2.4.8
paddlepaddle-gpu   2.4.1.post112
paddleslim         2.4.1
报错如下：
```python
Adding quant op with weight:|████████████████████████████████████████| 1510/1510
Adding OutScale op:|███████████████████████████████████████████████████| 818/818
Traceback (most recent call last):
  File "src/compress.py", line 382, in <module>
    main()
  File "src/compress.py", line 375, in main
    ac.compress()
  File "/home/xtl/anaconda3/envs/pp_com/lib/python3.8/site-packages/paddleslim/auto_compression/compressor.py", line 593, in compress
    self.single_strategy_compress(strategy, config, strategy_idx,
  File "/home/xtl/anaconda3/envs/pp_com/lib/python3.8/site-packages/paddleslim/auto_compression/compressor.py", line 775, in single_strategy_compress
    test_program_info = self._start_train(
  File "/home/xtl/anaconda3/envs/pp_com/lib/python3.8/site-packages/paddleslim/auto_compression/compressor.py", line 794, in _start_train
    loss = self._exe.run(train_program_info.program, \
  File "/home/xtl/anaconda3/envs/pp_com/lib/python3.8/site-packages/paddle/fluid/executor.py", line 1463, in run
    six.reraise(*sys.exc_info())
  File "/home/xtl/anaconda3/envs/pp_com/lib/python3.8/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/xtl/anaconda3/envs/pp_com/lib/python3.8/site-packages/paddle/fluid/executor.py", line 1450, in run
    res = self._run_impl(program=program,
  File "/home/xtl/anaconda3/envs/pp_com/lib/python3.8/site-packages/paddle/fluid/executor.py", line 1720, in _run_impl
    return self._run_parallel(program,
  File "/home/xtl/anaconda3/envs/pp_com/lib/python3.8/site-packages/paddle/fluid/executor.py", line 1254, in _run_parallel
    tensors = exe.run(fetch_var_names, return_merged)._move_to_list()
NotImplementedError: In user code:

    File "src/compress.py", line 382, in <module>
      main()
    File "src/compress.py", line 375, in main
      ac.compress()
    File "/home/xtl/anaconda3/envs/pp_com/lib/python3.8/site-packages/paddleslim/auto_compression/compressor.py", line 593, in compress
      self.single_strategy_compress(strategy, config, strategy_idx,
    File "/home/xtl/anaconda3/envs/pp_com/lib/python3.8/site-packages/paddleslim/auto_compression/compressor.py", line 769, in single_strategy_compress
      train_program_info, test_program_info = self._prepare_program(
    File "/home/xtl/anaconda3/envs/pp_com/lib/python3.8/site-packages/paddleslim/auto_compression/compressor.py", line 509, in _prepare_program
      train_program_info, test_program_info = build_distill_program(
    File "/home/xtl/anaconda3/envs/pp_com/lib/python3.8/site-packages/paddleslim/auto_compression/create_compressed_program.py", line 266, in build_distill_program
      train_program, test_program, data_name_map = _load_program_and_merge(
    File "/home/xtl/anaconda3/envs/pp_com/lib/python3.8/site-packages/paddleslim/auto_compression/create_compressed_program.py", line 192, in _load_program_and_merge
      merge(
    File "/home/xtl/anaconda3/envs/pp_com/lib/python3.8/site-packages/paddleslim/dist/single_distiller.py", line 103, in merge
      student_program.global_block().append_op(
    File "/home/xtl/anaconda3/envs/pp_com/lib/python3.8/site-packages/paddle/fluid/framework.py", line 4017, in append_op
      op = Operator(
    File "/home/xtl/anaconda3/envs/pp_com/lib/python3.8/site-packages/paddle/fluid/framework.py", line 2858, in __init__
      for frame in traceback.extract_stack():

    UnimplementedError: emebdding input only support int16, int32 and int64 (at /paddle/paddle/phi/kernels/gpu/embedding_kernel.cu:116)
      [operator < lookup_table_v2 > error]
```
uie模型是通过export导出的inference模型，一直报上述错误不知道如何排查。

**Comment by noobexplore** [comment]
解决了以上问题，发现需要将示例代码中feed_list与压缩模型中feed_list对应好才行。

**Comment by wanghaoshuang** [comment]
多谢反馈

**Comment by xiu86** [comment]
> 解决了以上问题，发现需要将示例代码中feed_list与压缩模型中feed_list对应好才行。

你好，这个问题具体怎么解决，可以详细说下吗？我也遇到这个错误了
