### ISSUE TITLE
PPYOLOE+  auto_compression 训练时eval精度0.92 预测验证时eval只有0.82 ？

### ISSUE THREAD

**Issue by yuanjim** [PaddlePaddle/PaddleSlim#1627]
在BML上跑 PPYOLOE+ 的auto_compression实验：
```
Global:
  reader_config: configs/ppyoloe_plus_640_reader.yml
  arch: PPYOLOE
  include_nms: False
  Evaluation: True
  model_dir: output_inference/ppyoloe_plus_crn_s_80e_coco_1500_noNMS
  model_filename: model.pdmodel
  params_filename: model.pdiparams

Distillation:
  alpha: 1.0
  loss: soft_label

QuantAware:
  onnx_format: true
  use_pact: true
  activation_quantize_type: 'moving_average_abs_max'
  quantize_op_types:
  - conv2d
  - depthwise_conv2d

TrainConfig:
  train_iter: 5000
  eval_iter: 1000
  learning_rate:  
    type: CosineAnnealingDecay
    learning_rate: 0.00003
    T_max: 6000
  optimizer_builder:
    optimizer: 
      type: SGD
    weight_decay: 4.0e-05
```
```
! export CUDA_VISIBLE_DEVICES=0
! cd work/PaddleDetection && python run.py --config_path=./configs/ppyoloe_plus_s_qat_dis_1500.yaml --save_dir='./output_slim/'
```
```
DONE (t=1.60s).
Accumulating evaluation results...
DONE (t=0.63s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.710
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.927
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.799
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.494
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.687
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.788
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.486
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.764
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.778
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.582
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.755
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.849
2023-01-10 13:55:44,387-INFO: epoch: 13 metric of compressed model is: 0.710378, best metric of compressed model is 0.716277
2023-01-10 13:55:46,655-INFO: Total iter: 4009, epoch: 13, batch: 110, loss: [13.291732]soft_label: [13.291732] 
2023-01-10 13:55:48,821-INFO: Total iter: 4019, epoch: 13, batch: 120, loss: [13.326349]soft_label: [13.326349] 
2023-01-10 13:55:51,086-INFO: Total iter: 4029, epoch: 13, batch: 130, loss: [13.304006]soft_label: [13.304006] 
```

这里边训练边eval，精度还是0.92。

后面预测时：
yaml文件中model_dir:改为了output_slim。执行命令：
```# TensorRT预测：
# 环境配置：如果使用 TesorRT 预测引擎，需安装 WITH_TRT=ON 的Paddle，下载地址：Python预测库
! cd work/PaddleDetection && python eval.py \
      --config_path=configs/ppyoloe_plus_s_qat_dis_1500.yaml
```
```
Warning: import ppdet from source directory without installing, run 'python setup.py install' to install ppdet firstly
[01-11 21:30:50 MainThread @logger.py:242] Argv: eval.py --config_path=configs/ppyoloe_plus_s_qat_dis_1500.yaml
[01-11 21:30:50 MainThread @utils.py:79] WRN paddlepaddle version: 2.4.0. The dynamic graph version of PARL is under development, not fully tested and supported
WARNING:root:cannot import name 'layers' from 'parl' (/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/parl/__init__.py)
-----------  Running Arguments -----------
 Distillation:
	 alpha: 1.0
	 loss: soft_label
 Global:
	 Evaluation: True
	 arch: PPYOLOE
	 include_nms: False
	 model_dir: output_slim
	 model_filename: model.pdmodel
	 params_filename: model.pdiparams
	 reader_config: configs/ppyoloe_plus_640_reader.yml
 QuantAware:
	 activation_quantize_type: moving_average_abs_max
	 onnx_format: True
	 quantize_op_types: ['conv2d', 'depthwise_conv2d']
	 use_pact: True
 TrainConfig:
	 eval_iter: 1000
	 learning_rate:
		 T_max: 6000
		 learning_rate: 3e-05
		 type: CosineAnnealingDecay
	 optimizer_builder:
		 optimizer:
			 type: SGD
		 weight_decay: 4e-05
	 train_iter: 5000
------------------------------------------
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
W0111 21:30:51.066249  3547 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 11.2, Runtime API Version: 11.2
W0111 21:30:51.070571  3547 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
Wed Jan 11 21:30:52-WARNING: The old way to load inference model is deprecated. model path: /home/aistudio/work/PaddleDetection/output_slim/model.pdmodel, params path: /home/aistudio/work/PaddleDetection/output_slim/model.pdiparams
Loaded model from: output_slim
[01/11 21:30:57] ppdet.data.transform.operators WARNING: The actual image height: 663 is not equal to the height: 0.0 in annotation, and update sample['h'] by actual image height.
[01/11 21:30:57] ppdet.data.transform.operators WARNING: The actual image width: 949 is not equal to the width: 0.0 in annotation, and update sample['w'] by actual image width.
Eval iter: 0
[01/11 21:31:10] ppdet.data.transform.operators WARNING: The actual image height: 663 is not equal to the height: 0.0 in annotation, and update sample['h'] by actual image height.
[01/11 21:31:10] ppdet.data.transform.operators WARNING: The actual image width: 949 is not equal to the width: 0.0 in annotation, and update sample['w'] by actual image width.
[01/11 21:31:16] ppdet.metrics.metrics INFO: The bbox result is saved to bbox.json.
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
[01/11 21:31:16] ppdet.metrics.coco_utils INFO: Start evaluate...
Loading and preparing results...
DONE (t=0.60s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=1.90s).
Accumulating evaluation results...
DONE (t=0.60s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.529
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.829
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.558
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.259
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.443
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.647
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.419
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.590
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.617
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.494
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.509
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.708
```
这时精度就下降到0.82了。
尝试按照[https://gitee.com/paddlepaddle/PaddleSlim/tree/develop/example/auto_compression/detection](https://gitee.com/paddlepaddle/PaddleSlim/tree/develop/example/auto_compression/detection)，使用paddle_inference_eval.py来eval时，出错：
```
! cd work/PaddleDetection && python paddle_inference_eval.py \
      --model_path=output_slim \
      --reader_config=configs/ppyoloe_plus_640_reader.yml
```
```
--- Running analysis [ir_graph_to_program_pass]
I0111 21:15:42.338825  1254 analysis_predictor.cc:1314] ======= optimize end =======
I0111 21:15:42.351177  1254 naive_executor.cc:110] ---  skip [feed], feed -> image
I0111 21:15:42.358578  1254 naive_executor.cc:110] ---  skip [save_infer_model/scale_0.tmp_0], fetch -> fetch
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
output_names= ['save_infer_model/scale_0.tmp_0']
output_names[0]= save_infer_model/scale_0.tmp_0
Traceback (most recent call last):
  File "paddle_inference_eval.py", line 501, in <module>
    main()
  File "paddle_inference_eval.py", line 485, in main
    eval(predictor, val_loader, metric, rerun_flag=rerun_flag)
  File "paddle_inference_eval.py", line 405, in eval
    boxes_num = predictor.get_output_handle(output_names[1])
IndexError: list index out of range
```
请各位大佬答疑解惑，感谢！

**Comment by zzjjay** [comment]
看你的训练配置模型是不包含nms的，那在使用paddle_inference_eval.py进行eval时也需要设置include_nms=False；
执行指令添加个 --include_nms=False 再试试

**Comment by yuanjim** [comment]
我已收到您的邮件。谢谢！

**Comment by yuanjim** [comment]
> 看你的训练配置模型是不包含nms的，那在使用paddle_inference_eval.py进行eval时也需要设置include_nms=False； 执行指令添加个 --include_nms=False 再试试

感谢解答。第一个问题预测时比训练时，精度下降10个点，还没有答案。第二个问题在eval函数中强行设置了include_nms=False同时，修改为：
```
if FLAGS.include_nms:
        boxes_num = predictor.get_output_handle(output_names[1])
```
新的报错：![image](https://user-images.githubusercontent.com/46877936/212219466-9034bff9-2824-4dc2-86ea-17a93aca0677.png)

**Comment by yghstill** [comment]
@yuanjim 
1. 由于量化后导出模型是全量化模型，所以直接用eval脚本测试精度会下降，这个要以paddle Inference真实预测库测试精度为准，这个问题近期做了兼容，或者需要更新最新develop PaddlePaddle和PaddleSlim来解决此问题。
2. 需要确认你的PPYOLOE模型是否含nms，https://github.com/PaddlePaddle/PaddleSlim/blob/develop/example/auto_compression/detection/paddle_inference_eval.py 的脚本默认是包含nms测试精度。如果include_nms=Ture，那么就不会走到单独后处理代码里https://github.com/PaddlePaddle/PaddleSlim/blob/develop/example/auto_compression/detection/paddle_inference_eval.py#L380 ，请再确认下这里。

**Comment by yuanjim** [comment]
> @yuanjim
> 
> 1. 由于量化后导出模型是全量化模型，所以直接用eval脚本测试精度会下降，这个要以paddle Inference真实预测库测试精度为准，这个问题近期做了兼容，或者需要更新最新develop PaddlePaddle和PaddleSlim来解决此问题。
> 2. 需要确认你的PPYOLOE模型是否含nms，https://github.com/PaddlePaddle/PaddleSlim/blob/develop/example/auto_compression/detection/paddle_inference_eval.py 的脚本默认是包含nms测试精度。如果include_nms=Ture，那么就不会走到单独后处理代码里https://github.com/PaddlePaddle/PaddleSlim/blob/develop/example/auto_compression/detection/paddle_inference_eval.py#L380 ，请再确认下这里。

感谢帮助。导出的模型是不包含nms的。这里需要提到一点，我之前设置了paddle_inference_eval.py中--include_nms的default=False，且执行命令时也添加了参数--include_nms=False后，在eval()函数中print(FLAGS.include_nms) 还是True。

**Comment by yghstill** [comment]
那应该是python传入参数的问题，试下直接在代码main函数中设置FLAGS.include_nms = False再测试下。

**Comment by yuanjim** [comment]
> 那应该是python传入参数的问题，试下直接在代码main函数中设置FLAGS.include_nms = False再测试下。

在main函数中加了FLAGS.include_nms = False，报错如下：
```
[notice] A new release of pip available: 22.1.2 -> 22.3.1
[notice] To update, run: pip install --upgrade pip
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting GPUtil
  Using cached GPUtil-1.4.0-py3-none-any.whl
Installing collected packages: GPUtil
Successfully installed GPUtil-1.4.0

[notice] A new release of pip available: 22.1.2 -> 22.3.1
[notice] To update, run: pip install --upgrade pip
Traceback (most recent call last):
  File "paddle_inference_eval.py", line 505, in <module>
    main()
  File "paddle_inference_eval.py", line 487, in main
    eval(predictor, val_loader, metric, rerun_flag=rerun_flag)
  File "paddle_inference_eval.py", line 431, in eval
    res = postprocess(np_boxes, data_all['scale_factor'])
  File "/home/aistudio/work/PaddleDetection/post_process.py", line 156, in __call__
    scale_factor)
  File "/home/aistudio/work/PaddleDetection/post_process.py", line 150, in _non_max_suppression
    out_boxes_list = np.concatenate(out_boxes_list, axis=0)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 6 and the array at index 3 has size 4
```

**Comment by yghstill** [comment]
@yuanjim 
eval.py测试没有问题？可以继续debug下，和eval.py比对下，打印进入postprocess前的np_boxes维度是否一致

**Comment by yuanjim** [comment]
> @yuanjim eval.py测试没有问题？可以继续debug下，和eval.py比对下，打印进入postprocess前的np_boxes维度是否一致


@yghstill 


测试了下，eval.py没有问题。
eval.py
![image](https://user-images.githubusercontent.com/46877936/212235359-d705ae15-004e-4850-96fb-96ca02d7b5e4.png)
```
np.array(outs[0]).shape= (4, 8400, 12)
```
paddle_inference_eval.py
![image](https://user-images.githubusercontent.com/46877936/212235603-315fc817-8198-4317-9ff1-8f0b3239c238.png)
```
np_boxes.shape= (4, 8400, 12)
```
进入postprocess前的np_boxes维度是一致的。
不过paddle_inference_eval.py还是报错：
```
[notice] A new release of pip available: 22.1.2 -> 22.3.1
[notice] To update, run: pip install --upgrade pip
np_boxes.shape= (4, 8400, 12)
Traceback (most recent call last):
  File "paddle_inference_eval.py", line 506, in <module>
    main()
  File "paddle_inference_eval.py", line 488, in main
    eval(predictor, val_loader, metric, rerun_flag=rerun_flag)
  File "paddle_inference_eval.py", line 432, in eval
    res = postprocess(np_boxes, data_all['scale_factor'])
  File "/home/aistudio/work/PaddleDetection/post_process.py", line 156, in __call__
    scale_factor)
  File "/home/aistudio/work/PaddleDetection/post_process.py", line 150, in _non_max_suppression
    out_boxes_list = np.concatenate(out_boxes_list, axis=0)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 6 and the array at index 3 has size 4
```

**Comment by yuanjim** [comment]
@yghstill 

paddle_inference_eval.py报错被顺利排查掉了。

通过将预测时的batchsize设为1，现在用eval.py，eval出的结果0.88，如下：
```
Accumulating evaluation results...
DONE (t=0.57s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.563
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.888
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.584
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.228
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.510
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.684
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.433
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.623
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.651
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.431
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.587
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.744
```
而用paddle_inference_eval.py，eval出的结果反而更低0.80，如下：
```
Accumulating evaluation results...
DONE (t=0.07s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.526
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.802
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.563
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.074
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.473
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.678
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.420
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.572
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.574
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.109
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.509
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.722
[Benchmark]Avg cpu_mem:2647.450357859529 MB, avg gpu_mem: 1140.0 MB
[Benchmark]Inference time(ms): min=23.58, max=1058.6, avg=30.3
[Benchmark] COCO mAP: 0.5259970849363985
```
两种预测结果都比训练时的0.92要低很多，大佬知道原因吗？
