### ISSUE TITLE
静态后量化matmul_v2 op出错

### ISSUE THREAD

**Issue by Kevin-XiongC** [PaddlePaddle/PaddleSlim#1683]
静态后量化 paddle官方picodet模型出错，因其中含有matmul_v2 op
``` python
import paddle
import paddleslim as slim
import numpy as np
place = paddle.CPUPlace()
exe = paddle.static.Executor(place)
paddle.enable_static()
def calibrate_data():
    while True:
        image = np.random.uniform(0, 1, size=(3, 320, 320)).astype("float32")
        scale_factor = np.random.uniform(0, 1, size=(1,2)).astype("float32")
        yield image,scale_factor

slim.quant.quant_post_static(
        executor=exe,
        model_dir='/home/picodet_s_320_coco_lcnet',
        quantize_model_path='/home/picodet_s_320_coco_lcnet/quant_post_static_model',
        sample_generator=calibrate_data,
        quantizable_op_type=[
                          "conv2d", "depthwise_conv2d", "mul", "matmul", "matmul_v2"],
        model_filename='model.pdmodel',
        params_filename='model.pdiparams',
        batch_nums=1        )
```

``` bash
Traceback (most recent call last):
  File "/Users/Desktop/baidu/aipe-edge/PPNC-ToolChain/tmp/tmp.py", line 17, in <module>
    slim.quant.quant_post_static(
  File "/Users/.pyenv/versions/3.8.15/lib/python3.8/site-packages/paddleslim/quant/quanter.py", line 627, in quant_post_static
    post_training_quantization.quantize()
  File "/Users/.pyenv/versions/3.8.15/lib/python3.8/site-packages/paddle/fluid/contrib/slim/quantization/post_training_quantization.py", line 431, in quantize
    self._calculate_kl_hist_threshold()
  File "/Users/.pyenv/versions/3.8.15/lib/python3.8/site-packages/paddle/fluid/contrib/slim/quantization/post_training_quantization.py", line 948, in _calculate_kl_hist_threshold
    for i in range(weight_data.shape[1]):
IndexError: tuple index out of range
```
将matmul_v2从quantizable_op_type去掉后，即可正常产出量化模型

## 环境
paddle 2.4.2
slim 2.4.1

**Comment by zzjjay** [comment]
picodet_s_320_coco_lcnet中的matmul_v2权重为一维矩阵，如图所示，暂不支持。目前仅支持量化权重为二维矩阵的矩阵乘。
<img width="219" alt="image" src="https://user-images.githubusercontent.com/41366441/227192259-4be7b230-736c-4a45-a44e-c306a76f97ca.png">
