### ISSUE TITLE
在使用官方文档中的教程的对ppyoloe进行auto_compress的时候报错AttributeError: 'SchemaDict' object has no attribute 'check_or_download_dataset'

### ISSUE THREAD

**Issue by NoConfusionj** [PaddlePaddle/PaddleSlim#1720]

**Comment by NoConfusionj** [comment]
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/__init__.py:107: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import MutableMapping
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/rcsetup.py:20: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Iterable, Mapping
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/colors.py:53: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Sized
[04-10 23:10:39 MainThread @logger.py:242] Argv: /home/aistudio/run.py --config_path=/home/aistudio/slim.yml --save_dir=/home/aistudio/PaddleDetection-2.5.0/output
[04-10 23:10:39 MainThread @utils.py:79] WRN paddlepaddle version: 2.4.1. The dynamic graph version of PARL is under development, not fully tested and supported
WARNING:root:cannot import name 'layers' from 'parl' (/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/parl/__init__.py)
-----------  Running Arguments -----------
 Distillation:
	 alpha: 1.0
	 loss: soft_label
 Global:
	 Evaluation: True
	 arch: PPYOLOE
	 include_nms: False
	 model_dir: /home/aistudio/model/ppyoloe_crn_l_300e_coco
	 model_filename: model.pdmodel
	 params_filename: model.pdiparams
	 reader_config: /home/aistudio/PaddleDetection-2.5.0/configs/ppyoloe/_base_/ppyoloe_reader.yml
 QuantAware:
	 activation_quantize_type: moving_average_abs_max
	 onnx_format: True
	 quantize_op_types: ['conv2d', 'depthwise_conv2d']
	 use_pact: True
 TrainConfig:
	 eval_iter: 1000
	 learning_rate:
		 T_max: 6000
		 learning_rate: 3e-05
		 type: CosineAnnealingDecay
	 optimizer_builder:
		 optimizer:
			 type: SGD
		 weight_decay: 4e-05
	 train_iter: 5000
------------------------------------------
Traceback (most recent call last):
  File "/home/aistudio/run.py", line 198, in <module>
    main()
  File "/home/aistudio/run.py", line 141, in main
    return_list=True)
  File "/home/aistudio/.data/webide/pip/lib/python3.7/site-packages/ppdet/data/reader.py", line 167, in __call__
    self.dataset.check_or_download_dataset()
AttributeError: 'SchemaDict' object has no attribute 'check_or_download_dataset'

**Comment by GUANGHANXUE** [comment]
我也遇到了这个问题

**Comment by XGZhang11** [comment]
应该是数据集配置有问题
