### ISSUE TITLE
基于修改过的yolov7-tiny，使用PaddleSlim/example/auto_compression/pytorch_yolo_series/自动压缩示例教程

### ISSUE THREAD

**Issue by DSP3460** [PaddlePaddle/PaddleSlim#1724]
在进行至README.md的导出至ONNX使用TensorRT部署阶段时，报错
```
Traceback (most recent call last):
  File "G:\PythonDev\YOLOProject\PaddleSlimAC\TensorRT\trt_eval.py", line 324, in <module>
    main()
  File "G:\PythonDev\YOLOProject\PaddleSlimAC\TensorRT\trt_eval.py", line 303, in main
    infer()
  File "G:\PythonDev\YOLOProject\PaddleSlimAC\TensorRT\trt_eval.py", line 279, in infer
    outs = np.array(outs).reshape(1, -1, 85)
ValueError: could not broadcast input array from shape (3,80,80,16) into shape (1,3)
```
截至此错误之前，项目已生成
![QQ截图20230413171818](https://user-images.githubusercontent.com/26647741/231714964-d9940a4d-2480-4869-8206-1fc3b76ebc2d.png)
请问报错的原因是什么呢？需要修改什么参数吗?还是网络自身存在问题？
求解答，谢谢!

**Comment by ceci3** [comment]
报错那一行的shape看起来不太对
