### ISSUE TITLE
量化分析工具报错

### ISSUE THREAD

**Issue by truthsun22** [PaddlePaddle/PaddleSlim#1756]
我安装的paddlepaddle是2.4.2版本，但我运行量化分析工具\example\post_training_quantization\detection\analysis.py报错
我直接打开python ,执行import paddleslim也是报同样的错
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddleslim
/home/deepiot/anaconda3/envs/paddle2.4/lib/python3.8/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
2023-05-31 17:36:22,721-WARNING: No module named 'paddle.static.quantization'
2023-05-31 17:36:22,721-WARNING: If you want to use training-aware and post-training quantization, please use Paddle >= 2.3.0 or develop version
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/deepiot/ai/PaddleSlim/paddleslim/__init__.py", line 20, in <module>
    from paddleslim import quant
  File "/home/deepiot/ai/PaddleSlim/paddleslim/quant/__init__.py", line 42, in <module>
    from . import nn
  File "/home/deepiot/ai/PaddleSlim/paddleslim/quant/nn/__init__.py", line 15, in <module>
    from .conv_bn import QuantedConv2DBatchNorm, Conv2DBatchNormWrapper
  File "/home/deepiot/ai/PaddleSlim/paddleslim/quant/nn/conv_bn.py", line 21, in <module>
    from paddle.nn.quant.format import ConvertibleQuantedLayer
ModuleNotFoundError: No module named 'paddle.nn.quant.format'

**Comment by ceci3** [comment]
paddle版本和paddleslim版本对不上，可以升级paddlepaddle到2.6
