### ISSUE TITLE
剪枝时axis对不上，正常卷积可以对上，深度可分离卷积就对不上了

### ISSUE THREAD

**Issue by shangshanruowo** [PaddlePaddle/PaddleSlim#1761]
使用pruner = L1NormFilterPruner(trainer.model, input_spec)时，对正常卷积的模型可以运行，但模型里面有深度可分离卷积的就会报错误，2023-06-10 16:31:29,724-WARNING: Leaves ['eager_tmp_5', 'batch_norm_75.tmp_0', 'batch_norm_75.tmp_1', 'batch_norm_76.tmp_0', 'batch_norm_76.tmp_1', 'batch_norm_77.tmp_0', 'batch_norm_77.tmp_1', 'batch_norm_78.tmp_0', 'batch_norm_78.tmp_1', 'batch_norm_79.tmp_0', 'batch_norm_79.tmp_1', 'batch_norm_80.tmp_0', 'batch_norm_80.tmp_1', 'batch_norm_81.tmp_0', 'batch_norm_81.tmp_1', 'batch_norm_82.tmp_0', 'batch_norm_82.tmp_1', 'batch_norm_83.tmp_0', 'batch_norm_83.tmp_1', 'batch_norm_84.tmp_0', 'batch_norm_84.tmp_1', 'batch_norm_85.tmp_0', 'batch_norm_85.tmp_1', 'batch_norm_86.tmp_0', 'batch_norm_86.tmp_1', 'batch_norm_87.tmp_0', 'batch_norm_87.tmp_1', 'batch_norm_88.tmp_0', 'batch_norm_88.tmp_1', 'batch_norm_89.tmp_0', 'batch_norm_89.tmp_1', 'batch_norm_90.tmp_0', 'batch_norm_90.tmp_1', 'batch_norm_91.tmp_0', 'batch_norm_91.tmp_1', 'reshape2_46.tmp_1', 'transpose_40.tmp_1', 'reshape2_47.tmp_1', 'transpose_41.tmp_1', 'reshape2_48.tmp_1', 'layer_norm_21.tmp_0', 'layer_norm_21.tmp_1', 'reshape2_49.tmp_1', 'transpose_42.tmp_1', 'transpose_43.tmp_1', 'transpose_44.tmp_1', 'reshape2_50.tmp_1', 'dropout_18.tmp_1', 'layer_norm_22.tmp_0', 'layer_norm_22.tmp_1', 'dropout_19.tmp_1', 'layer_norm_23.tmp_0', 'layer_norm_23.tmp_1', 'reshape2_51.tmp_1', 'transpose_45.tmp_1', 'transpose_46.tmp_1', 'transpose_47.tmp_1', 'reshape2_52.tmp_1', 'dropout_20.tmp_1', 'layer_norm_24.tmp_0', 'layer_norm_24.tmp_1', 'dropout_21.tmp_1', 'layer_norm_25.tmp_0', 'layer_norm_25.tmp_1', 'reshape2_53.tmp_1', 'transpose_48.tmp_1', 'reshape2_54.tmp_1', 'transpose_49.tmp_1', 'reshape2_55.tmp_1', 'batch_norm_92.tmp_0', 'batch_norm_92.tmp_1', 'batch_norm_93.tmp_0', 'batch_norm_93.tmp_1', 'batch_norm_94.tmp_0', 'batch_norm_94.tmp_1', 'batch_norm_95.tmp_0', 'batch_norm_95.tmp_1', 'batch_norm_96.tmp_0', 'batch_norm_96.tmp_1', 'batch_norm_97.tmp_0', 'batch_norm_97.tmp_1', 'reshape2_56.tmp_1', 'transpose_50.tmp_1', 'reshape2_57.tmp_1', 'transpose_51.tmp_1', 'reshape2_58.tmp_1', 'layer_norm_26.tmp_0', 'layer_norm_26.tmp_1', 'reshape2_59.tmp_1', 'transpose_52.tmp_1', 'transpose_53.tmp_1', 'transpose_54.tmp_1', 'reshape2_60.tmp_1', 'dropout_22.tmp_1', 'layer_norm_27.tmp_0', 'layer_norm_27.tmp_1', 'dropout_23.tmp_1', 'layer_norm_28.tmp_0', 'layer_norm_28.tmp_1', 'reshape2_61.tmp_1', 'transpose_55.tmp_1', 'transpose_56.tmp_1', 'transpose_57.tmp_1', 'reshape2_62.tmp_1', 'dropout_24.tmp_1', 'layer_norm_29.tmp_0', 'layer_norm_29.tmp_1', 'dropout_25.tmp_1', 'layer_norm_30.tmp_0', 'layer_norm_30.tmp_1', 'reshape2_63.tmp_1', 'transpose_58.tmp_1', 'transpose_59.tmp_1', 'transpose_60.tmp_1', 'reshape2_64.tmp_1', 'dropout_26.tmp_1', 'layer_norm_31.tmp_0', 'layer_norm_31.tmp_1', 'dropout_27.tmp_1', 'layer_norm_32.tmp_0', 'layer_norm_32.tmp_1', 'reshape2_65.tmp_1', 'transpose_61.tmp_1', 'transpose_62.tmp_1', 'transpose_63.tmp_1', 'reshape2_66.tmp_1', 'dropout_28.tmp_1', 'layer_norm_33.tmp_0', 'layer_norm_33.tmp_1', 'dropout_29.tmp_1', 'layer_norm_34.tmp_0', 'layer_norm_34.tmp_1', 'reshape2_67.tmp_1', 'transpose_64.tmp_1', 'reshape2_68.tmp_1', 'transpose_65.tmp_1', 'reshape2_69.tmp_1', 'batch_norm_98.tmp_0', 'batch_norm_98.tmp_1', 'batch_norm_99.tmp_0', 'batch_norm_99.tmp_1', 'batch_norm_100.tmp_0', 'batch_norm_100.tmp_1', 'batch_norm_101.tmp_0', 'batch_norm_101.tmp_1', 'batch_norm_102.tmp_0', 'batch_norm_102.tmp_1', 'batch_norm_103.tmp_0', 'batch_norm_103.tmp_1', 'reshape2_70.tmp_1', 'transpose_66.tmp_1', 'reshape2_71.tmp_1', 'transpose_67.tmp_1', 'reshape2_72.tmp_1', 'layer_norm_35.tmp_0', 'layer_norm_35.tmp_1', 'reshape2_73.tmp_1', 'transpose_68.tmp_1', 'transpose_69.tmp_1', 'transpose_70.tmp_1', 'reshape2_74.tmp_1', 'dropout_30.tmp_1', 'layer_norm_36.tmp_0', 'layer_norm_36.tmp_1', 'dropout_31.tmp_1', 'layer_norm_37.tmp_0', 'layer_norm_37.tmp_1', 'reshape2_75.tmp_1', 'transpose_71.tmp_1', 'transpose_72.tmp_1', 'transpose_73.tmp_1', 'reshape2_76.tmp_1', 'dropout_32.tmp_1', 'layer_norm_38.tmp_0', 'layer_norm_38.tmp_1', 'dropout_33.tmp_1', 'layer_norm_39.tmp_0', 'layer_norm_39.tmp_1', 'reshape2_77.tmp_1', 'transpose_74.tmp_1', 'transpose_75.tmp_1', 'transpose_76.tmp_1', 'reshape2_78.tmp_1', 'dropout_34.tmp_1', 'layer_norm_40.tmp_0', 'layer_norm_40.tmp_1', 'dropout_35.tmp_1', 'layer_norm_41.tmp_0', 'layer_norm_41.tmp_1', 'reshape2_79.tmp_1', 'transpose_77.tmp_1', 'reshape2_80.tmp_1', 'transpose_78.tmp_1', 'reshape2_81.tmp_1', 'batch_norm_104.tmp_0', 'batch_norm_104.tmp_1', 'batch_norm_105.tmp_0', 'batch_norm_105.tmp_1', 'batch_norm_106.tmp_0', 'batch_norm_106.tmp_1', 'batch_norm_107.tmp_0', 'batch_norm_107.tmp_1', 'batch_norm_108.tmp_0', 'batch_norm_108.tmp_1', 'batch_norm_109.tmp_0', 'batch_norm_109.tmp_1', 'batch_norm_110.tmp_0', 'batch_norm_110.tmp_1', 'pool2d_6.tmp_1', 'pool2d_7.tmp_1', 'pool2d_8.tmp_1', 'batch_norm_111.tmp_0', 'batch_norm_111.tmp_1', 'batch_norm_112.tmp_0', 'batch_norm_112.tmp_1', 'batch_norm_113.tmp_0', 'batch_norm_113.tmp_1', 'batch_norm_114.tmp_0', 'batch_norm_114.tmp_1', 'batch_norm_115.tmp_0', 'batch_norm_115.tmp_1', 'batch_norm_116.tmp_0', 'batch_norm_116.tmp_1', 'batch_norm_117.tmp_0', 'batch_norm_117.tmp_1', 'batch_norm_118.tmp_0', 'batch_norm_118.tmp_1', 'batch_norm_119.tmp_0', 'batch_norm_119.tmp_1', 'batch_norm_120.tmp_0', 'batch_norm_120.tmp_1', 'batch_norm_121.tmp_0', 'batch_norm_121.tmp_1', 'batch_norm_122.tmp_0', 'batch_norm_122.tmp_1', 'batch_norm_123.tmp_0', 'batch_norm_123.tmp_1', 'batch_norm_124.tmp_0', 'batch_norm_124.tmp_1', 'batch_norm_125.tmp_0', 'batch_norm_125.tmp_1', 'batch_norm_126.tmp_0', 'batch_norm_126.tmp_1', 'batch_norm_127.tmp_0', 'batch_norm_127.tmp_1', 'batch_norm_128.tmp_0', 'batch_norm_128.tmp_1', 'batch_norm_129.tmp_0', 'batch_norm_129.tmp_1', 'batch_norm_130.tmp_0', 'batch_norm_130.tmp_1', 'batch_norm_131.tmp_0', 'batch_norm_131.tmp_1', 'batch_norm_132.tmp_0', 'batch_norm_132.tmp_1', 'batch_norm_133.tmp_0', 'batch_norm_133.tmp_1', 'batch_norm_134.tmp_0', 'batch_norm_134.tmp_1', 'batch_norm_135.tmp_0', 'batch_norm_135.tmp_1', 'batch_norm_136.tmp_0', 'batch_norm_136.tmp_1', 'batch_norm_137.tmp_0', 'batch_norm_137.tmp_1', 'batch_norm_138.tmp_0', 'batch_norm_138.tmp_1', 'batch_norm_139.tmp_0', 'batch_norm_139.tmp_1', 'batch_norm_140.tmp_0', 'batch_norm_140.tmp_1', 'shape_6.tmp_0_slice_0', 'shape_6.tmp_0_slice_1', 'reshape2_82.tmp_1', 'tmp_166', 'shape_7.tmp_0_slice_0', 'shape_7.tmp_0_slice_1', 'reshape2_83.tmp_1', 'tmp_174', 'shape_8.tmp_0_slice_0', 'shape_8.tmp_0_slice_1', 'reshape2_84.tmp_1', 'tmp_182', 'concat_37.tmp_0', 'shape_9.tmp_0_slice_1', 'batch_norm_141.tmp_0', 'batch_norm_141.tmp_1', 'batch_norm_142.tmp_0', 'batch_norm_142.tmp_1', 'batch_norm_143.tmp_0', 'batch_norm_143.tmp_1', 'reshape2_85.tmp_1', 'reshape2_86.tmp_1', 'shape_10.tmp_0_slice_1', 'batch_norm_144.tmp_0', 'batch_norm_144.tmp_1', 'batch_norm_145.tmp_0', 'batch_norm_145.tmp_1', 'batch_norm_146.tmp_0', 'batch_norm_146.tmp_1', 'reshape2_87.tmp_1', 'reshape2_88.tmp_1', 'shape_11.tmp_0_slice_1', 'batch_norm_147.tmp_0', 'batch_norm_147.tmp_1', 'batch_norm_148.tmp_0', 'batch_norm_148.tmp_1', 'batch_norm_149.tmp_0', 'batch_norm_149.tmp_1', 'reshape2_89.tmp_1', 'reshape2_90.tmp_1', 'transpose_79.tmp_1', 'reshape2_91.tmp_1', 'multiclass_nms3_1.tmp_0', 'multiclass_nms3_1.tmp_1', 'multiclass_nms3_1.tmp_2'] will be skipped when parsing graph.
2023-06-10 16:31:32,172-WARNING: Couldn't find relative variables of conv2d_34.w_0 because conv2d_34.w_0 is not in target program or model. Please make sure conv2d_34.w_0 is in your program if you are using static API of PaddlePaddle. And make sure your model in correct mode and contains conv2d_34.w_0 if you are using dynamic API of PaddlePaddle.
Traceback (most recent call last):
  File "D:/DeepLearning/DeepLearning_project/PaddleDetection-release/test01.py", line 110, in <module>
    pruner = L1NormFilterPruner(trainer.model, input_spec)
  File "D:\DeepLearning\Anaconda3\envs\PaddleDetection\lib\site-packages\paddleslim\dygraph\prune\l1norm_pruner.py", line 18, in __init__
    model, inputs, sen_file=sen_file, opt=opt, skip_leaves=skip_leaves)
  File "D:\DeepLearning\Anaconda3\envs\PaddleDetection\lib\site-packages\paddleslim\dygraph\prune\filter_pruner.py", line 68, in __init__
    model, inputs, skip_leaves=self.skip_leaves)
  File "D:\DeepLearning\Anaconda3\envs\PaddleDetection\lib\site-packages\paddleslim\dygraph\prune\var_group.py", line 33, in __init__
    params, graph, skip_leaves=skip_leaves)
  File "D:\DeepLearning\Anaconda3\envs\PaddleDetection\lib\site-packages\paddleslim\prune\collections.py", line 220, in create_pruning_collections
    worker.prune(param, pruned_axis=0, pruned_idx=[])
  File "D:\DeepLearning\Anaconda3\envs\PaddleDetection\lib\site-packages\paddleslim\prune\prune_worker.py", line 94, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "D:\DeepLearning\Anaconda3\envs\PaddleDetection\lib\site-packages\paddleslim\prune\prune_worker.py", line 208, in _prune
    self._visit_and_search(output_var, channel_axis, pruned_idx)
  File "D:\DeepLearning\Anaconda3\envs\PaddleDetection\lib\site-packages\paddleslim\prune\prune_worker.py", line 117, in _visit_and_search
    self._prune_op(op, var, axis, transforms)
  File "D:\DeepLearning\Anaconda3\envs\PaddleDetection\lib\site-packages\paddleslim\prune\prune_worker.py", line 147, in _prune_op
    worker.prune(var, pruned_axis, pruned_idx)
  File "D:\DeepLearning\Anaconda3\envs\PaddleDetection\lib\site-packages\paddleslim\prune\prune_worker.py", line 94, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "D:\DeepLearning\Anaconda3\envs\PaddleDetection\lib\site-packages\paddleslim\prune\prune_worker.py", line 286, in _prune
    self._visit_and_search(out_var, pruned_axis, pruned_idx)
  File "D:\DeepLearning\Anaconda3\envs\PaddleDetection\lib\site-packages\paddleslim\prune\prune_worker.py", line 117, in _visit_and_search
    self._prune_op(op, var, axis, transforms)
  File "D:\DeepLearning\Anaconda3\envs\PaddleDetection\lib\site-packages\paddleslim\prune\prune_worker.py", line 147, in _prune_op
    worker.prune(var, pruned_axis, pruned_idx)
  File "D:\DeepLearning\Anaconda3\envs\PaddleDetection\lib\site-packages\paddleslim\prune\prune_worker.py", line 94, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "D:\DeepLearning\Anaconda3\envs\PaddleDetection\lib\site-packages\paddleslim\prune\prune_worker.py", line 336, in _prune
    self._visit_and_search(in_var, y_pruned_axis, pruned_idx)
  File "D:\DeepLearning\Anaconda3\envs\PaddleDetection\lib\site-packages\paddleslim\prune\prune_worker.py", line 114, in _visit_and_search
    self._prune_op(op, var, axis, transforms)
  File "D:\DeepLearning\Anaconda3\envs\PaddleDetection\lib\site-packages\paddleslim\prune\prune_worker.py", line 147, in _prune_op
    worker.prune(var, pruned_axis, pruned_idx)
  File "D:\DeepLearning\Anaconda3\envs\PaddleDetection\lib\site-packages\paddleslim\prune\prune_worker.py", line 94, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "D:\DeepLearning\Anaconda3\envs\PaddleDetection\lib\site-packages\paddleslim\prune\prune_worker.py", line 321, in _prune
    self._visit_and_search(in_var, actual_axis, pruned_idx)
  File "D:\DeepLearning\Anaconda3\envs\PaddleDetection\lib\site-packages\paddleslim\prune\prune_worker.py", line 114, in _visit_and_search
    self._prune_op(op, var, axis, transforms)
  File "D:\DeepLearning\Anaconda3\envs\PaddleDetection\lib\site-packages\paddleslim\prune\prune_worker.py", line 147, in _prune_op
    worker.prune(var, pruned_axis, pruned_idx)
  File "D:\DeepLearning\Anaconda3\envs\PaddleDetection\lib\site-packages\paddleslim\prune\prune_worker.py", line 94, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "D:\DeepLearning\Anaconda3\envs\PaddleDetection\lib\site-packages\paddleslim\prune\prune_worker.py", line 278, in _prune
    self._visit_and_search(in_var, pruned_axis, pruned_idx)
  File "D:\DeepLearning\Anaconda3\envs\PaddleDetection\lib\site-packages\paddleslim\prune\prune_worker.py", line 114, in _visit_and_search
    self._prune_op(op, var, axis, transforms)
  File "D:\DeepLearning\Anaconda3\envs\PaddleDetection\lib\site-packages\paddleslim\prune\prune_worker.py", line 147, in _prune_op
    worker.prune(var, pruned_axis, pruned_idx)
  File "D:\DeepLearning\Anaconda3\envs\PaddleDetection\lib\site-packages\paddleslim\prune\prune_worker.py", line 94, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "D:\DeepLearning\Anaconda3\envs\PaddleDetection\lib\site-packages\paddleslim\prune\prune_worker.py", line 215, in _prune
    pruned_axis, var.name(), channel_axis)
AssertionError: pruned_axis: 4; var: conv2d_117.tmp_0 channel_axis: 1

进程已结束,退出代码1
模型中有深度可分离卷积和正常卷积

**Comment by minghaoBD** [comment]
我没有找到您报错的代码片段，最新版本的PaddleSlim包含对于depthwise_conv2d的处理逻辑：https://github.com/PaddlePaddle/PaddleSlim/blob/develop/paddleslim/prune/prune_worker.py#L307

请尝试更新PaddleSlim版本。

**Comment by shangshanruowo** [comment]
> 我没有找到您报错的代码片段，最新版本的PaddleSlim包含对于depthwise_conv2d的处理逻辑：https://github.com/PaddlePaddle/PaddleSlim/blob/develop/paddleslim/prune/prune_worker.py#L307
> 
> 请尝试更新PaddleSlim版本。

好的感谢回复，我还有在paddledetction中使用你们的slim进行量化减枝，使用过程也出现一些问题，在paddledetction上你们同事让我在这边问一下，可以帮忙看一下吗：
[https://github.com/PaddlePaddle/PaddleDetection/issues/8792](url)
预祝新年快乐^_^
