### ISSUE TITLE
'SchemaDict' object has no attribute 'check_or_download_dataset'

### ISSUE THREAD

**Issue by liuxinglau** [PaddlePaddle/PaddleSlim#1789]
l
执行paddleslim/example/full_quantization/picodet/run.py,出现这个对象SchemaDict没有定义'check_or_download_dataset这个属性的错误，请教下这个是什么问题？我这边按照最新版本装的paddlepaddle-gpu:
python -m pip install paddlepaddle-gpu==2.5.1.post102 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html
paddleslim版本为2.4.1PaddleDetection版本为2.6

iuxj@liuxj-desktop:~/fallai/paddleslim/example/full_quantization/picodet$ python run.py --config_path=./configs/picodet_npu_with_postprocess.yaml --save_dir='./output/'
Warning: Unable to use JDE/FairMOT/ByteTrack, please install lap, for example: `pip install lap`, see https://github.com/gatagat/lap
-----------  Running Arguments -----------
 Distillation:
	 alpha: 1.0
	 loss: l2
 Global:
	 Evaluation: True
	 include_post_process: True
	 input_list: ['image', 'scale_factor']
	 model_dir: ./picodet_s_416_voc_npu
	 model_filename: model.pdmodel
	 params_filename: model.pdiparams
	 reader_config: ./configs/voc_detection.yml
 PTQ:
	 activation_quantize_type: moving_average_abs_max
	 algo: avg
	 batch_nums: 10
	 batch_size: 32
	 onnx_format: False
	 quantizable_op_type: ['conv2d', 'depthwise_conv2d']
 QuantAware:
	 activation_bits: 8
	 activation_quantize_type: moving_average_abs_max
	 quantize_op_types: ['conv2d', 'depthwise_conv2d']
	 use_pact: True
	 weight_bits: 8
 TrainConfig:
	 eval_iter: 1000
	 learning_rate:
		 T_max: 8000
		 learning_rate: 1e-05
		 type: CosineAnnealingDecay
	 optimizer_builder:
		 optimizer:
			 type: SGD
		 weight_decay: 4e-05
	 train_iter: 8000
------------------------------------------
Traceback (most recent call last):
  File "run.py", line 170, in <module>
    main()
  File "run.py", line 126, in main
    train_loader = create('TrainReader')(reader_cfg['TrainDataset'],
  File "/usr/local/lib/python3.8/dist-packages/paddledet-2.6.0-py3.8.egg/ppdet/data/reader.py", line 167, in __call__
    self.dataset.check_or_download_dataset()
AttributeError: 'SchemaDict' object has no attribute 'check_or_download_dataset'

各位大侠帮忙看看是什么原因？

**Comment by pcycccccc** [comment]
我在跑这个run.py文件的时候也出现这个问题，原来提供的是picodet_reader.yml配置文件提供的是COCO数据格式的，我想修改成VOC格式出现了这种报错，因为VOC的配置没有提供参考，所以我也不知道是不是写对了，后面只能修改回COCO（并且提供COCO格式的数据集），就能跑了，我觉得应该是写数据集路径或者数据集的其他配置参数上出现了问题，所以报错。
盲猜是没写对路径，找不到数据，所以报错了

**Comment by XGZhang11** [comment]
应该是数据配置的问题
