### ISSUE TITLE
使用paddleslim的模型自动化压缩工具ACT报错

### ISSUE THREAD

**Issue by EddieEduardo** [PaddlePaddle/PaddleSlim#1808]
按照paddleslim/example/auto_compression的Readme.md进行操作，运行运行自动化压缩时报错：
```

Traceback (most recent call last):
  File "/aidata/CYHan/auto_compass.py", line 42, in <module>
    ac.compress()
  File "/root/anaconda3/envs/cyhan_paddle/lib/python3.9/site-packages/paddleslim/auto_compression/compressor.py", line 593, in compress
    self.single_strategy_compress(strategy, config, strategy_idx,
  File "/root/anaconda3/envs/cyhan_paddle/lib/python3.9/site-packages/paddleslim/auto_compression/compressor.py", line 715, in single_strategy_compress
    post_quant_hpo.quant_post_hpo(
  File "/root/anaconda3/envs/cyhan_paddle/lib/python3.9/site-packages/paddleslim/quant/post_quant_hpo.py", line 425, in quant_post_hpo
    from smac.configspace import ConfigurationSpace
  File "/root/anaconda3/envs/cyhan_paddle/lib/python3.9/site-packages/smac/__init__.py", line 27, in <module>
    from smac.facade import (
  File "/root/anaconda3/envs/cyhan_paddle/lib/python3.9/site-packages/smac/facade/__init__.py", line 1, in <module>
    from smac.facade.abstract_facade import AbstractFacade
  File "/root/anaconda3/envs/cyhan_paddle/lib/python3.9/site-packages/smac/facade/abstract_facade.py", line 10, in <module>
    from dask.distributed import Client
  File "/root/anaconda3/envs/cyhan_paddle/lib/python3.9/site-packages/dask/distributed.py", line 13, in <module>
    from distributed import *
  File "/root/anaconda3/envs/cyhan_paddle/lib/python3.9/site-packages/distributed/__init__.py", line 23, in <module>
    from distributed.actor import Actor, ActorFuture, BaseActorFuture
  File "/root/anaconda3/envs/cyhan_paddle/lib/python3.9/site-packages/distributed/actor.py", line 13, in <module>
    from distributed.client import Future
  File "/root/anaconda3/envs/cyhan_paddle/lib/python3.9/site-packages/distributed/client.py", line 117, in <module>
    from distributed.worker import get_client, get_worker, secede
  File "/root/anaconda3/envs/cyhan_paddle/lib/python3.9/site-packages/distributed/worker.py", line 120, in <module>
    from distributed.worker_memory import (
  File "/root/anaconda3/envs/cyhan_paddle/lib/python3.9/site-packages/distributed/worker_memory.py", line 56, in <module>
    WorkerDataParameter: TypeAlias = Union[
  File "/root/anaconda3/envs/cyhan_paddle/lib/python3.9/typing.py", line 243, in inner
    return func(*args, **kwds)
  File "/root/anaconda3/envs/cyhan_paddle/lib/python3.9/typing.py", line 316, in __getitem__
    return self._getitem(self, parameters)
  File "/root/anaconda3/envs/cyhan_paddle/lib/python3.9/typing.py", line 421, in Union
    parameters = _remove_dups_flatten(parameters)
  File "/root/anaconda3/envs/cyhan_paddle/lib/python3.9/typing.py", line 215, in _remove_dups_flatten
    all_params = set(params)
TypeError: unhashable type: 'list'
```
python版本3.9 
paddlepaddle-gpu版本2.4.2 
paddleslim版本2.4.0
求解问题出在那里？

**Comment by ceci3** [comment]
smac的版本可能会有问题，可以安装 1.4.0 试下
