### ISSUE TITLE
AttributeError: 'Teacher' object has no attribute '_manager'

### ISSUE THREAD

**Issue by Dabulv** [PaddlePaddle/PaddleSlim#394]
### 环境
paddlepaddle-gpu     1.8.1.post97
paddleslim           1.1.1

### 命令
CUDA_VISIBLE_DEVICES=0 python -u run_teacher1.py --use_cuda true --out_port 8080

### 报错信息
2020-07-22 22:11:36,723-WARNING: If you want to use training-aware and post-training quantization, please use Paddle >= 2.0.0 or develop version
python3.6.8/lib/python3.6/site-packages/paddle/fluid/executor.py:1093: UserWarning: There are no operators in the program to be executed. If you pass Program manually, please use fluid.program_guard to ensure the current Program is being used.
  warnings.warn(error_info)
W0722 22:11:36.740073  1295 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 35, Driver API Version: 9.0, Runtime API Version: 9.0
W0722 22:11:36.744243  1295 device_context.cc:260] device: 0, cuDNN Version: 7.0.
W0722 22:11:38.036867  1295 device_context.h:155] WARNING: device: 0. The installed Paddle is compiled with CUDNN 7.3, but CUDNN version in your machine is 7.0, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.
Process BaseManager-1:
Traceback (most recent call last):
  File "python3.6.8/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "python3.6.8/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "python3.6.8/lib/python3.6/multiprocessing/managers.py", line 539, in _run_server
    server = cls._Server(registry, address, authkey, serializer)
  File "python3.6.8/lib/python3.6/multiprocessing/managers.py", line 139, in __init__
    self.listener = Listener(address=address, backlog=16)
  File "python3.6.8/lib/python3.6/multiprocessing/connection.py", line 438, in __init__
    self._listener = SocketListener(address, family, backlog)
  File "python3.6.8/lib/python3.6/multiprocessing/connection.py", line 576, in __init__
    self._socket.bind(address)
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "run_teacher1.py", line 81, in <module>
    run(args)
  File "run_teacher1.py", line 42, in run
    teacher.start()
  File "github/PaddleSlim/paddleslim/pantheon/teacher.py", line 233, in start
    self._manager = self._start_manager() if self._out_port else None
  File "github/PaddleSlim/paddleslim/pantheon/teacher.py", line 219, in _start_manager
    manager.start()
  File "/python3.6.8/lib/python3.6/multiprocessing/managers.py", line 517, in start
    self._address = reader.recv()
  File "python3.6.8/lib/python3.6/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "python3.6.8/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "python3.6.8/lib/python3.6/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Exception ignored in: <bound method Teacher.__del__ of <paddleslim.pantheon.teacher.Teacher object at 0x7f094e5f9b38>>
Traceback (most recent call last):
  File "github/PaddleSlim/paddleslim/pantheon/teacher.py", line 661, in __del__
    if self._manager:
AttributeError: 'Teacher' object has no attribute '_manager'

**Comment by Dabulv** [comment]
没注意看 OSError: [Errno 98] Address already in use
