### ISSUE TITLE
使用slim.quant.quant_post量化时出错

### ISSUE THREAD

**Issue by CVdandelion** [PaddlePaddle/PaddleSlim#478]
对YOLOv3模型进行量化，将slim.quant.quant_post安排到了paddledetection中的得infer.py文件中，借助其exe与program
```
Traceback (most recent call last):
  File "tools/infer.py", line 278, in <module>
    main()
  File "tools/infer.py", line 242, in main
    batch_nums=10)
  File "/home/robot/anaconda3/envs/paddle/lib/python3.7/site-packages/paddleslim/quant/quanter.py", line 331, in quant_post
    post_training_quantization.quantize()
  File "/home/robot/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/contrib/slim/quantization/post_training_quantization.py", line 300, in quantize
    self._calculate_kl_threshold()
  File "/home/robot/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/contrib/slim/quantization/post_training_quantization.py", line 503, in _calculate_kl_threshold
    weight_data = self._sampling_data[var_name]
KeyError: 'stage.3.6.1.conv.weights'
```
而且每次KeyError:后面的内容都会变化，请问是什么原因

**Comment by CVdandelion** [comment]
这个是详细信息
```
2020-10-21 19:27:48,227-INFO: Load model and set data loader ...
2020-10-21 19:27:48,318-INFO: Collect quantized variable names ...
2020-10-21 19:27:48,339-INFO: Finish all batch: 0
2020-10-21 19:27:48,341-INFO: Calculate KL threshold ...
Traceback (most recent call last):
  File "tools/infer.py", line 278, in <module>
    main()
  File "tools/infer.py", line 242, in main
    batch_nums=10)
  File "/home/robot/anaconda3/envs/paddle/lib/python3.7/site-packages/paddleslim/quant/quanter.py", line 331, in quant_post
    post_training_quantization.quantize()
  File "/home/robot/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/contrib/slim/quantization/post_training_quantization.py", line 300, in quantize
    self._calculate_kl_threshold()
  File "/home/robot/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/contrib/slim/quantization/post_training_quantization.py", line 503, in _calculate_kl_threshold
    weight_data = self._sampling_data[var_name]
KeyError: 'stage.3.6.1.conv.weights'
```

**Comment by baiyfbupt** [comment]
请问您用的Paddle版本是？我们查一下问题

**Comment by CVdandelion** [comment]
> 请问您用的Paddle版本是？我们查一下问题
1.8.4

**Comment by baiyfbupt** [comment]
这种情况一般是reader没写对，导致离线量化没有正常跑前向过程，没有收集到中间的激活值，可以再check一下reader是否正确
