### ISSUE TITLE
模型蒸馏通过merge来对teacher_program重命名时出现变量不在当前block内的问题

### ISSUE THREAD

**Issue by Heuchler7** [PaddlePaddle/PaddleSlim#508]
```bash
Traceback (most recent call last):
  File "D:\Program Files\JetBrains\PyCharm Community Edition 2020.2.1\plugins\python-ce\helpers\pydev\pydevd.py", line 1448, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\Program Files\JetBrains\PyCharm Community Edition 2020.2.1\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/NLP_SRO/逐步改进版本/SimpleInterface/JointTrainner.py", line 88, in <module>
    slim.dist.merge(teacher_program,student_train_program,data_name_map,place)
  File "C:\Users\bsw12\code\lib\site-packages\paddleslim\dist\single_distiller.py", line 66, in merge
    teacher_var.name, new_name)
  File "C:\Users\bsw12\code\lib\site-packages\paddle\fluid\framework.py", line 2378, in _rename_var
    raise ValueError("var %s is not in current block" % name)
ValueError: var transpose_4.tmp_0 is not in current block
```
上述为完整的报错信息，代码如图

**Comment by Heuchler7** [comment]
```bash
teacher_train_program = fluid.Program()
teacher_train_startup = fluid.Program()

with fluid.program_guard(teacher_train_program, teacher_train_startup):
    with fluid.unique_name.guard():
        ls1, ls2, lo1, lo2, ps1, ps2, po1, po2, mask = teacher_model(cfg=cfg)
        label, predict = [ls1, ls2, lo1, lo2], [ps1, ps2, po1, po2]
        train_tec_loss = Base_Loss(label, predict, mask)

student_train_program = fluid.Program()
student_train_startup = fluid.Program()

with fluid.program_guard(student_train_program, student_train_startup):
    ls1, ls2, lo1, lo2, ps1, ps2, po1, po2, mask = student_model(cfg=cfg)
    label, predict = [ls1, ls2, lo1, lo2], [ps1, ps2, po1, po2]
    train_stu_loss = Base_Loss(label, predict, mask)


data_name_map = {'T1':'T1','S1':'S1','S2':'S2','K1':'K1','K2':'K2','O1':'O1', 'O2':'O2'
               ,'kin0':'kin0','kin1':'kin1','kin2':'kin2','kin3':'kin3','kin4':'kin4','kin5':'kin5'}

# # Embedding Version
# data_name_map = {'T1':'T1','T2':'T2','S1':'S1','S2':'S2','K1':'K1','K2':'K2','O1':'O1', 'O2':'O2'
#                ,'kin0':'kin0','kin1':'kin1','kin2':'kin2','kin3':'kin3','kin4':'kin4','kin5':'kin5'}

place = fluid.CUDAPlace(0) if cfg['train_params']['use_cuda'] else fluid.CPUPlace()
exe = fluid.Executor(place)
# fluid.io.load_params(executor=exe, dirname=cfg['path']['params_saved'], main_program=teacher_train_program)
teacher_program = teacher_train_program.clone(for_test=True)
slim.dist.merge(teacher_program,student_train_program,data_name_map,place)
```

没找到我po的图，就直接上代码吧，执行到上述最后一句报错

**Comment by Heuchler7** [comment]
我后面打印出来所有teacher_program.global_block()内的transpose变量，确实是有transpose_4.tmp_0,那为什么还会报错呢？

**Comment by baiyfbupt** [comment]
teacher模型是否存在控制流代码https://www.paddlepaddle.org.cn/documentation/docs/zh/api_guides/low_level/layers/control_flow.html#ifelse ,导致模型存在多个block呢？

**Comment by Heuchler7** [comment]
是的，看了下内部一共三个block,所以全局所有变量数大于global_block内变量数。
对了，我使用的是对应1.7paddle版本的1.0.1的paddleSlim。
后来我决定自己根据官方mergeAPI写一个自己的merge，但碰到了一个program下不同block内报这个错：
Traceback (most recent call last):
  File "D:\Program Files\JetBrains\PyCharm Community Edition 2020.2.1\plugins\python-ce\helpers\pydev\pydevd.py", line 1448, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\Program Files\JetBrains\PyCharm Community Edition 2020.2.1\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/NLP_SRO/逐步改进版本/SimpleInterface/JointTrainner.py", line 135, in <module>
    merge(teacher_program,student_train_program,data_name_map,place)
  File "D:/NLP_SRO/逐步改进版本/SimpleInterface/JointTrainner.py", line 63, in merge
    teacher_var, force_persistable=False)
  File "C:\Users\bsw12\code\lib\site-packages\paddle\fluid\framework.py", line 2759, in _clone_variable
    need_check_feed=var.desc.need_check_feed())
  File "C:\Users\bsw12\code\lib\site-packages\paddle\fluid\framework.py", line 2348, in create_var
    var = Variable(block=self, *args, **kwargs)
  File "C:\Users\bsw12\code\lib\site-packages\paddle\fluid\framework.py", line 895, in __init__
    "matched.".format(self.name, old_shape, shape))
ValueError: Variable transpose_3.tmp_0 has been created before. the previous shape is (-1, 300, 4, 16); the new shape is (-1, 300, 16, 4). They are not matched.

初步怀疑是不同block内有名称相同的变量，我对于原版本merge的改动在这里：
将原来的renamed_var = teacher_program.global_block()._rename_var(
                    teacher_var.name, new_name)
改为：
                block_num = teacher_program.num_blocks
                for idx in range(block_num):
                    if teacher_var in teacher_program.block(idx).vars:
                        renamed_var = teacher_program.block(idx)._rename_var(
                            teacher_var.name, new_name)
能帮忙看看吗？

**Comment by baiyfbupt** [comment]
您好，目前slim蒸馏还不支持这种多block模型

**Comment by Heuchler7** [comment]
谢谢回复，那我想问下如果我自己重构merge支持了多block，后面实际训练还是会出现问题是么？
在2020年11月13日 10:22，Bai Yifan 写道：

您好，目前slim蒸馏还不支持这种多block模型

**Comment by baiyfbupt** [comment]
主要是merge的问题，可以试一下，也欢迎贡献代码~

**Comment by Heuchler7** [comment]
我尝试了下，但报出了新的错误，打眼一看好像是不同block内变量重名的问题，目前还在调试，想问下一个unique-name-guard下的peogram内不同block间有没有可能变量重名，如果有的话有解决方案吗？




在2020年11月13日 10:26，Bai Yifan 写道：

主要是merge的问题，可以试一下，也欢迎贡献代码~

**Comment by baiyfbupt** [comment]
一个unique-name-guard应该不会有同名变量

**Comment by Heuchler7** [comment]
emmm，那我再仔细看看是什么原因。对了，能顺便问您一个关于slim下剪枝prune方法debug中的问题吗？还是需要我在issue上先更新？




在2020年11月13日 10:42，Bai Yifan 写道：

一个unique-name-guard应该不会有同名变量

**Comment by Heuchler7** [comment]
place = fluid.CUDAPlace(0) if USE_CUDA else fluid.CPUPlace()
exe = fluid.Executor(place)
startup_program.random_seed = 1
scope=fluid.global_scope()
exe.run(startup_program)
exe.run(startup_program,scope=scope)
prune=Pruner()
a = train_program.global_block().vars
for item in a.keys():
    if '_out' in item:
        print(item)
for param in train_program.global_block().all_parameters():
    if "weights" in param.name:
        print("param name: {}; param shape: {}".format(param.name, param.shape))
train_program,_,_=prune.prune(train_program,scope,
                              params=['n1_weights','n2_weights','n3_weights','n4_weights','conv1_weights','conv2_weights'],
                              ratios=[0.3,0.3,0.3,0.3,0.3,0.3],
                              place=place,
                              lazy=True)
剪枝上我仔细看了下接口用法没有问题，我们需要剪枝的模型也是多block，不过需要剪枝的param我断点进去看了下确实是在global_block下，也就是说其也是在global_scope内的，但运行上述剪枝代码后出现下面的问题：
Traceback (most recent call last):
  File "D:\Program Files\JetBrains\PyCharm Community Edition 2020.2.1\plugins\python-ce\helpers\pydev\pydevd.py", line 1448, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\Program Files\JetBrains\PyCharm Community Edition 2020.2.1\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/NLP_SRO/Code/finalTest/train_simple1.py", line 365, in <module>
    lazy=True)
  File "C:\Users\bsw12\code\lib\site-packages\paddleslim\prune\pruner.py", line 85, in prune
    conv_op = param.outputs()[0]
  File "C:\Users\bsw12\code\lib\site-packages\paddleslim\core\graph_wrapper.py", line 94, in outputs
    if self in op.all_inputs():
  File "C:\Users\bsw12\code\lib\site-packages\paddleslim\core\graph_wrapper.py", line 49, in __eq__
    return self._var.name == v._var.name
AttributeError: 'NoneType' object has no attribute '_var'

**Comment by Heuchler7** [comment]
余留问题转新一个issue内描述

**Comment by lrp123456** [comment]
@Heuchler7 同学你好，我遇到了相同的问题，请问通过修改merge后续会有影响吗
