### ISSUE TITLE
使用离线量化paddlex的模型出错

### ISSUE THREAD

**Issue by Huihuihh** [PaddlePaddle/PaddleSlim#676]
针对paddlex的工业质检yolov3模型导出，然后利用paddleslim进行离线量化
paddleslim版本1.1.1

执行下面的命令
```
python3 quant_post.py --model_path ./yolov3/ --save_path ./quant_model_train/easydl-yolov3 --model_filename __model__ --params_filename __params__ --use_gpu false
```
报错信息
```
/home/awcloud/Desktop/paddle/PaddleSlim/demo/data/ILSVRC2012/
train_list.txt
2021-02-25 18:14:16,461-INFO: Load model and set data loader ...
2021-02-25 18:14:16,538-INFO: Collect quantized variable names ...
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/paddle/reader/decorator.py", line 398, in read_worker
    for i in reader():
  File "../../reader_cv2.py", line 465, in reader
    yield img_path, int(label)
ValueError: invalid literal for int() with base 10: 'Annotations/jiaoweiloudi-188.xml'
```

**Comment by wanghaoshuang** [comment]
## 如果你完全参考[示例](https://github.com/PaddlePaddle/PaddleSlim/tree/release/2.0.0/demo/quant/quant_post)的话：

这个应该是数据格式的问题。

在``demo``文件夹下创建``data``文件夹，将``ImageNet``数据集解压在``data``文件夹下，解压后``data/ILSVRC2012``文件夹下应包含以下文件：
- ``'train'``文件夹，训练图片
- ``'train_list.txt'``文件
- ``'val'``文件夹，验证图片
- ``'val_list.txt'``文件

其中，``'train_list.txt'`` 文件中每行为一个样本，格式为：

```
image_path label
```
image_path为相对路径。label为数值类型的类别，而你给的是'Annotations/jiaoweiloudi-188.xml'。

## 如果你是在[示例](https://github.com/PaddlePaddle/PaddleSlim/tree/release/2.0.0/demo/quant/quant_post)基础上做了修改：

请将以下脚本内容贴到issue里：

- ../../reader_cv2.py
- quant_post.py
- train_list.txt （几行示例即可）

**Comment by Huihuihh** [comment]
我按照AIStudio上面的yolov3的例子改了下测试，也是有问题
`../../reader_cv2.py`
```
import os
import math
import random
import functools
import numpy as np
import cv2
import io

from PIL import Image
from PIL import ImageDraw

import argparse
from utility import add_arguments, print_arguments

import paddle

parser = argparse.ArgumentParser(description=__doc__)
add_arg = functools.partial(add_arguments, argparser=parser)

add_arg('data_dim',       int,  224,                 "data dimension")
add_arg('data_dir',       str,  "../../data/果蔬23_0910",  "data dir")
add_arg('image_mean',      str, "0.485,0.456,0.406",       "Input image mean")
add_arg('image_std',      str, "0.229,0.224,0.225",       "Input image standards")
add_arg('thread_num',       int,  4,                 "thread number")
add_arg('buf_size',       int,  224,                 "buffer size")


random.seed(0)
np.random.seed(0)

#DATA_DIM = 224
#THREAD = 4
#BUF_SIZE = 2048
DATA_DIR = '../../data/果蔬23_0910'
img_mean = np.array([0.485, 0.456, 0.406]).reshape((3, 1, 1))
img_std = np.array([0.229, 0.224, 0.225]).reshape((3, 1, 1))

## 果蔬模型 ResNet50 InceptionV4
#DATA_DIM = 224
#THREAD = 4
#BUF_SIZE = 2048
#DATA_DIR = '../../data/果蔬23_0910'
#img_mean = np.array([0.485, 0.456, 0.406]).reshape((3, 1, 1))
#img_std = np.array([0.229, 0.224, 0.225]).reshape((3, 1, 1))

### ShuffleNetV2-yolov3

#DATA_DIM = 384
THREAD = 4
BUF_SIZE = 2048
#DATA_DIR = '../../data/pascalvoc'
TRAIN_LIST = "train_list.txt"
#img_mean = np.array([0.5, 0.5, 0.5]).reshape((3, 1, 1))
#img_std = np.array([0.007843, 0.007843, 0.007843]).reshape((3, 1, 1))

#args = parser.parse_args()
#print_arguments(args)

#DATA_DIM = args.data_dim
#THREAD = args.thread_num
#BUF_SIZE = args.buf_size
#DATA_DIR = args.data_dir
#img_mean = np.array([args.image_mean[0]], [args.image_mean[1]], [args.image_mean[2]]).reshape((3, 1, 1))
#img_std = np.array([args.image_std[0]], [args.image_std[1]], [args.image_std[2]]).reshape((3, 1, 1))



def rotate_image(img):
    """ rotate_image """
    (h, w) = img.shape[:2]
    center = (w / 2, h / 2)
    angle = np.random.randint(-10, 11)
    M = cv2.getRotationMatrix2D(center, angle, 1.0)
    rotated = cv2.warpAffine(img, M, (w, h))
    return rotated


def random_crop(img, size, settings, scale=None, ratio=None):
    """ random_crop """
    lower_scale = settings.lower_scale
    lower_ratio = settings.lower_ratio
    upper_ratio = settings.upper_ratio
    scale = [lower_scale, 1.0] if scale is None else scale
    ratio = [lower_ratio, upper_ratio] if ratio is None else ratio

    aspect_ratio = math.sqrt(np.random.uniform(*ratio))
    w = 1. * aspect_ratio
    h = 1. / aspect_ratio

    bound = min((float(img.shape[0]) / img.shape[1]) / (h**2),
                (float(img.shape[1]) / img.shape[0]) / (w**2))

    scale_max = min(scale[1], bound)
    scale_min = min(scale[0], bound)

    target_area = img.shape[0] * img.shape[1] * np.random.uniform(scale_min,
                                                                  scale_max)
    target_size = math.sqrt(target_area)
    w = int(target_size * w)
    h = int(target_size * h)
    i = np.random.randint(0, img.shape[0] - h + 1)
    j = np.random.randint(0, img.shape[1] - w + 1)

    img = img[i:i + h, j:j + w, :]

    resized = cv2.resize(
        img,
        (size, size)
        #, interpolation=cv2.INTER_LANCZOS4
    )
    return resized


def random_brightness(img):
    prob = np.random.uniform(0, 1)
    if prob < train_parameters['image_distort_strategy']['brightness_prob']:
        brightness_delta = train_parameters['image_distort_strategy']['brightness_delta']
        delta = np.random.uniform(-brightness_delta, brightness_delta) + 1
        img = ImageEnhance.Brightness(img).enhance(delta)
    return img


def random_contrast(img):
    prob = np.random.uniform(0, 1)
    if prob < train_parameters['image_distort_strategy']['contrast_prob']:
        contrast_delta = train_parameters['image_distort_strategy']['contrast_delta']
        delta = np.random.uniform(-contrast_delta, contrast_delta) + 1
        img = ImageEnhance.Contrast(img).enhance(delta)
    return img


def random_saturation(img):
    prob = np.random.uniform(0, 1)
    if prob < train_parameters['image_distort_strategy']['saturation_prob']:
        saturation_delta = train_parameters['image_distort_strategy']['saturation_delta']
        delta = np.random.uniform(-saturation_delta, saturation_delta) + 1
        img = ImageEnhance.Color(img).enhance(delta)
    return img


def random_hue(img):
    prob = np.random.uniform(0, 1)
    if prob < train_parameters['image_distort_strategy']['hue_prob']:
        hue_delta = train_parameters['image_distort_strategy']['hue_delta']
        delta = np.random.uniform(-hue_delta, hue_delta)
        img_hsv = np.array(img.convert('HSV'))
        img_hsv[:, :, 0] = img_hsv[:, :, 0] + delta
        img = Image.fromarray(img_hsv, mode='HSV').convert('RGB')
    return img

def distort_color(img):
    prob = np.random.uniform(0, 1)
    # Apply different distort order
    if prob > 0.5:
        img = random_brightness(img)
        img = random_contrast(img)
        img = random_saturation(img)
        img = random_hue(img)
    else:
        img = random_brightness(img)
        img = random_saturation(img)
        img = random_hue(img)
        img = random_contrast(img)
    return img


def resize_short(img, target_size):
    """ resize_short """
    percent = float(target_size) / min(img.shape[0], img.shape[1])
    resized_width = int(round(img.shape[1] * percent))
    resized_height = int(round(img.shape[0] * percent))
    resized = cv2.resize(
        img,
        (resized_width, resized_height),
        #interpolation=cv2.INTER_LANCZOS4
    )
    return resized


def crop_image(img, target_size, center):
    """ crop_image """
    height, width = img.shape[:2]
    size = target_size
    if center == True:
        w_start = (width - size) // 2
        h_start = (height - size) // 2
    else:
        w_start = np.random.randint(0, width - size + 1)
        h_start = np.random.randint(0, height - size + 1)
    w_end = w_start + size
    h_end = h_start + size
    img = img[h_start:h_end, w_start:w_end, :]
    return img


def create_mixup_reader(settings, rd):
    class context:
        tmp_mix = []
        tmp_l1 = []
        tmp_l2 = []
        tmp_lam = []

    batch_size = settings.batch_size
    alpha = settings.mixup_alpha

    def fetch_data():

        data_list = []
        for i, item in enumerate(rd()):
            data_list.append(item)
            if i % batch_size == batch_size - 1:
                yield data_list
                data_list = []

    def mixup_data():

        for data_list in fetch_data():
            if alpha > 0.:
                lam = np.random.beta(alpha, alpha)
            else:
                lam = 1.
            l1 = np.array(data_list)
            l2 = np.random.permutation(l1)
            mixed_l = [
                l1[i][0] * lam + (1 - lam) * l2[i][0] for i in range(len(l1))
            ]
            yield mixed_l, l1, l2, lam

    def mixup_reader():

        for context.tmp_mix, context.tmp_l1, context.tmp_l2, context.tmp_lam in mixup_data():
            for i in range(len(context.tmp_mix)):
                mixed_l = context.tmp_mix[i]
                l1 = context.tmp_l1[i]
                l2 = context.tmp_l2[i]
                lam = context.tmp_lam
                yield mixed_l, l1[1], l2[1], lam

    return mixup_reader


def process_image(sample,
                  settings,
                  mode,
                  color_jitter,
                  rotate,
                  crop_size=224,
                  mean=None,
                  std=None):
    """ process_image """

    mean = [0.485, 0.456, 0.406] if mean is None else mean
    std = [0.229, 0.224, 0.225] if std is None else std

    img_path = sample[0]
    img = cv2.imread(img_path)

    if mode == 'train':
        if rotate:
            img = rotate_image(img)
        if crop_size > 0:
            img = random_crop(img, crop_size, settings)
        if color_jitter:
            img = distort_color(img)
        if np.random.randint(0, 2) == 1:
            img = img[:, ::-1, :]
    else:
        if crop_size > 0:
            target_size = settings.resize_short_size
            img = resize_short(img, target_size)

            img = crop_image(img, target_size=crop_size, center=True)

    img = img[:, :, ::-1].astype('float32').transpose((2, 0, 1)) / 255
    img_mean = np.array(mean).reshape((3, 1, 1))
    img_std = np.array(std).reshape((3, 1, 1))
    img -= img_mean
    img /= img_std

    if mode == 'train' or mode == 'val':
       # print (sample[1])
        img = np.expand_dims(img, 0)
        #print (img.shape)
        return (img, sample[1])

    elif mode == 'test':
        return (img, )


def image_mapper(**kwargs):
    """ image_mapper """
    return functools.partial(process_image, **kwargs)

## yolov3
## begin
def resize_img(img, target_size):
    """
    保持比例的缩放图片
    :param img:
    :param target_size:
    :return:
    """
    img = img.resize(target_size[1:], Image.BILINEAR)

    return img

def read_image(img):
    """
    读取图片
    :param img_path:
    :return:
    """
    origin = img
    #img = resize_img(origin, yolo_config["input_size"])
    img = resize_img(origin, np.array([3,384,384]))

    resized_img = img.copy()
    if img.mode != 'RGB':
        img = img.convert('RGB')
    img = np.array(img).astype('float32').transpose((2, 0, 1))  # HWC to CHW
    img -= 127.5
    img *= 0.007843
    img = img[np.newaxis, :]
    return origin, img, resized_img

def _reader_creator_yolov3(settings,
                    file_list,
                    mode,
                    shuffle=False,
                    color_jitter=False,
                    rotate=False,
                    data_dir=DATA_DIR,
                    pass_id_as_seed=0):
    def reader():
        with open(file_list) as flist:
            full_lines = [line.strip() for line in flist]

            if shuffle:
                if pass_id_as_seed:
                    np.random.seed(pass_id_as_seed)
                np.random.shuffle(full_lines)
            if mode == 'train' and os.getenv('PADDLE_TRAINING_ROLE'):
                # distributed mode if the env var `PADDLE_TRAINING_ROLE` exits
                trainer_id = int(os.getenv("PADDLE_TRAINER_ID", "0"))
                trainer_count = int(os.getenv("PADDLE_TRAINERS_NUM", "1"))
                per_node_lines = len(full_lines) // trainer_count
                lines = full_lines[trainer_id * per_node_lines:(trainer_id + 1)
                                   * per_node_lines]
                print(
                    "read images from %d, length: %d, lines length: %d, total: %d"
                    % (trainer_id * per_node_lines, per_node_lines, len(lines),
                       len(full_lines)))
            else:
                lines = full_lines


            for line in lines:
                if mode == 'train' or mode == 'val':
                    if len(line.split())>2:
                        continue
                    img_path, label = line.split()
                    ## debug
                    ##print (img_path)
                    img_path = os.path.join(data_dir, img_path)
                    #yield img_path, int(label)
                    image = cv2.imread(img_path)
                    image = Image.fromarray(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))
                    origin, tensor_img, resized_img = read_image(image)
                    input_w, input_h = origin.size[0], origin.size[1]
                    image_shape = np.array([input_h, input_w], dtype='int32')
                    #print("$$$$$", image_shape[np.newaxis, :])
                    #yield img_path, int(label)
                    yield img_path, image_shape[np.newaxis, :]
                elif mode == 'test':
                    if len(line.split())>2:
                        continue
                    img_path, label = line.split()
                    img_path = os.path.join(data_dir, img_path)

                    yield [img_path]

    crop_size = int(settings.image_shape.split(",")[2])
    image_mapper = functools.partial(
        process_image,
        settings=settings,
        mode=mode,
        color_jitter=color_jitter,
        rotate=rotate,
        crop_size=crop_size)
    reader = paddle.reader.xmap_readers(
        image_mapper, reader, THREAD, BUF_SIZE, order=False)
    return reader

def train_yolov3(settings, data_dir=DATA_DIR, pass_id_as_seed=0, train_list_name=TRAIN_LIST):
    #file_list = os.path.join(data_dir, 'train_list.txt')
    file_list = os.path.join(data_dir, train_list_name)
    reader = _reader_creator_yolov3(
        settings,
        file_list,
        'train',
        #'test',
        shuffle=True,
        color_jitter=False,
        rotate=False,
        data_dir=data_dir,
        pass_id_as_seed=pass_id_as_seed, )
    if settings.use_mixup == True:
        reader = create_mixup_reader(settings, reader)
    return reader

##end

def _reader_creator(settings,
                    file_list,
                    mode,
                    shuffle=False,
                    color_jitter=False,
                    rotate=False,
                    data_dir=DATA_DIR,
                    #data_dir,
                    pass_id_as_seed=0):
    def reader():
        with open(file_list) as flist:
            full_lines = [line.strip() for line in flist]

            if shuffle:
                if pass_id_as_seed:
                    np.random.seed(pass_id_as_seed)
                np.random.shuffle(full_lines)
            if mode == 'train' and os.getenv('PADDLE_TRAINING_ROLE'):
                # distributed mode if the env var `PADDLE_TRAINING_ROLE` exits
                trainer_id = int(os.getenv("PADDLE_TRAINER_ID", "0"))
                trainer_count = int(os.getenv("PADDLE_TRAINERS_NUM", "1"))
                per_node_lines = len(full_lines) // trainer_count
                lines = full_lines[trainer_id * per_node_lines:(trainer_id + 1)
                                   * per_node_lines]
                print(
                    "read images from %d, length: %d, lines length: %d, total: %d"
                    % (trainer_id * per_node_lines, per_node_lines, len(lines),
                       len(full_lines)))
            else:
                lines = full_lines


            for line in lines:
                if mode == 'train' or mode == 'val':
                    if len(line.split())>2:
                        continue
                    img_path, label = line.split()
                    img_path = os.path.join(data_dir, img_path)
                    yield img_path, int(label)

                elif mode == 'test':
                    if len(line.split())>2:
                        continue
                    img_path, label = line.split()
                    img_path = os.path.join(data_dir, img_path)

                    yield [img_path]

    crop_size = int(settings.image_shape.split(",")[2])
    image_mapper = functools.partial(
        process_image,
        settings=settings,
        mode=mode,
        color_jitter=color_jitter,
        rotate=rotate,
        crop_size=crop_size)
    reader = paddle.reader.xmap_readers(
        image_mapper, reader, THREAD, BUF_SIZE, order=False)
    return reader


def train(settings, data_dir=DATA_DIR, pass_id_as_seed=0, train_list_name=TRAIN_LIST):
    #file_list = os.path.join(data_dir, 'train_list.txt')
    file_list = os.path.join(data_dir, train_list_name)
    print (data_dir)
    print (train_list_name)
    reader = _reader_creator(
        settings,
        file_list,
        'train',
        shuffle=True,
        color_jitter=False,
        rotate=False,
        data_dir=data_dir,
        pass_id_as_seed=pass_id_as_seed, )
    if settings.use_mixup == True:
        reader = create_mixup_reader(settings, reader)
    return reader


def val(settings, data_dir, val_list_name):
    #file_list = os.path.join(data_dir, 'val_list.txt')
    file_list = os.path.join(data_dir, val_list_name)
    return _reader_creator(
        settings, file_list, 'val', shuffle=False, data_dir=data_dir)


def test(settings, data_dir=DATA_DIR):
    file_list = os.path.join(data_dir, 'val_list.txt')
    return _reader_creator(
        settings, file_list, 'test', shuffle=False, data_dir=data_dir)
```
`quant_post.py`
```
import os
import sys
import logging
import paddle
import argparse
import functools
import math
import time
import numpy as np
import paddle.fluid as fluid

sys.path[0] = os.path.join(
    os.path.dirname("__file__"), os.path.pardir, os.path.pardir)
from paddleslim.common import get_logger
from paddleslim.quant import quant_post
from utility import add_arguments, print_arguments
#import imagenet_reader as reader
import reader_cv2 as reader
_logger = get_logger(__name__, level=logging.INFO)

parser = argparse.ArgumentParser(description=__doc__)
add_arg = functools.partial(add_arguments, argparser=parser)
# yapf: disable
add_arg('batch_size',       int,  4,                 "Minibatch size.")
add_arg('image_shape',      str, "3,608,608",       "Input image size")
add_arg('use_mixup',      bool,      False,        "Whether to use mixup or not")
add_arg('batch_num',       int,  5,               "Batch number")
add_arg('use_gpu',          bool, True,                "Whether to use GPU or not.")
add_arg('model_path',       str,  "./inference_model/MobileNet/",  "model dir")
add_arg('save_path',       str,  "./quant_model/MobileNet/",  "model dir to save quanted model")
add_arg('model_filename',       str, None,                 "model file name")
add_arg('params_filename',      str, None,                 "params file name")
add_arg('data_dir',       str,  "../../data/果蔬23_0910",  "data dir")
add_arg('train_list_name', str, "train_list.txt", "Train label list")
add_arg('mixup_alpha',      float,     0.2,      "Set the mixup_alpha parameter")
add_arg('l2_decay',         float, 1e-4,                 "L2_decay parameter.")
add_arg('momentum_rate',    float, 0.9,                  "momentum_rate.")
add_arg('use_label_smoothing',      bool,      False,        "Whether to use label_smoothing or not")
add_arg('label_smoothing_epsilon',      float,     0.2,      "Set the label_smoothing_epsilon parameter")
add_arg('lower_scale',      float,     0.08,      "Set the lower_scale in ramdom_crop")
add_arg('lower_ratio',      float,     3./4.,      "Set the lower_ratio in ramdom_crop")
add_arg('upper_ratio',      float,     4./3.,      "Set the upper_ratio in ramdom_crop")
# yapf: enable


def quantize(args):
    #val_reader = reader.train()
    val_reader = reader.train_yolov3(settings=args, data_dir = args.data_dir, train_list_name = args.train_list_name)

    place = fluid.CUDAPlace(0) if args.use_gpu else fluid.CPUPlace()

    assert os.path.exists(args.model_path), "args.model_path doesn't exist"
    assert os.path.isdir(args.model_path), "args.model_path must be a dir"

    exe = fluid.Executor(place)
    quant_post(
        executor=exe,
        model_dir=args.model_path,
        quantize_model_path=args.save_path,
        sample_generator=val_reader,
        model_filename=args.model_filename,
        params_filename=args.params_filename,
        batch_size=args.batch_size,
        batch_nums=args.batch_num)


def main():
    args = parser.parse_args()
    print_arguments(args)
    quantize(args)


if __name__ == '__main__':
    main()
```

`train_list.txt`
```
JPEGImages/budaodian-105.jpg Annotations/budaodian-105.xml
JPEGImages/budaodian-204.jpg Annotations/budaodian-204.xml
JPEGImages/budaodian-110.jpg Annotations/budaodian-110.xml
JPEGImages/budaodian-255.jpg Annotations/budaodian-255.xml
JPEGImages/budaodian-354.jpg Annotations/budaodian-354.xml
JPEGImages/budaodian-93.jpg Annotations/budaodian-93.xml
JPEGImages/budaodian-13.jpg Annotations/budaodian-13.xml
JPEGImages/budaodian-351.jpg Annotations/budaodian-351.xml
JPEGImages/budaodian-91.jpg Annotations/budaodian-91.xml
JPEGImages/budaodian-359.jpg Annotations/budaodian-359.xml
JPEGImages/budaodian-193.jpg Annotations/budaodian-193.xml
JPEGImages/budaodian-336.jpg Annotations/budaodian-336.xml
```

执行命令：
```
python3 quant_post.py --model_path ./yolov3/ --save_path ./quant_model_train/easydl-yolov3 --model_filename __model__ --params_filename __params__ --use_gpu false --data_dir "/home/awcloud/Desktop/paddle/PaddleSlim/demo/data/ILSVRC2012/" --image_shape "3,608,608"
```
报错信息：
```
2021-02-26 13:48:56,624-INFO: Load model and set data loader ...
2021-02-26 13:48:56,701-INFO: Collect quantized variable names ...
/usr/local/lib/python3.6/dist-packages/paddle/fluid/executor.py:1070: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "quant_post.py", line 75, in <module>
    main()
  File "quant_post.py", line 71, in main
    quantize(args)
  File "quant_post.py", line 65, in quantize
    batch_nums=args.batch_num)
  File "/usr/local/lib/python3.6/dist-packages/paddleslim/quant/quanter.py", line 331, in quant_post
    post_training_quantization.quantize()
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/contrib/slim/quantization/post_training_quantization.py", line 284, in quantize
    return_numpy=False)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.6/dist-packages/six-1.15.0-py3.6.egg/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/executor.py", line 1066, in run
    return_merged=return_merged)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/executor.py", line 1154, in _run_impl
    use_program_cache=use_program_cache)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/executor.py", line 1226, in _run_program
    self._feed_data(program, feed, feed_var_name, scope)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/executor.py", line 638, in _feed_data
    check_feed_shape_type(var, cur_feed)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/executor.py", line 225, in check_feed_shape_type
    (var.name, len(var.shape), var.shape, diff_shape))
ValueError: The fed Variable 'image' should have dimensions = 4, shape = (-1, 3, -1, -1), but received fed shape [4, 1, 3, 608, 608] on each device
```

**Comment by wanghaoshuang** [comment]
从`val_reader`读取到的数据不应该包括『batch_size』, 你可以把`img = img[np.newaxis, :]`这一句去掉试一下。

**Comment by Huihuihh** [comment]
去掉后还是同样的报错

**Comment by dium6i** [comment]
@wanghaoshuang 你好，想问一下离线量化支持检测类的模型么？根据离线量化的demo: https://github.com/PaddlePaddle/PaddleSlim/blob/develop/docs/zh_cn/quick_start/static/quant_post_static_tutorial.md 中将数据集换成自己的后，就提示报错了。或者应该怎么改一下就可以支持检测类模型了呢？

**Comment by XGZhang11** [comment]
> @wanghaoshuang 你好，想问一下离线量化支持检测类的模型么？根据离线量化的demo: https://github.com/PaddlePaddle/PaddleSlim/blob/develop/docs/zh_cn/quick_start/static/quant_post_static_tutorial.md 中将数据集换成自己的后，就提示报错了。或者应该怎么改一下就可以支持检测类模型了呢？

可以参考paddledetection相关文档：https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.7/configs/slim
