### ISSUE TITLE
直接运行教程中通道裁剪代码报错

### ISSUE THREAD

**Issue by Entromorgan** [PaddlePaddle/PaddleSlim#685]
软件版本：
Python 3.6.2
PaddlePaddle (gpu) 2.0.1
PaddleSlim 2.0.0

文档地址：
https://github.com/PaddlePaddle/PaddleSlim/blob/release/2.0.0/docs/zh_cn/quick_start/static/pruning_tutorial.md

代码：
```
import paddle
import paddle.fluid as fluid
import paddleslim as slim
paddle.enable_static()

exe, train_program, val_program, inputs, outputs = slim.models.image_classification("MobileNet", [1, 28, 28], 10, use_gpu=False)
FLOPs = slim.analysis.flops(train_program)
print("FLOPs: {}".format(FLOPs))

pruner = slim.prune.Pruner()
pruned_program, _, _ = pruner.prune(train_program, fluid.global_scope(), params=["conv2_1_sep_weights", "conv2_2_sep_weights"],ratios=[0.33] * 2, place=fluid.CPUPlace())

FLOPs = slim.analysis.flops(pruned_program)
print("FLOPs: {}".format(FLOPs))

import paddle.dataset.mnist as reader
train_reader = paddle.fluid.io.batch(reader.train(), batch_size=128, drop_last=True)
train_feeder = fluid.DataFeeder(inputs, fluid.CPUPlace())

for data in train_reader():
    acc1, acc5, loss, _ = exe.run(pruned_program, feed=train_feeder.feed(data), fetch_list=outputs)
    print(acc1, acc5, loss)
```

核心错误信息：
```
    InvalidArgumentError: The start row index must be less than the end row index.But received the start index = 0, the end index = 0.
      [Hint: Expected begin_idx < end_idx, but received begin_idx:0 >= end_idx:0.] (at D:\v2.0.1\paddle\paddle\fluid\framework\tensor.cc:120)
      [operator < depthwise_conv2d_grad > error]
```

完整错误信息：
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-86853272bf05> in <module>
      1 for data in train_reader():
----> 2     acc1, acc5, loss, _ = exe.run(pruned_program, feed=train_feeder.feed(data), fetch_list=outputs)
      3     print(acc1, acc5, loss)

d:\users\leon\miniconda3\envs\dl\lib\site-packages\paddle\fluid\executor.py in run(self, program, feed, fetch_list, feed_var_name, fetch_var_name, scope, return_numpy, use_program_cache, return_merged, use_prune)
   1108                 return_merged=return_merged)
   1109         except Exception as e:
-> 1110             six.reraise(*sys.exc_info())
   1111 
   1112     def _run_impl(self, program, feed, fetch_list, feed_var_name,

d:\users\leon\miniconda3\envs\dl\lib\site-packages\six.py in reraise(tp, value, tb)
    691             if value.__traceback__ is not tb:
    692                 raise value.with_traceback(tb)
--> 693             raise value
    694         finally:
    695             value = None

d:\users\leon\miniconda3\envs\dl\lib\site-packages\paddle\fluid\executor.py in run(self, program, feed, fetch_list, feed_var_name, fetch_var_name, scope, return_numpy, use_program_cache, return_merged, use_prune)
   1106                 use_program_cache=use_program_cache,
   1107                 use_prune=use_prune,
-> 1108                 return_merged=return_merged)
   1109         except Exception as e:
   1110             six.reraise(*sys.exc_info())

d:\users\leon\miniconda3\envs\dl\lib\site-packages\paddle\fluid\executor.py in _run_impl(self, program, feed, fetch_list, feed_var_name, fetch_var_name, scope, return_numpy, use_program_cache, return_merged, use_prune)
   1236                 scope=scope,
   1237                 return_numpy=return_numpy,
-> 1238                 use_program_cache=use_program_cache)
   1239 
   1240         program._compile(scope, self.place)

d:\users\leon\miniconda3\envs\dl\lib\site-packages\paddle\fluid\executor.py in _run_program(self, program, feed, fetch_list, feed_var_name, fetch_var_name, scope, return_numpy, use_program_cache)
   1326         if not use_program_cache:
   1327             self._default_executor.run(program.desc, scope, 0, True, True,
-> 1328                                        [fetch_var_name])
   1329         else:
   1330             self._default_executor.run_prepared_ctx(ctx, scope, False, False,

ValueError: In user code:

    File "d:\users\leon\miniconda3\envs\dl\lib\runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "d:\users\leon\miniconda3\envs\dl\lib\runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "d:\users\leon\miniconda3\envs\dl\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
      app.launch_new_instance()
    File "d:\users\leon\miniconda3\envs\dl\lib\site-packages\traitlets\config\application.py", line 664, in launch_instance
      app.start()
    File "d:\users\leon\miniconda3\envs\dl\lib\site-packages\ipykernel\kernelapp.py", line 563, in start
      self.io_loop.start()
    File "d:\users\leon\miniconda3\envs\dl\lib\site-packages\tornado\platform\asyncio.py", line 148, in start
      self.asyncio_loop.run_forever()
    File "d:\users\leon\miniconda3\envs\dl\lib\asyncio\base_events.py", line 421, in run_forever
      self._run_once()
    File "d:\users\leon\miniconda3\envs\dl\lib\asyncio\base_events.py", line 1426, in _run_once
      handle._run()
    File "d:\users\leon\miniconda3\envs\dl\lib\asyncio\events.py", line 127, in _run
      self._callback(*self._args)
    File "d:\users\leon\miniconda3\envs\dl\lib\site-packages\tornado\ioloop.py", line 690, in <lambda>
      lambda f: self._run_callback(functools.partial(callback, future))
    File "d:\users\leon\miniconda3\envs\dl\lib\site-packages\tornado\ioloop.py", line 743, in _run_callback
      ret = callback()
    File "d:\users\leon\miniconda3\envs\dl\lib\site-packages\tornado\gen.py", line 781, in inner
      self.run()
    File "d:\users\leon\miniconda3\envs\dl\lib\site-packages\tornado\gen.py", line 742, in run
      yielded = self.gen.send(value)
    File "d:\users\leon\miniconda3\envs\dl\lib\site-packages\ipykernel\kernelbase.py", line 365, in process_one
      yield gen.maybe_future(dispatch(*args))
    File "d:\users\leon\miniconda3\envs\dl\lib\site-packages\tornado\gen.py", line 209, in wrapper
      yielded = next(result)
    File "d:\users\leon\miniconda3\envs\dl\lib\site-packages\ipykernel\kernelbase.py", line 272, in dispatch_shell
      yield gen.maybe_future(handler(stream, idents, msg))
    File "d:\users\leon\miniconda3\envs\dl\lib\site-packages\tornado\gen.py", line 209, in wrapper
      yielded = next(result)
    File "d:\users\leon\miniconda3\envs\dl\lib\site-packages\ipykernel\kernelbase.py", line 542, in execute_request
      user_expressions, allow_stdin,
    File "d:\users\leon\miniconda3\envs\dl\lib\site-packages\tornado\gen.py", line 209, in wrapper
      yielded = next(result)
    File "d:\users\leon\miniconda3\envs\dl\lib\site-packages\ipykernel\ipkernel.py", line 294, in do_execute
      res = shell.run_cell(code, store_history=store_history, silent=silent)
    File "d:\users\leon\miniconda3\envs\dl\lib\site-packages\ipykernel\zmqshell.py", line 536, in run_cell
      return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
    File "d:\users\leon\miniconda3\envs\dl\lib\site-packages\IPython\core\interactiveshell.py", line 2855, in run_cell
      raw_cell, store_history, silent, shell_futures)
    File "d:\users\leon\miniconda3\envs\dl\lib\site-packages\IPython\core\interactiveshell.py", line 2881, in _run_cell
      return runner(coro)
    File "d:\users\leon\miniconda3\envs\dl\lib\site-packages\IPython\core\async_helpers.py", line 68, in _pseudo_sync_runner
      coro.send(None)
    File "d:\users\leon\miniconda3\envs\dl\lib\site-packages\IPython\core\interactiveshell.py", line 3058, in run_cell_async
      interactivity=interactivity, compiler=compiler, result=result)
    File "d:\users\leon\miniconda3\envs\dl\lib\site-packages\IPython\core\interactiveshell.py", line 3249, in run_ast_nodes
      if (await self.run_code(code, result,  async_=asy)):
    File "d:\users\leon\miniconda3\envs\dl\lib\site-packages\IPython\core\interactiveshell.py", line 3326, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "<ipython-input-2-e232f8a80cb4>", line 3, in <module>
      exe, train_program, val_program, inputs, outputs = slim.models.image_classification("MobileNet", [1, 28, 28], 10, use_gpu=False)
    File "d:\users\leon\miniconda3\envs\dl\lib\site-packages\paddleslim\models\util.py", line 19, in image_classification
      out = model.net(input=image, class_dim=class_num)
    File "d:\users\leon\miniconda3\envs\dl\lib\site-packages\paddleslim\models\mobilenet.py", line 65, in net
      name="conv3_1")
    File "d:\users\leon\miniconda3\envs\dl\lib\site-packages\paddleslim\models\mobilenet.py", line 188, in depthwise_separable
      name=name + "_dw")
    File "d:\users\leon\miniconda3\envs\dl\lib\site-packages\paddleslim\models\mobilenet.py", line 162, in conv_bn_layer
      bias_attr=False)
    File "d:\users\leon\miniconda3\envs\dl\lib\site-packages\paddle\fluid\layers\nn.py", line 1622, in conv2d
      "data_format": data_format,
    File "d:\users\leon\miniconda3\envs\dl\lib\site-packages\paddle\fluid\layer_helper.py", line 43, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "d:\users\leon\miniconda3\envs\dl\lib\site-packages\paddle\fluid\framework.py", line 3023, in append_op
      attrs=kwargs.get("attrs", None))
    File "d:\users\leon\miniconda3\envs\dl\lib\site-packages\paddle\fluid\framework.py", line 2107, in __init__
      for frame in traceback.extract_stack():

    InvalidArgumentError: The start row index must be less than the end row index.But received the start index = 0, the end index = 0.
      [Hint: Expected begin_idx < end_idx, but received begin_idx:0 >= end_idx:0.] (at D:\v2.0.1\paddle\paddle\fluid\framework\tensor.cc:120)
      [operator < depthwise_conv2d_grad > error]```

**Comment by yike725** [comment]
遇到了相同的问题

InvalidArgumentError: The start row index must be less than the end row index.But received the start index = 0, the end index = 0.
      [Hint: Expected begin_idx < end_idx, but received begin_idx:0 >= end_idx:0.] (at /paddle/paddle/fluid/framework/tensor.cc:120)
      [operator < depthwise_conv2d_grad > error]

**Comment by wanghaoshuang** [comment]
@Entromorgan @yike725 

你可以用以下命令在python libs目录下找到pruner.py文件:
```
find . -name "pruner.py"  | grep "paddleslim/prune/pruner.py"
```
然后，根据https://github.com/PaddlePaddle/PaddleSlim/pull/689 中的修复更新下本地的pruner.py文件，即可解决上述问题。

多谢您的反馈。

**Comment by Entromorgan** [comment]
好的，修正后已经能正常输出结果了，谢谢。
