### ISSUE TITLE
基于paddledetection的剪裁

### ISSUE THREAD

**Issue by guotongjian** [PaddlePaddle/PaddleSlim#688]
使用paddletection训练好的模型，使用剪裁时发现如下：
2021-03-14 16:35:02,283-INFO: sensitive - param: res2c_branch2c_weights; ratios: 0.6
2021-03-14 16:35:02,343-INFO: pruning: res2c_branch2c_weights
2021-03-14 16:35:12,415 - INFO - Test iter 0
2021-03-14 16:35:14,065 - INFO - Test finish iter 19
2021-03-14 16:35:14,065 - INFO - Total number of images: 19, inference time: 10.222864249571384 fps.
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
2021-03-14 16:35:14,068 - WARNING - The number of valid bbox detected is zero.
             Please use reasonable model and check input data.
             stop eval!
正常情况，我的test image number是147，这里显示19，而且提示bbox无效，检查数据，是什么原因呢

**Comment by V5peng** [comment]
请问您有解决吗 我也遇到了这个问题

**Comment by wanghaoshuang** [comment]
辛苦贴一下完整的脚本内容，已经PaddleDetection相关的配置文件，注意删除敏感信息。
另外，请补充下PaddlePaddle、PaddleSlim和PaddleDetection的版本号。

**Comment by guotongjian** [comment]
PaddePaddle2.0.0的，PaddleSlim直接在aistudio上pip install的应该是最新的，PaddeDetetion是2.0-release版本的。
configs文件：
```
（1）yolov3_enhance_reader.yml
TrainReader:
  inputs_def:
    fields: ['image', 'gt_bbox', 'gt_class', 'gt_score']
    num_max_boxes: 50
  use_fine_grained_loss: true
  dataset:
    !COCODataSet
    image_dir: train2017
    anno_path: annotations/instances_train2017.json
    dataset_dir: ../../data/coco
    with_background: false
  sample_transforms:
    - !DecodeImage
      to_rgb: True
    - !RandomCrop {}
    - !RandomFlipImage
      is_normalized: false
    - !NormalizeBox {}
    - !PadBox
      num_max_boxes: 50
    - !BboxXYXY2XYWH {}
  batch_transforms:
    - !RandomShape
      sizes: [320, 352, 384, 416, 448, 480, 512, 544, 576, 608]
      random_inter: True
    - !NormalizeImage
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
      is_scale: False
      is_channel_first: false
    - !Permute
      to_bgr: false
      channel_first: True
    # Gt2YoloTarget is only used when use_fine_grained_loss set as true,
    # this operator will be deleted automatically if use_fine_grained_loss
    # is set as false
    - !Gt2YoloTarget
      anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]]
      anchors: [[10, 13], [16, 30], [33, 23],
                [30, 61], [62, 45], [59, 119],
                [116, 90], [156, 198], [373, 326]]
      downsample_ratios: [32, 16, 8]
  batch_size: 8
  shuffle: true
  drop_last: true
  worker_num: 8
  bufsize: 16
  use_process: true

EvalReader:
  inputs_def:
    image_shape: [3, 608, 608]
    fields: ['image', 'im_size', 'im_id']
    num_max_boxes: 50
  dataset:
    !COCODataSet
    dataset_dir: ../../data/coco
    anno_path: annotations/instances_val2017.json
    image_dir: val2017
    with_background: false
  sample_transforms:
    - !DecodeImage
      to_rgb: True
      with_mixup: false
    - !ResizeImage
      interp: 2
      target_size: 608
    - !NormalizeImage
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
      is_scale: False
      is_channel_first: false
    - !PadBox
      num_max_boxes: 50
    - !Permute
      to_bgr: false
      channel_first: True
  batch_size: 8
  drop_empty: false
  worker_num: 8
  bufsize: 16

TestReader:
  inputs_def:
    image_shape: [3, 608, 608]
    fields: ['image', 'im_size', 'im_id']
  dataset:
    !ImageFolder
      anno_path: ../../data/coco/annotations/instances_test2017.json
      with_background: false
  sample_transforms:
    - !DecodeImage
      to_rgb: True
      with_mixup: false
    - !ResizeImage
      interp: 2
      target_size: 608
    - !NormalizeImage
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
      is_scale: False
      is_channel_first: false
    - !Permute
      to_bgr: false
      channel_first: True
  batch_size: 1
```
```
architecture: YOLOv3
use_gpu: true
max_iters: 65850
log_iter: 20
save_dir: output
snapshot_iter: 1000
metric: COCO
pretrain_weights: https://paddlemodels.bj.bcebos.com/object_detection/ResNet50_vd_dcn_db_obj365_pretrained.tar
weights: ../../output/mymodel/best_model
num_classes: 4
use_fine_grained_loss: true

YOLOv3:
  backbone: ResNet
  yolo_head: YOLOv3Head
  use_fine_grained_loss: true
  
ResNet:
  norm_type: bn
  freeze_at: 0
  freeze_norm: false
  norm_decay: 0.
  depth: 50
  feature_maps: [3, 4, 5]
  variant: d
  dcn_v2_stages: [5]

YOLOv3Head:
  anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]]
  anchors: [[10, 13], [16, 30], [33, 23],
            [30, 61], [62, 45], [59, 119],
            [116, 90], [156, 198], [373, 326]]
  norm_decay: 0.
  yolo_loss: YOLOv3Loss
  nms:
    background_label: -1
    keep_top_k: 100
    nms_threshold: 0.45
    nms_top_k: 1000
    normalized: false
    score_threshold: 0.01

YOLOv3Loss:
  ignore_thresh: 0.7
  label_smooth: false
  use_fine_grained_loss: true
  iou_loss: IouLoss
  
IouLoss:
  loss_weight: 2.5
  max_height: 608
  max_width: 608

LearningRate:
  base_lr: 0.000125
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones:
    - 43333
    - 59090
  - !LinearWarmup
    start_factor: 0.
    steps: 4000

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0005
    type: L2

_READER_: 'yolov3_enhance_reader.yml'
```
```
2021-03-14 16:35:02,283-INFO: sensitive - param: res2c_branch2c_weights; ratios: 0.6
2021-03-14 16:35:02,343-INFO: pruning: res2c_branch2c_weights
2021-03-14 16:35:12,415 - INFO - Test iter 0
2021-03-14 16:35:14,065 - INFO - Test finish iter 19
2021-03-14 16:35:14,065 - INFO - Total number of images: 19, inference time: 10.222864249571384 fps.
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
2021-03-14 16:35:14,068 - WARNING - The number of valid bbox detected is zero.
Please use reasonable model and check input data.
stop eval!
```
这个问题是在按ratios从0.1到0.9做敏感度分析时出现的，在整个分析过程中，剪裁别的层或者在别的ratio下有时候是正常的没有问题，显示的测试图片数量也是147，只是在有的层和有的ratio下会出现这种情况。
```
2021-03-14 20:48:15,801-INFO: pruning: res4f_branch2b_weights
2021-03-14 20:48:17,121-INFO: pruning: res5a_branch2a_weights
2021-03-14 20:48:19,659-INFO: pruning: res5a_branch2b_conv_offset.w_0
2021-03-14 20:48:20,711-INFO: pruning: res5a_branch2b_conv_offset.b_0
2021-03-14 20:48:20,747-INFO: pruning: res5a_branch2b_weights
2021-03-14 20:48:20,781-INFO: No walker for operator: deformable_conv
2021-03-14 20:48:20,781-INFO: pruning: res5b_branch2a_weights
2021-03-14 20:48:23,262-INFO: pruning: res5b_branch2b_conv_offset.w_0
2021-03-14 20:48:24,298-INFO: pruning: res5b_branch2b_conv_offset.b_0
2021-03-14 20:48:24,333-INFO: pruning: res5b_branch2b_weights
2021-03-14 20:48:24,370-INFO: No walker for operator: deformable_conv
2021-03-14 20:48:24,370-INFO: pruning: res5c_branch2a_weights
2021-03-14 20:48:26,850-INFO: pruning: res5c_branch2b_conv_offset.w_0
2021-03-14 20:48:27,893-INFO: pruning: res5c_branch2b_conv_offset.b_0
2021-03-14 20:48:27,929-INFO: pruning: res5c_branch2b_weights
2021-03-14 20:48:27,964-INFO: No walker for operator: deformable_conv
2021-03-14 20:48:27,964-INFO: pruning: yolo_block.0.0.1.conv.weights
2021-03-14 20:48:29,309-INFO: pruning: yolo_block.0.1.0.conv.weights
2021-03-14 20:48:30,775-INFO: pruning: yolo_block.0.1.1.conv.weights
2021-03-14 20:48:32,186-INFO: pruning: yolo_block.0.2.conv.weights
2021-03-14 20:48:33,948-INFO: pruning: yolo_transition.0.conv.weights
2021-03-14 20:48:35,416-INFO: pruning: yolo_block.1.0.1.conv.weights
2021-03-14 20:48:36,922-INFO: pruning: yolo_block.1.1.0.conv.weights
2021-03-14 20:48:38,219-INFO: pruning: yolo_block.1.1.1.conv.weights
2021-03-14 20:48:39,617-INFO: pruning: yolo_block.1.2.conv.weights
2021-03-14 20:48:41,315-INFO: pruning: yolo_block.1.tip.conv.weights
2021-03-14 20:48:42,789-INFO: pruning: yolo_transition.1.conv.weights
2021-03-14 20:48:44,290-INFO: pruning: yolo_block.2.0.1.conv.weights
2021-03-14 20:48:45,736-INFO: pruning: yolo_block.2.2.conv.weights
2021-03-14 20:48:47,143-INFO: pruning: yolo_block.2.tip.conv.weights
2021-03-14 20:48:48,538-INFO: pruning: yolo_output.2.conv.weights
Traceback (most recent call last):
  File "slim/prune/prune.py", line 415, in <module>
    main()
  File "slim/prune/prune.py", line 199, in main
    only_graph=False)[0]
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/pruner.py", line 98, in prune
    visited)[0]  # [(name, axis, pruned_idx)]
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/group_param.py", line 87, in collect_convs
    walker.prune(param, pruned_axis=0, pruned_idx=[])
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 55, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 161, in _prune
    self._prune_op(op, output_var, channel_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 101, in _prune_op
    walker.prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 55, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 316, in _prune
    self._visit_and_search(out_var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 75, in _visit_and_search
    self._prune_op(op, var, axis, transforms)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 101, in _prune_op
    walker.prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 55, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 365, in _prune
    self._visit_and_search(out_var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 75, in _visit_and_search
    self._prune_op(op, var, axis, transforms)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 101, in _prune_op
    walker.prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 55, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 365, in _prune
    self._visit_and_search(out_var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 75, in _visit_and_search
    self._prune_op(op, var, axis, transforms)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 101, in _prune_op
    walker.prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 55, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 306, in _prune
    self._visit_and_search(in_var, y_pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 72, in _visit_and_search
    self._prune_op(op, var, axis, transforms)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 101, in _prune_op
    walker.prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 55, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 290, in _prune
    self._visit_and_search(in_var, actual_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 72, in _visit_and_search
    self._prune_op(op, var, axis, transforms)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 101, in _prune_op
    walker.prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 55, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 365, in _prune
    self._visit_and_search(out_var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 75, in _visit_and_search
    self._prune_op(op, var, axis, transforms)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 101, in _prune_op
    walker.prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 55, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 365, in _prune
    self._visit_and_search(out_var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 75, in _visit_and_search
    self._prune_op(op, var, axis, transforms)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 101, in _prune_op
    walker.prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 55, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 365, in _prune
    self._visit_and_search(out_var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 75, in _visit_and_search
    self._prune_op(op, var, axis, transforms)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 101, in _prune_op
    walker.prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 55, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 365, in _prune
    self._visit_and_search(out_var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 75, in _visit_and_search
    self._prune_op(op, var, axis, transforms)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 101, in _prune_op
    walker.prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 55, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 306, in _prune
    self._visit_and_search(in_var, y_pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 75, in _visit_and_search
    self._prune_op(op, var, axis, transforms)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 101, in _prune_op
    walker.prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 55, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 313, in _prune
    self._visit_and_search(in_var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 72, in _visit_and_search
    self._prune_op(op, var, axis, transforms)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 101, in _prune_op
    walker.prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 55, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 362, in _prune
    self._visit_and_search(in_var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 72, in _visit_and_search
    self._prune_op(op, var, axis, transforms)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 101, in _prune_op
    walker.prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 55, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 362, in _prune
    self._visit_and_search(in_var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 72, in _visit_and_search
    self._prune_op(op, var, axis, transforms)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 101, in _prune_op
    walker.prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 55, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 362, in _prune
    self._visit_and_search(in_var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 72, in _visit_and_search
    self._prune_op(op, var, axis, transforms)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 101, in _prune_op
    walker.prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 55, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 361, in _prune
    if len(in_var.shape()) == len(var.shape()):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/core/graph_wrapper.py", line 64, in shape
    return self._var.shape
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 1561, in shape
    return tuple(self.desc.shape())
RuntimeError: (Unavailable) Getting 'tensor_desc' is not supported by the double_buffer_0 type variable. (at /paddle/paddle/fluid/framework/var_desc.cc:213)
```
在第一个问题的基础上继续执行官方教程，计算敏感度后进行prune，又出现如上的报错，请问是不是不支持dcn的剪裁，我看官方有给过res50vd-dcn的剪裁过的.tar权重文件，请问那个是只剪裁了yolo层吗。

**Comment by guotongjian** [comment]
@wanghaoshuang 感谢大佬回答，不胜感激

**Comment by V5peng** [comment]
我跟楼主用的.yml是一样的，不过我是在模型量化的时候遇到的这个问题，剪裁训练没有遇到问题
python   3.6.13
paddlepaddle-gpu    1.8.4.post107
paddleslim          1.2.0
paddleDetection   release/2.0-beta

执行命令：python slim/quantization/train.py     --eval     -c ./configs/yolov3_r34_dcn.yml     -o max_iters=30000     save_dir=./output/yolov3     LearningRate.base_lr=0.0001     LearningRate.schedulers="[!PiecewiseDecay {gamma: 0.1, milestones: [10000]}]"     pretrain_weights=https://paddle-imagenet-models-name.bj.bcebos.com/ResNet34_vd_pretrained.tar    --use_pact=True

量化的时候在--eval阶段：
2021-03-15 15:38:21,152-INFO: Test iter 0
2021-03-15 15:38:29,659-INFO: Test iter 100
2021-03-15 15:38:37,615-INFO: Test iter 200
2021-03-15 15:38:45,650-INFO: Test iter 300
2021-03-15 15:38:53,636-INFO: Test iter 400
Corrupt JPEG data: premature end of data segment
2021-03-15 15:39:01,587-INFO: Test iter 500
2021-03-15 15:39:09,470-INFO: Test iter 600
2021-03-15 15:39:17,586-INFO: Test iter 700
2021-03-15 15:39:25,449-INFO: Test iter 800
2021-03-15 15:39:33,358-INFO: Test iter 900
2021-03-15 15:39:38,012-INFO: Test finish iter 959
2021-03-15 15:39:38,013-INFO: Total number of images: 959, inference time: 12.452998707541694 fps.
loading annotations into memory...
Done (t=0.05s)
creating index...
index created!
2021-03-15 15:39:38,080-WARNING: The number of valid bbox detected is zero.
             Please use reasonable model and check input data.
             stop eval!

**Comment by wanghaoshuang** [comment]
@guotongjian 您好，我在跟进这个问题，请问这个issue为什么被closed了？是问题已经解决了么？

**Comment by guotongjian** [comment]
> @guotongjian 您好，我在跟进这个问题，请问这个issue为什么被closed了？是问题已经解决了么？

不好意思，看您没回复，我在paddledetection上也提了这个issue，我就关了一个

**Comment by wanghaoshuang** [comment]
@guotongjian 方便把paddledetection上issue链接贴过来么？我也看下这个问题。

**Comment by guotongjian** [comment]
> @guotongjian 方便把paddledetection上issue链接贴过来么？我也看下这个问题。

https://github.com/PaddlePaddle/PaddleDetection/issues/2345
