### ISSUE TITLE
slimfacenet训练报错

### ISSUE THREAD

**Issue by yangy996** [PaddlePaddle/PaddleSlim#694]
PaddlePaddle版本：2.0.1
数据集：CASIA和LFW

报错如下：
Traceback (most recent call last):
  File "train_eval.py", line 389, in <module>
    main()
  File "train_eval.py", line 335, in main
    train(exe, train_program, train_out, test_program, test_out, args)
  File "train_eval.py", line 127, in train
    loss, acc, global_lr = exe.run(compiled_prog,
  File "/home/su/PycharmProjects/SlimFaceNet/venv/lib/python3.8/site-packages/paddle/fluid/executor.py", line 1110, in run
    six.reraise(*sys.exc_info())
  File "/home/su/PycharmProjects/SlimFaceNet/venv/lib/python3.8/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/su/PycharmProjects/SlimFaceNet/venv/lib/python3.8/site-packages/paddle/fluid/executor.py", line 1098, in run
    return self._run_impl(
  File "/home/su/PycharmProjects/SlimFaceNet/venv/lib/python3.8/site-packages/paddle/fluid/executor.py", line 1244, in _run_impl
    return self._run_parallel(
  File "/home/su/PycharmProjects/SlimFaceNet/venv/lib/python3.8/site-packages/paddle/fluid/executor.py", line 913, in _run_parallel
    tensors = exe.run(fetch_var_names, return_merged)._move_to_list()
ValueError: In user code:

    File "train_eval.py", line 389, in <module>
      main()
    File "train_eval.py", line 327, in main
      train_out = build_program(train_program, startup_program, args, True)
    File "train_eval.py", line 186, in build_program
      loss, acc = model.net(image, label)
    File "/home/su/PycharmProjects/SlimFaceNet/SlimFaceNet/models/slimfacenet.py", line 176, in net
      cost = fluid.layers.cross_entropy(input=softmax, label=label)
    File "/home/su/PycharmProjects/SlimFaceNet/venv/lib/python3.8/site-packages/paddle/fluid/layers/loss.py", line 260, in cross_entropy
      return cross_entropy2(input, label, ignore_index)
    File "/home/su/PycharmProjects/SlimFaceNet/venv/lib/python3.8/site-packages/paddle/fluid/layers/loss.py", line 292, in cross_entropy2
      helper.append_op(
    File "/home/su/PycharmProjects/SlimFaceNet/venv/lib/python3.8/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/home/su/PycharmProjects/SlimFaceNet/venv/lib/python3.8/site-packages/paddle/fluid/framework.py", line 3017, in append_op
      op = Operator(
    File "/home/su/PycharmProjects/SlimFaceNet/venv/lib/python3.8/site-packages/paddle/fluid/framework.py", line 2107, in __init__
      for frame in traceback.extract_stack():

    InvalidArgumentError: Input(X) and Input(Label) shall have the same shape except the last dimension. But received: the shape of Input(X) is [64, 64, 10572], the shape of Input(Label) is [64, 1].
      [Hint: Expected framework::slice_ddim(x_dims, 0, rank - 1) == framework::slice_ddim(label_dims, 0, rank - 1), but received framework::slice_ddim(x_dims, 0, rank - 1):64, 64 != framework::slice_ddim(label_dims, 0, rank - 1):64, 1.] (at /paddle/paddle/fluid/operators/cross_entropy_op.cc:49)
      [operator < cross_entropy2 > error]

**Comment by yangy996** [comment]
> PaddlePaddle版本：2.0.1
> 数据集：CASIA和LFW
> 
> 报错如下：
> Traceback (most recent call last):
> File "train_eval.py", line 389, in
> main()
> File "train_eval.py", line 335, in main
> train(exe, train_program, train_out, test_program, test_out, args)
> File "train_eval.py", line 127, in train
> loss, acc, global_lr = exe.run(compiled_prog,
> File "/home/su/PycharmProjects/SlimFaceNet/venv/lib/python3.8/site-packages/paddle/fluid/executor.py", line 1110, in run
> six.reraise(*sys.exc_info())
> File "/home/su/PycharmProjects/SlimFaceNet/venv/lib/python3.8/site-packages/six.py", line 703, in reraise
> raise value
> File "/home/su/PycharmProjects/SlimFaceNet/venv/lib/python3.8/site-packages/paddle/fluid/executor.py", line 1098, in run
> return self._run_impl(
> File "/home/su/PycharmProjects/SlimFaceNet/venv/lib/python3.8/site-packages/paddle/fluid/executor.py", line 1244, in _run_impl
> return self._run_parallel(
> File "/home/su/PycharmProjects/SlimFaceNet/venv/lib/python3.8/site-packages/paddle/fluid/executor.py", line 913, in _run_parallel
> tensors = exe.run(fetch_var_names, return_merged)._move_to_list()
> ValueError: In user code:
> 
> ```
> File "train_eval.py", line 389, in <module>
>   main()
> File "train_eval.py", line 327, in main
>   train_out = build_program(train_program, startup_program, args, True)
> File "train_eval.py", line 186, in build_program
>   loss, acc = model.net(image, label)
> File "/home/su/PycharmProjects/SlimFaceNet/SlimFaceNet/models/slimfacenet.py", line 176, in net
>   cost = fluid.layers.cross_entropy(input=softmax, label=label)
> File "/home/su/PycharmProjects/SlimFaceNet/venv/lib/python3.8/site-packages/paddle/fluid/layers/loss.py", line 260, in cross_entropy
>   return cross_entropy2(input, label, ignore_index)
> File "/home/su/PycharmProjects/SlimFaceNet/venv/lib/python3.8/site-packages/paddle/fluid/layers/loss.py", line 292, in cross_entropy2
>   helper.append_op(
> File "/home/su/PycharmProjects/SlimFaceNet/venv/lib/python3.8/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
>   return self.main_program.current_block().append_op(*args, **kwargs)
> File "/home/su/PycharmProjects/SlimFaceNet/venv/lib/python3.8/site-packages/paddle/fluid/framework.py", line 3017, in append_op
>   op = Operator(
> File "/home/su/PycharmProjects/SlimFaceNet/venv/lib/python3.8/site-packages/paddle/fluid/framework.py", line 2107, in __init__
>   for frame in traceback.extract_stack():
> 
> InvalidArgumentError: Input(X) and Input(Label) shall have the same shape except the last dimension. But received: the shape of Input(X) is [64, 64, 10572], the shape of Input(Label) is [64, 1].
>   [Hint: Expected framework::slice_ddim(x_dims, 0, rank - 1) == framework::slice_ddim(label_dims, 0, rank - 1), but received framework::slice_ddim(x_dims, 0, rank - 1):64, 64 != framework::slice_ddim(label_dims, 0, rank - 1):64, 1.] (at /paddle/paddle/fluid/operators/cross_entropy_op.cc:49)
>   [operator < cross_entropy2 > error]
> ```

将one_hot = fluid.one_hot(input=label, depth=out_dim)改成one_hot = fluid.layers.one_hot(input=label, depth=out_dim)就好了，不过又遇到新的问题，报错如下：
Traceback (most recent call last):
  File "train_eval.py", line 390, in <module>
    main()
  File "train_eval.py", line 336, in main
    train(exe, train_program, train_out, test_program, test_out, args)
  File "train_eval.py", line 141, in train
    temp_ave = test(exe, test_program, test_out, args)
  File "train_eval.py", line 102, in test
    ACCs = evaluation_10_fold(args.feature_save_dir)
  File "/home/su/PycharmProjects/SlimFaceNet/SlimFaceNet/lfw_eval.py", line 91, in evaluation_10_fold
    (featureLs[valFold[0], :], featureRs[valFold[0], :]), 0), 0)
IndexError: boolean index did not match indexed array along dimension 0; dimension is 800 but corresponding boolean dimension is 6000

**Comment by scott-mao** [comment]
请问此问题解决了吗？我也遇到这个问题，还有fluid.one_hot，您在哪个地方修改的，没找到这个地方，我训练slimface也出现和你一样的错误

**Comment by scott-mao** [comment]
我的paddlepaddle 2.1.3版本
