### ISSUE TITLE
敏感度分析训练时报错

### ISSUE THREAD

**Issue by Durianner** [PaddlePaddle/PaddleSlim#739]
paddlepaddle-gpu 2.0.0.post100
paddleslim 2.0.0
想对一个目标检测模型剪枝，执行完敏感度分析后，在分析训练时报错
  File "deploy/slim/prune/sensitivity_anal.py", line 146, in <module>
    main(config, device, logger, vdl_writer)
  File "deploy/slim/prune/sensitivity_anal.py", line 141, in main
    eval_class, pre_best_model_dict, logger, vdl_writer)
  File "deploy/slim/prune/../../../tools/program.py", line 214, in train
    optimizer.step()
  File "<decorator-gen-198>", line 2, in step
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/base.py", line 260, in __impl__
    return func(*args, **kwargs)
  File "<decorator-gen-196>", line 2, in step
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 225, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/optimizer/adam.py", line 367, in step
    loss=None, startup_program=None, params_grads=params_grads)
  File "/usr/local/lib/python3.7/dist-packages/paddle/optimizer/optimizer.py", line 775, in _apply_optimize
    optimize_ops = self._create_optimization_pass(params_grads)
  File "/usr/local/lib/python3.7/dist-packages/paddle/optimizer/optimizer.py", line 597, in _create_optimization_pass
    [p[0] for p in parameters_and_grads if p[0].trainable])
  File "/usr/local/lib/python3.7/dist-packages/paddle/optimizer/adam.py", line 249, in _create_accumulators
    self._add_moments_pows(p)
  File "/usr/local/lib/python3.7/dist-packages/paddle/optimizer/adam.py", line 216, in _add_moments_pows
    self._add_accumulator(self._moment1_acc_str, p, dtype=acc_dtype)
  File "/usr/local/lib/python3.7/dist-packages/paddle/optimizer/optimizer.py", line 516, in _add_accumulator
    var.set_value(self._accumulators_holder[var_name])
  File "<decorator-gen-113>", line 2, in set_value
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 225, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 125, in set_value
    self.name, self_tensor_np.shape, value_np.shape)
AssertionError: Variable Shape not match, Variable [ conv2_expand_weights_moment1_0 ] need tensor with shape (7, 8, 1, 1) but load set tensor with shape (8, 8, 1, 1)

**Comment by Zhang-O** [comment]
我也报错了，命令是：
python -u /data/zhangyl/PaddleOCR_v2.1/deploy/slim/prune/sensitivity_anal.py -c rec_chinese_lite_train_v2.0_origin.yml -o Global.pretrained_model=rec_CRNN_2.1/best_accuracy Global.save_model_dir=rec_CRNN_2.1/prune_model

错误是：
[2021/08/26 08:40:06] root INFO: metric['acc']: 0.38350265017667845
2021-08-26 08:40:06,508-INFO: pruned param: conv2_se_1_weights; 0.7; loss=0.13456267131821575
2021-08-26 08:40:06,509-INFO: Save status into ./sen.pickle
2021-08-26 08:40:06,513-INFO: Pruning variable [conv2_se_1_weights] and its relatives ['conv2_se_1_weights', 'conv2_se_1_offset', 'conv2_se_2_weights']
eval model::   0%|                                      | 0/283 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/data/zhangyl/PaddleOCR_v2.1/deploy/slim/prune/sensitivity_anal.py", line 146, in <module>
    main(config, device, logger, vdl_writer)
  File "/data/zhangyl/PaddleOCR_v2.1/deploy/slim/prune/sensitivity_anal.py", line 116, in main
    skip_vars=[
  File "/data/tools/anaconda3/envs/paddle/lib/python3.7/site-packages/paddleslim-2.1.1-py3.7.egg/paddleslim/dygraph/prune/filter_pruner.py", line 129, in sensitive
  File "/data/tools/anaconda3/envs/paddle/lib/python3.7/site-packages/paddleslim-2.1.1-py3.7.egg/paddleslim/dygraph/prune/filter_pruner.py", line 267, in _cal_sensitive
  File "/data/zhangyl/PaddleOCR_v2.1/deploy/slim/prune/sensitivity_anal.py", line 109, in eval_fn
    eval_class)
  File "/data/zhangyl/PaddleOCR_v2.1/tools/program.py", line 359, in eval
    preds = model(images)
  File "/data/tools/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/data/zhangyl/PaddleOCR_v2.1/ppocr/modeling/architectures/base_model.py", line 74, in forward
    x = self.backbone(x)
  File "/data/tools/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/data/zhangyl/PaddleOCR_v2.1/ppocr/modeling/backbones/rec_mobilenet_v3.py", line 135, in forward
    x = self.blocks(x)
  File "/data/tools/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/data/tools/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/container.py", line 98, in forward
    input = layer(input)
  File "/data/tools/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/data/zhangyl/PaddleOCR_v2.1/ppocr/modeling/backbones/det_mobilenet_v3.py", line 253, in forward
    x = self.mid_se(x)
  File "/data/tools/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/data/zhangyl/PaddleOCR_v2.1/ppocr/modeling/backbones/det_mobilenet_v3.py", line 283, in forward
    outputs = self.conv1(outputs)
  File "/data/tools/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/data/tools/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/nn/layer/conv.py", line 667, in forward
    use_cudnn=self._use_cudnn)
  File "/data/tools/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/nn/functional/conv.py", line 114, in _conv_nd
    pre_bias = getattr(core.ops, op_type)(x, weight, *attrs)
OSError: (External)  Cudnn error, CUDNN_STATUS_BAD_PARAM  (at /paddle/paddle/fluid/platform/cudnn_desc.h:203)
  [operator < conv2d > error]
eval model::   0%|                                      | 0/283 [00:00<?, ?it/s]
