### ISSUE TITLE
量化paddleocr 自带的识别模型报错

### ISSUE THREAD

**Issue by wings0820** [PaddlePaddle/PaddleSlim#796]
报错如下
Traceback (most recent call last):
Exception in thread Thread-1:
  File "tools/quan.py", line 50, in <module>
Traceback (most recent call last):
  File "/home/jianguosun/.conda/envs/ppocr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    main(config, device, logger, vdl_writer)
  File "tools/quan.py", line 37, in main
    paddleslim.quant.quant_post_static(
  File "/home/jianguosun/.local/lib/python3.8/site-packages/paddleslim/quant/quanter.py", line 417, in quant_post_static
    self.run()
  File "/home/jianguosun/.conda/envs/ppocr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jianguosun/.conda/envs/ppocr/lib/python3.8/site-packages/paddle/fluid/reader.py", line 1295, in __thread_main__
    post_training_quantization.quantize()
  File "/home/jianguosun/.conda/envs/ppocr/lib/python3.8/site-packages/paddle/fluid/contrib/slim/quantization/post_training_quantization.py", line 365, in quantize
    for data in self._data_loader():
  File "/home/jianguosun/.conda/envs/ppocr/lib/python3.8/site-packages/paddle/fluid/reader.py", line 1251, in __next__
    six.reraise(*sys.exc_info())
  File "/home/jianguosun/.conda/envs/ppocr/lib/python3.8/site-packages/six.py", line 703, in reraise
    return self._reader.read_next()
    raise value
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:166)
  File "/home/jianguosun/.conda/envs/ppocr/lib/python3.8/site-packages/paddle/fluid/reader.py", line 1275, in __thread_main__

    for tensors in self._tensor_reader():
  File "/home/jianguosun/.conda/envs/ppocr/lib/python3.8/site-packages/paddle/fluid/data_feeder.py", line 241, in __call__
    for each_sample in self.generator():
  File "tools/quan.py", line 24, in __reader__
    for indx, data in enumerate(loader):
  File "/home/jianguosun/.conda/envs/ppocr/lib/python3.8/site-packages/paddle/fluid/reader.py", line 426, in __iter__
    return _DataLoaderIterMultiProcess(self)
  File "/home/jianguosun/.conda/envs/ppocr/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 283, in __init__
    self._init_workers()
  File "/home/jianguosun/.conda/envs/ppocr/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 332, in _init_workers
    _set_SIGCHLD_handler()
  File "/home/jianguosun/.conda/envs/ppocr/lib/python3.8/site-packages/paddle/fluid/multiprocess_utils.py", line 142, in _set_SIGCHLD_handler
    signal.signal(signal.SIGCHLD, __handler__)
  File "/home/jianguosun/.conda/envs/ppocr/lib/python3.8/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
Exception ignored in: <function _DataLoaderIterMultiProcess.__del__ at 0x7f2a1cc343a0>
Traceback (most recent call last):
  File "/home/jianguosun/.conda/envs/ppocr/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 566, in __del__
    self._try_shutdown_all()
  File "/home/jianguosun/.conda/envs/ppocr/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 371, in _try_shutdown_all
    if not self._shutdown:
AttributeError: '_DataLoaderIterMultiProcess' object has no attribute '_shutdown'
-----------------------------------------------------------------------------
paddlepaddle 2.1.0.post101
paddleslim 2.1.0

quant.py 代码如下

      def sample_generator(loader):
            def __reader__():
                  for indx, data in enumerate(loader):
                       images = np.array(data[0])
                       yield images
             return __reader__

    def main(config, device, logger, vdl_writer):
          loader = build_dataloader(config, 'Train', device, logger)
          paddle.enable_static()
          place = paddle.CPUPlace()
          exe = paddle.static.Executor(place)
          model_dir = 'ch_ppocr_server_v2.0_rec_infer/'

          paddleslim.quant.quant_post_static(
                  executor=exe,
                  model_dir=model_dir,
                  model_filename='inference.pdmodel',
                  params_filename='inference.pdiparams',
                  quantize_model_path='quant_post_static_model',
                  sample_generator=sample_generator(loader),
                  batch_size=64,
                  batch_nums=10)

    if __name__ == '__main__':
          config, device, logger, vdl_writer = program.preprocess(is_train=True)
          main(config, device, logger, vdl_writer)

官方的教程里只有cifar集成包接口，还只是图像分类的，能提供一下自定义的reader的写法，和格式嘛

**Comment by XGZhang11** [comment]
您好，目前离线量化只支持静态图模型，一般需要静态图模式下的dataloader，另外需要注意reader所提供数据应该与inference model的输入对应。reader的写法可以参照https://github.com/PaddlePaddle/PaddleSlim/blob/release/2.1.0/demo/imagenet_reader.py 与 https://github.com/PaddlePaddle/PaddleSlim/issues/719 .
对于多输入的模型，可以参考：
```
def batch_generator(val_loader):
    def __reader__():
        for indx, data in enumerate(val_loader()):
            images = np.array([img[0] for img in data])
            im_size = np.array([img[1] for img in data])
            yield images, im_size
    return __reader__
```
并将batch_generator指定为
```
batch_generator=batch_generator(val_loader)
```

**Comment by LiquorPerfect** [comment]
您好，AttributeError: '_DataLoaderIterMultiProcess' object has no attribute '_shutdown'这个报错问题，您解决了嘛，我按照上述方法还是不行。
