### ISSUE TITLE
知识蒸馏demo遇到问题

### ISSUE THREAD

**Issue by yezechen** [PaddlePaddle/PaddleSlim#804]
运行图像分类模型知识蒸馏的demo时遇到报错：

Traceback (most recent call last):
  File "distiller.py", line 71, in <module>
    acc1, acc5, loss_np = exe.run(student_program, feed=data, fetch_list=[acc_top1.name, acc_top5.name, loss.name])
  File "/home/server1604-1/anaconda3/envs/yzc/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1110, in run
    six.reraise(*sys.exc_info())
  File "/home/server1604-1/anaconda3/envs/yzc/lib/python3.6/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/server1604-1/anaconda3/envs/yzc/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1108, in run
    return_merged=return_merged)
  File "/home/server1604-1/anaconda3/envs/yzc/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1239, in _run_impl
    use_program_cache=use_program_cache)
  File "/home/server1604-1/anaconda3/envs/yzc/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1329, in _run_program
    [fetch_var_name])
IndexError: In user code:

    File "distiller.py", line 16, in <module>
      cost = paddle.nn.functional.cross_entropy(input=out, label=gt)
    File "/home/server1604-1/anaconda3/envs/yzc/lib/python3.6/site-packages/paddle/nn/functional/loss.py", line 1492, in cross_entropy
      attrs=attrs)
    File "/home/server1604-1/anaconda3/envs/yzc/lib/python3.6/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/home/server1604-1/anaconda3/envs/yzc/lib/python3.6/site-packages/paddle/fluid/framework.py", line 3232, in append_op
      attrs=kwargs.get("attrs", None))
    File "/home/server1604-1/anaconda3/envs/yzc/lib/python3.6/site-packages/paddle/fluid/framework.py", line 2312, in __init__
      for frame in traceback.extract_stack():

    OutOfRangeError: label value should less than the shape of axis dimension when label value(25) not equal to ignore_index(-100), But received label value as 25 and shape of axis dimension is 10
      [Hint: Expected lbl < axis_dim, but received lbl:25 >= axis_dim:10.] (at /paddle/paddle/fluid/operators/math/cross_entropy.cc:75)
      [operator < softmax_with_cross_entropy > error]

**Comment by ceci3** [comment]
你好，可以发一下demo链接吗？看起来是输出logits维度和label维度不匹配
