### ISSUE TITLE
yolov5检测模型离线静态量化失败

### ISSUE THREAD

**Issue by youngstu** [PaddlePaddle/PaddleSlim#875]
```
2021-08-11 21:11:37,106-INFO: Load model and set data loader ...
W0811 21:11:37.140259 30871 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 10.2, Runtime API Version: 10.2
W0811 21:11:37.142552 30871 device_context.cc:422] device: 0, cuDNN Version: 7.6.
2021-08-11 21:11:38,439-INFO: Collect quantized variable names ...
2021-08-11 21:11:38,442-INFO: Preparation stage ...
Traceback (most recent call last):
  File "quant_post.py", line 69, in <module>
    main()
  File "quant_post.py", line 64, in main
    quantize()
  File "quant_post.py", line 50, in quantize
    bias_correction=bias_correction)
  File "/home/ar/shaoxiong/envs/anaconda3/envs/py36_paddle2.1/lib/python3.6/site-packages/paddleslim/quant/quanter.py", line 417, in quant_post_static
    post_training_quantization.quantize()
  File "/home/ar/shaoxiong/envs/anaconda3/envs/py36_paddle2.1/lib/python3.6/site-packages/paddle/fluid/contrib/slim/quantization/post_training_quantization.py", line 370, in quantize
    scope=self._scope)
  File "/home/ar/shaoxiong/envs/anaconda3/envs/py36_paddle2.1/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1110, in run
    six.reraise(*sys.exc_info())
  File "/home/ar/shaoxiong/envs/anaconda3/envs/py36_paddle2.1/lib/python3.6/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/ar/shaoxiong/envs/anaconda3/envs/py36_paddle2.1/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1108, in run
    return_merged=return_merged)
  File "/home/ar/shaoxiong/envs/anaconda3/envs/py36_paddle2.1/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1239, in _run_impl
    use_program_cache=use_program_cache)
  File "/home/ar/shaoxiong/envs/anaconda3/envs/py36_paddle2.1/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1329, in _run_program
    [fetch_var_name])
ValueError: In user code:

    File "/home/ar/shaoxiong/envs/anaconda3/envs/py38_pytorch1.7/bin/x2paddle", line 33, in <module>
      sys.exit(load_entry_point('x2paddle==1.2.3', 'console_scripts', 'x2paddle')())
    File "/home/ar/shaoxiong/envs/anaconda3/envs/py38_pytorch1.7/lib/python3.8/site-packages/x2paddle-1.2.3-py3.8.egg/x2paddle/convert.py", line 259, in main
      onnx2paddle(args.model, args.save_dir)
    File "/home/ar/shaoxiong/envs/anaconda3/envs/py38_pytorch1.7/lib/python3.8/site-packages/x2paddle-1.2.3-py3.8.egg/x2paddle/convert.py", line 165, in onnx2paddle
      mapper.paddle_graph.gen_model(save_dir)
    File "/home/ar/shaoxiong/envs/anaconda3/envs/py38_pytorch1.7/lib/python3.8/site-packages/x2paddle-1.2.3-py3.8.egg/x2paddle/core/program.py", line 274, in gen_model
      self.dygraph2static(save_dir, input_shapes, input_types)
    File "/home/ar/shaoxiong/envs/anaconda3/envs/py38_pytorch1.7/lib/python3.8/site-packages/x2paddle-1.2.3-py3.8.egg/x2paddle/core/program.py", line 553, in dygraph2static
      paddle.jit.save(static_model,
    File "<decorator-gen-67>", line 2, in save
      
    File "/home/ar/shaoxiong/envs/anaconda3/envs/py38_pytorch1.7/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/home/ar/shaoxiong/envs/anaconda3/envs/py38_pytorch1.7/lib/python3.8/site-packages/paddle/fluid/dygraph/base.py", line 40, in __impl__
      return func(*args, **kwargs)
    File "/home/ar/shaoxiong/envs/anaconda3/envs/py38_pytorch1.7/lib/python3.8/site-packages/paddle/fluid/dygraph/jit.py", line 718, in save
      concrete_program = static_func.concrete_program_specify_input_spec(
    File "/home/ar/shaoxiong/envs/anaconda3/envs/py38_pytorch1.7/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 487, in concrete_program_specify_input_spec
      concrete_program, _ = self.get_concrete_program(
    File "/home/ar/shaoxiong/envs/anaconda3/envs/py38_pytorch1.7/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 402, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "/home/ar/shaoxiong/envs/anaconda3/envs/py38_pytorch1.7/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 711, in __getitem__
      self._caches[item] = self._build_once(item)
    File "/home/ar/shaoxiong/envs/anaconda3/envs/py38_pytorch1.7/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 698, in _build_once
      concrete_program = ConcreteProgram.from_func_spec(
    File "<decorator-gen-65>", line 2, in from_func_spec
      
    File "/home/ar/shaoxiong/envs/anaconda3/envs/py38_pytorch1.7/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/home/ar/shaoxiong/envs/anaconda3/envs/py38_pytorch1.7/lib/python3.8/site-packages/paddle/fluid/dygraph/base.py", line 40, in __impl__
      return func(*args, **kwargs)
    File "/home/ar/shaoxiong/envs/anaconda3/envs/py38_pytorch1.7/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 652, in from_func_spec
      outputs = static_func(*inputs)
    File "v2_3_1_yolov6_best.pd/x2paddle_code.py", line 474, in forward
      x2paddle_992 = paddle.reshape(x=x2paddle_974, shape=[1, 3, 6, 40, 40])
    File "/home/ar/shaoxiong/envs/anaconda3/envs/py38_pytorch1.7/lib/python3.8/site-packages/paddle/tensor/manipulation.py", line 1575, in reshape
      return paddle.fluid.layers.reshape(x=x, shape=shape, name=name)
    File "/home/ar/shaoxiong/envs/anaconda3/envs/py38_pytorch1.7/lib/python3.8/site-packages/paddle/fluid/layers/nn.py", line 6202, in reshape
      helper.append_op(
    File "/home/ar/shaoxiong/envs/anaconda3/envs/py38_pytorch1.7/lib/python3.8/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/home/ar/shaoxiong/envs/anaconda3/envs/py38_pytorch1.7/lib/python3.8/site-packages/paddle/fluid/framework.py", line 2899, in append_op
      op = Operator(
    File "/home/ar/shaoxiong/envs/anaconda3/envs/py38_pytorch1.7/lib/python3.8/site-packages/paddle/fluid/framework.py", line 1977, in __init__
      for frame in traceback.extract_stack():

    InvalidArgumentError: The 'shape' in ReshapeOp is invalid. The input tensor X'size must be equal to the capacity of 'shape'. But received X's shape = [32, 18, 40, 40], X's size = 921600, 'shape' is [1, 3, 6, 40, 40], the capacity of 'shape' is 28800.
      [Hint: Expected capacity == in_size, but received capacity:28800 != in_size:921600.] (at /paddle/paddle/fluid/operators/reshape_op.cc:222)
      [operator < reshape2 > error]

```

**Comment by wanghaoshuang** [comment]
这个错误看起看和量化没关系。
你确定量化时用的input data的shape和原模型兼容吗？
建议您先在不用量化的情况下，保证推理可以正常执行。

**Comment by youngstu** [comment]
1、input_data shape和原模型shape是一致的，都是3*320*320
2、在不用量化的情况下，推理是正常的

**Comment by youngstu** [comment]
把quant_post_static() batch_size=1，batch_num 调大（保证有足够的图片输入）方法就解决了
