### ISSUE TITLE
离线量化PaddleDetection模型库的yolov3报错

### ISSUE THREAD

**Issue by LiquorPerfect** [PaddlePaddle/PaddleSlim#887]
paddle版本：paddlepaddle-gpu          2.1.1.post101
paddleslim版本：paddleslim                2.1.1
paddledetection版本：            release v2.2.0
CUDA版本：10.1
cudnn版本：7.6.5

**写在前面：**
1、paddleocr模型已经可以离线量化，静态sample_generator也已经自己实现。
2、在测试对paddledetection模型进行量化时出现报错。
目前已经尝试量化的模型有：yolov3_darknet53_270e_coco.yml、yolov3_darknet53_270e_voc.yml、yolov3_r50vd_dcn_270e_coco.yml，均出现一样的报错，模型参数直接模型库下载，在export_model为inference模型。

**报错信息如下：**
_**1、CPU版本报错，使用模型是yolov3_r50vd_dcn_270e_coco.yml**_

![image](https://user-images.githubusercontent.com/36955510/131336331-e1781d26-59d8-4ea3-af6e-3ef66bdbdf12.png)

_**2、GPU版本报错，使用模型是yolov3_r50vd_dcn_270e_coco.yml**_

2021-08-30 20:04:56,442-INFO: model_filename：model.pdmodel
2021-08-30 20:04:56,443-INFO: params_filename: model.pdiparams
2021-08-30 20:04:56,443-INFO: Load model and set data loader ...
W0830 20:04:56.580090 64299 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 10.1, Runtime API Version: 10.1
W0830 20:04:56.583691 64299 device_context.cc:422] device: 0, cuDNN Version: 7.6.
2021-08-30 20:05:06,263-INFO: Collect quantized variable names ...
2021-08-30 20:05:06,278-INFO: Preparation stage ...
Traceback (most recent call last):
  File "/xxx/anaconda3/envs/paddle_2.1.2_gpu/lib/python3.6/site-packages/paddleslim/quant/quanter.py", line 433, in quant_post_static
    post_training_quantization.quantize()
  File "/xxx/anaconda3/envs/paddle_2.1.2_gpu/lib/python3.6/site-packages/paddle/fluid/contrib/slim/quantization/post_training_quantization.py", line 370, in quantize
    scope=self._scope)
  File "/root/anaconda3/envs/paddle_2.1.2_gpu/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1110, in run
    six.reraise(*sys.exc_info())
  File "/xxx/anaconda3/envs/paddle_2.1.2_gpu/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/xxx/anaconda3/envs/paddle_2.1.2_gpu/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1108, in run
    return_merged=return_merged)
  File "/xxx/anaconda3/envs/paddle_2.1.2_gpu/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1239, in _run_impl
    use_program_cache=use_program_cache)
  File "/xxx/anaconda3/envs/paddle_2.1.2_gpu/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1329, in _run_program
    [fetch_var_name])
OSError: 

  Compile Traceback (most recent call last):       _**为什么这里会涉及到inference模型导出**_
    File "PaddleDetection-2.2.0/tools/export_model.py", line 114, in <module>
      main()
    File "PaddleDetection-2.2.0/tools/export_model.py", line 110, in main
      run(FLAGS, cfg)
    File "PaddleDetection-2.2.0/tools/export_model.py", line 78, in run
      trainer.export(FLAGS.output_dir)
    File "/mnt/ssd1/zhangjinlong21/paddle/PaddleDetection-2.2.0/ppdet/engine/trainer.py", line 573, in export
      input_spec, static_model.forward.main_program,
    File "/root/anaconda3/envs/paddle_2.1.2_gpu/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 534, in main_program
      concrete_program = self.concrete_program
    File "/root/anaconda3/envs/paddle_2.1.2_gpu/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 454, in concrete_program
      return self.concrete_program_specify_input_spec(input_spec=None)
    File "/root/anaconda3/envs/paddle_2.1.2_gpu/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 488, in concrete_program_specify_input_spec
      *desired_input_spec)
    File "/root/anaconda3/envs/paddle_2.1.2_gpu/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 402, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "/root/anaconda3/envs/paddle_2.1.2_gpu/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 711, in __getitem__
      self._caches[item] = self._build_once(item)
    File "/root/anaconda3/envs/paddle_2.1.2_gpu/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 702, in _build_once
      class_instance=cache_key.class_instance)
    File "<decorator-gen-65>", line 2, in from_func_spec
      
    File "/root/anaconda3/envs/paddle_2.1.2_gpu/lib/python3.6/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/root/anaconda3/envs/paddle_2.1.2_gpu/lib/python3.6/site-packages/paddle/fluid/dygraph/base.py", line 40, in __impl__
      return func(*args, **kwargs)
    File "/root/anaconda3/envs/paddle_2.1.2_gpu/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 652, in from_func_spec
      outputs = static_func(*inputs)
    File "/tmp/tmpc1ycg8eo.py", line 27, in forward
      false_fn_1, (), (), (out,))
    File "/root/anaconda3/envs/paddle_2.1.2_gpu/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 210, in convert_ifelse
      return _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/root/anaconda3/envs/paddle_2.1.2_gpu/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 235, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/xxxxPaddleDetection-2.2.0/ppdet/modeling/architectures/meta_arch.py", line 28, in forward
      out = self.get_pred()
    File "/xxxx/PaddleDetection-2.2.0/ppdet/modeling/architectures/yolo.py", line 124, in get_pred
      return self._forward()
    File "/xxxx/PaddleDetection-2.2.0/ppdet/modeling/architectures/yolo.py", line 79, in _forward
      body_feats = self.backbone(self.inputs)
    File "/xxxxx/paddle_2.1.2_gpu/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/xxxx/paddle/PaddleDetection-2.2.0/ppdet/modeling/backbones/resnet.py", line 582, in forward
      conv1 = self.conv1(x)
    File "/root/anaconda3/envs/paddle_2.1.2_gpu/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/root/anaconda3/envs/paddle_2.1.2_gpu/lib/python3.6/site-packages/paddle/fluid/dygraph/container.py", line 98, in forward
      input = layer(input)
    File "/root/anaconda3/envs/paddle_2.1.2_gpu/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/tmp/tmp59fdoqes.py", line 22, in forward
      (inputs, self), (out,))
    File "/root/anaconda3/envs/paddle_2.1.2_gpu/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 210, in convert_ifelse
      return _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/root/anaconda3/envs/paddle_2.1.2_gpu/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 235, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/xxxxx/paddle/PaddleDetection-2.2.0/ppdet/modeling/backbones/resnet.py", line 122, in forward
      out = self.conv(inputs)
    File "/root/anaconda3/envs/paddle_2.1.2_gpu/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/root/anaconda3/envs/paddle_2.1.2_gpu/lib/python3.6/site-packages/paddle/nn/layer/conv.py", line 667, in forward
      use_cudnn=self._use_cudnn)
    File "/root/anaconda3/envs/paddle_2.1.2_gpu/lib/python3.6/site-packages/paddle/nn/functional/conv.py", line 139, in _conv_nd
      type=op_type, inputs=inputs, outputs=outputs, attrs=attrs)
    File "/root/anaconda3/envs/paddle_2.1.2_gpu/lib/python3.6/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/root/anaconda3/envs/paddle_2.1.2_gpu/lib/python3.6/site-packages/paddle/fluid/framework.py", line 2905, in append_op
      attrs=kwargs.get("attrs", None))
    File "/root/anaconda3/envs/paddle_2.1.2_gpu/lib/python3.6/site-packages/paddle/fluid/framework.py", line 1977, in __init__
      for frame in traceback.extract_stack():

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string > > const&, bool, bool)
1   paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool)
2   paddle::framework::Executor::RunPartialPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, long, long, bool, bool, bool)
3   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
4   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
5   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
6   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::CUDNNConvOpKernel<float>, paddle::operators::CUDNNConvOpKernel<double>, paddle::operators::CUDNNConvOpKernel<paddle::platform::float16> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
7   paddle::operators::CUDNNConvOpKernel<float>::Compute(paddle::framework::ExecutionContext const&) const
8   paddle::platform::TensorDescriptor::set(paddle::framework::Tensor const&, cudnnTensorFormat_t)
9   paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
10  paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
ExternalError:  Cudnn error, CUDNN_STATUS_BAD_PARAM  (at /paddle/paddle/fluid/platform/cudnn_desc.h:163)
  [operator < conv2d > error]

**猜测**：会不会由于export_model.py导出模型的时候，detection inference模型的保存还是老版本的接口导致的。

**Comment by XGZhang11** [comment]
请使用paddledetection的静态图模型导出inference model以及静态图下的dataloader：https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.2/static 。目前因为dataloader的原因，需要使用paddledetection静态图模型导出的inference model。目前动态图的离线量化功能正在开发。

**Comment by LiquorPerfect** [comment]
@XGZhang11 目前离线量化支持双输入或者多输入模型的量化嘛

**Comment by XGZhang11** [comment]
目前是支持多输入的模型的
