### ISSUE TITLE
slim剪裁识别模型错误输出：？

### ISSUE THREAD

**Issue by EricHuiK** [PaddlePaddle/PaddleSlim#915]
eval model:: 100%|?????????????????????????????????????????????????????????????????????????????????????????????| 160/160 [01:02<00:00,  2.57it/s]
[2021/11/04 07:12:04] root INFO: metric['acc']: 0.0
eval model:: 100%|?????????????????????????????????????????????????????????????????????????????????????????????| 160/160 [01:00<00:00,  2.66it/s]
[2021/11/04 07:13:04] root INFO: metric['acc']: 0.0
Traceback (most recent call last):
  File "deploy/slim/prune/export_prune_model.py", line 127, in <module>
    main(config, device, logger, vdl_writer)
  File "deploy/slim/prune/export_prune_model.py", line 73, in main
    params_sensitive = pruner.sensitive(
  File "/usr/local/lib/python3.8/dist-packages/paddleslim-1.0.0-py3.8.egg/paddleslim/dygraph/prune/filter_pruner.py", line 118, in sensitive
  File "/usr/local/lib/python3.8/dist-packages/paddleslim-1.0.0-py3.8.egg/paddleslim/dygraph/prune/filter_pruner.py", line 264, in _cal_sensitive
ZeroDivisionError: float division by zero

**Comment by wanghaoshuang** [comment]
感谢反馈，剪裁模块的敏感度分析需要在训好的模型上做。
我们会完善下log提示信息。
