### ISSUE TITLE
ResNeXt101_vd_32x4d 参考PaddleClas 模板剪枝报错。

### ISSUE THREAD

**Issue by ChrisMengxl** [PaddlePaddle/PaddleSlim#976]
ResNeXt101_vd_32x4d 剪枝报错。 其中，版本：
PaddleSlim 2.1.1
PaddleClas 2.2
PaddlePadddle 2.1.2

2022-02-14 22:20:16,608-INFO: change groups from 32 to 22 for res5c_branch2b_weights.
Traceback (most recent call last):
  File "tools/train.py", line 31, in <module>
    engine = Engine(config, mode="train")
  File "/home/aistudio/PaddleClas/ppcls/engine/engine.py", line 194, in __init__
    self.pruner = get_pruner(self.config, self.model)
  File "/home/aistudio/PaddleClas/ppcls/engine/slim/prune.py", line 35, in get_pruner
    _prune_model(pruner, config, model)
  File "/home/aistudio/PaddleClas/ppcls/engine/slim/prune.py", line 59, in _prune_model
    flops(model, [1] + config["Global"]["image_shape"]) / 1e9,
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/analysis/flops.py", line 133, in dygraph_flops
    program = dygraph2program(model, inputs)
  File "<decorator-gen-279>", line 2, in dygraph2program
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 227, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/core/dygraph.py", line 119, in dygraph2program
    original_outputs = layer(*inputs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleClas/ppcls/arch/backbone/model_zoo/resnext_vd.py", line 246, in forward
    y = block(y)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleClas/ppcls/arch/backbone/model_zoo/resnext_vd.py", line 141, in forward
    conv1 = self.conv1(y)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleClas/ppcls/arch/backbone/model_zoo/resnext_vd.py", line 90, in forward
    y = self._conv(inputs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/layer/conv.py", line 667, in forward
    use_cudnn=self._use_cudnn)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/functional/conv.py", line 114, in _conv_nd
    pre_bias = getattr(core.ops, op_type)(x, weight, *attrs)
ValueError: (InvalidArgument) The number of output's channels (filter's first dimension) of Op(Conv) should be divided by groups. But received: the output channels is 90, the filter's shape is [90, 4, 3, 3], the groups is 22.
  [Hint: Expected filter_dims[0] % groups == 0, but received filter_dims[0] % groups:2 != 0:0.] (at /paddle/paddle/fluid/operators/conv_op.cc:108)
  [operator < conv2d > error]

**Comment by ChrisMengxl** [comment]
个人配置文件问题。Sorry。
